#ifndef GAEACTOR_TRANSMIT_GLOBAL_H
#define GAEACTOR_TRANSMIT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GAEACTOR_TRANSMIT_LIBRARY)
#  define GAEACTOR_TRANSMIT_EXPORT Q_DECL_EXPORT
#else
#  define GAEACTOR_TRANSMIT_EXPORT Q_DECL_IMPORT
#endif

#endif // GAEACTOR_TRANSMIT_GLOBAL_H
