#ifndef GAEACTOR_INTERACTIONS_GLOBAL_H
#define GAEACTOR_INTERACTIONS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GAEACTOR_INTERACTIONS_LIBRARY)
#  define GAEACTOR_INTERACTIONS_EXPORT Q_DECL_EXPORT
#else
#  define GAEACTOR_INTERACTIONS_EXPORT Q_DECL_IMPORT
#endif

#endif // GAEACTOR_INTERACTIONS_GLOBAL_H
