#ifndef GAEACTOR_AUDITIONS_GLOBAL_H
#define GAEACTOR_AUDITIONS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GAEACTOR_AUDITIONS_LIBRARY)
#  define GAEACTOR_AUDITIONS_EXPORT Q_DECL_EXPORT
#else
#  define GAEACTOR_AUDITIONS_EXPORT Q_DECL_IMPORT
#endif

#endif // GAEACTOR_AUDITIONS_GLOBAL_H
