#ifndef GAEACTOR_EVENT_ENGINE_GLOBAL_H
#define GAEACTOR_EVENT_ENGINE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GAEACTOR_EVENT_ENGINE_LIBRARY)
#  define GAEACTOR_EVENT_ENGINE_EXPORT Q_DECL_EXPORT
#else
#  define GAEACTOR_EVENT_ENGINE_EXPORT Q_DECL_IMPORT
#endif

#endif // GAEACTOR_EVENT_ENGINE_GLOBAL_H
