#ifndef GAEACTOR_ENVIRONMENT_GLOBAL_H
#define GAEACTOR_ENVIRONMENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GAEACTOR_ENVIRONMENT_LIBRARY)
#  define GAEACTOR_ENVIRONMENT_EXPORT Q_DECL_EXPORT
#else
#  define GAEACTOR_ENVIRONMENT_EXPORT Q_DECL_IMPORT
#endif

#endif // GAEACTOR_ENVIRONMENT_GLOBAL_H
