// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AgentRelationInfo.proto

#include "AgentRelationInfo.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace msg {
namespace AgentRelationInfo {
PROTOBUF_CONSTEXPR msg_AgentInfo::msg_AgentInfo(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.agentid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.sensingmediaid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.timestamp_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.sim_timestamp_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.iffcode_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.lon_)*/0
  , /*decltype(_impl_.lat_)*/0
  , /*decltype(_impl_.amsl_)*/0
  , /*decltype(_impl_.ref_)*/0
  , /*decltype(_impl_.roll_)*/0
  , /*decltype(_impl_.pitch_)*/0
  , /*decltype(_impl_.yaw_)*/0
  , /*decltype(_impl_.speed_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct msg_AgentInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR msg_AgentInfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~msg_AgentInfoDefaultTypeInternal() {}
  union {
    msg_AgentInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 msg_AgentInfoDefaultTypeInternal _msg_AgentInfo_default_instance_;
PROTOBUF_CONSTEXPR msg_AgentRelationInfo::msg_AgentRelationInfo(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.updatetimestamp_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.src_agent_)*/nullptr
  , /*decltype(_impl_.dst_agent_)*/nullptr
  , /*decltype(_impl_.relationtype_)*/0
  , /*decltype(_impl_.refreshtype_)*/0
  , /*decltype(_impl_.distance_)*/0
  , /*decltype(_impl_.usage_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct msg_AgentRelationInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR msg_AgentRelationInfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~msg_AgentRelationInfoDefaultTypeInternal() {}
  union {
    msg_AgentRelationInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 msg_AgentRelationInfoDefaultTypeInternal _msg_AgentRelationInfo_default_instance_;
}  // namespace AgentRelationInfo
}  // namespace msg
static ::_pb::Metadata file_level_metadata_AgentRelationInfo_2eproto[2];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_AgentRelationInfo_2eproto[2];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_AgentRelationInfo_2eproto = nullptr;

const uint32_t TableStruct_AgentRelationInfo_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::msg::AgentRelationInfo::msg_AgentInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::msg::AgentRelationInfo::msg_AgentInfo, _impl_.agentid_),
  PROTOBUF_FIELD_OFFSET(::msg::AgentRelationInfo::msg_AgentInfo, _impl_.sensingmediaid_),
  PROTOBUF_FIELD_OFFSET(::msg::AgentRelationInfo::msg_AgentInfo, _impl_.timestamp_),
  PROTOBUF_FIELD_OFFSET(::msg::AgentRelationInfo::msg_AgentInfo, _impl_.sim_timestamp_),
  PROTOBUF_FIELD_OFFSET(::msg::AgentRelationInfo::msg_AgentInfo, _impl_.lon_),
  PROTOBUF_FIELD_OFFSET(::msg::AgentRelationInfo::msg_AgentInfo, _impl_.lat_),
  PROTOBUF_FIELD_OFFSET(::msg::AgentRelationInfo::msg_AgentInfo, _impl_.amsl_),
  PROTOBUF_FIELD_OFFSET(::msg::AgentRelationInfo::msg_AgentInfo, _impl_.ref_),
  PROTOBUF_FIELD_OFFSET(::msg::AgentRelationInfo::msg_AgentInfo, _impl_.roll_),
  PROTOBUF_FIELD_OFFSET(::msg::AgentRelationInfo::msg_AgentInfo, _impl_.pitch_),
  PROTOBUF_FIELD_OFFSET(::msg::AgentRelationInfo::msg_AgentInfo, _impl_.yaw_),
  PROTOBUF_FIELD_OFFSET(::msg::AgentRelationInfo::msg_AgentInfo, _impl_.speed_),
  PROTOBUF_FIELD_OFFSET(::msg::AgentRelationInfo::msg_AgentInfo, _impl_.iffcode_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::msg::AgentRelationInfo::msg_AgentRelationInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::msg::AgentRelationInfo::msg_AgentRelationInfo, _impl_.src_agent_),
  PROTOBUF_FIELD_OFFSET(::msg::AgentRelationInfo::msg_AgentRelationInfo, _impl_.dst_agent_),
  PROTOBUF_FIELD_OFFSET(::msg::AgentRelationInfo::msg_AgentRelationInfo, _impl_.relationtype_),
  PROTOBUF_FIELD_OFFSET(::msg::AgentRelationInfo::msg_AgentRelationInfo, _impl_.refreshtype_),
  PROTOBUF_FIELD_OFFSET(::msg::AgentRelationInfo::msg_AgentRelationInfo, _impl_.updatetimestamp_),
  PROTOBUF_FIELD_OFFSET(::msg::AgentRelationInfo::msg_AgentRelationInfo, _impl_.distance_),
  PROTOBUF_FIELD_OFFSET(::msg::AgentRelationInfo::msg_AgentRelationInfo, _impl_.usage_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::msg::AgentRelationInfo::msg_AgentInfo)},
  { 19, -1, -1, sizeof(::msg::AgentRelationInfo::msg_AgentRelationInfo)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::msg::AgentRelationInfo::_msg_AgentInfo_default_instance_._instance,
  &::msg::AgentRelationInfo::_msg_AgentRelationInfo_default_instance_._instance,
};

const char descriptor_table_protodef_AgentRelationInfo_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\027AgentRelationInfo.proto\022\025msg.AgentRela"
  "tionInfo\"\341\001\n\rmsg_AgentInfo\022\017\n\007agentid\030\001 "
  "\001(\t\022\026\n\016sensingmediaid\030\002 \001(\t\022\021\n\ttimestamp"
  "\030\003 \001(\t\022\025\n\rsim_timestamp\030\004 \001(\t\022\013\n\003lon\030\005 \001"
  "(\001\022\013\n\003lat\030\006 \001(\001\022\014\n\004amsl\030\007 \001(\001\022\013\n\003ref\030\010 \001"
  "(\005\022\014\n\004roll\030\t \001(\002\022\r\n\005pitch\030\n \001(\002\022\013\n\003yaw\030\013"
  " \001(\002\022\r\n\005speed\030\014 \001(\002\022\017\n\007iffcode\030\r \001(\t\"\273\002\n"
  "\025msg_AgentRelationInfo\0227\n\tsrc_agent\030\001 \001("
  "\0132$.msg.AgentRelationInfo.msg_AgentInfo\022"
  "7\n\tdst_agent\030\002 \001(\0132$.msg.AgentRelationIn"
  "fo.msg_AgentInfo\022;\n\014relationtype\030\003 \001(\0162%"
  ".msg.AgentRelationInfo.E_RELATIONTYPE\0229\n"
  "\013refreshtype\030\004 \001(\0162$.msg.AgentRelationIn"
  "fo.E_REFRESHTYPE\022\027\n\017updatetimestamp\030\005 \001("
  "\t\022\020\n\010distance\030\006 \001(\001\022\r\n\005usage\030\007 \001(\005*\373\001\n\016E"
  "_RELATIONTYPE\022\032\n\026E_RELATIONTYPE_UNKNOWN\020"
  "\000\022\027\n\023E_RELATIONTYPE_COMM\020\001\022\030\n\024E_RELATION"
  "TYPE_TRACK\020\002\022\031\n\025E_RELATIONTYPE_DETECT\020\003\022"
  "\036\n\032E_RELATIONTYPE_IFF_REQUEST\020\004\022\037\n\033E_REL"
  "ATIONTYPE_IFF_RESPONSE\020\005\022\035\n\031E_RELATIONTY"
  "PE_IFF_THREAT\020\006\022\037\n\033E_RELATIONTYPE_IFF_NO"
  "THREAT\020\007*u\n\rE_REFRESHTYPE\022\031\n\025E_REFRESHTY"
  "PE_UNKNOWN\020\000\022\025\n\021E_REFRESHTYPE_ADD\020\001\022\030\n\024E"
  "_REFRESHTYPE_REMOVE\020\002\022\030\n\024E_REFRESHTYPE_U"
  "PDATE\020\003b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_AgentRelationInfo_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_AgentRelationInfo_2eproto = {
    false, false, 975, descriptor_table_protodef_AgentRelationInfo_2eproto,
    "AgentRelationInfo.proto",
    &descriptor_table_AgentRelationInfo_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_AgentRelationInfo_2eproto::offsets,
    file_level_metadata_AgentRelationInfo_2eproto, file_level_enum_descriptors_AgentRelationInfo_2eproto,
    file_level_service_descriptors_AgentRelationInfo_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_AgentRelationInfo_2eproto_getter() {
  return &descriptor_table_AgentRelationInfo_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_AgentRelationInfo_2eproto(&descriptor_table_AgentRelationInfo_2eproto);
namespace msg {
namespace AgentRelationInfo {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* E_RELATIONTYPE_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_AgentRelationInfo_2eproto);
  return file_level_enum_descriptors_AgentRelationInfo_2eproto[0];
}
bool E_RELATIONTYPE_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* E_REFRESHTYPE_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_AgentRelationInfo_2eproto);
  return file_level_enum_descriptors_AgentRelationInfo_2eproto[1];
}
bool E_REFRESHTYPE_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class msg_AgentInfo::_Internal {
 public:
};

msg_AgentInfo::msg_AgentInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:msg.AgentRelationInfo.msg_AgentInfo)
}
msg_AgentInfo::msg_AgentInfo(const msg_AgentInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  msg_AgentInfo* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.agentid_){}
    , decltype(_impl_.sensingmediaid_){}
    , decltype(_impl_.timestamp_){}
    , decltype(_impl_.sim_timestamp_){}
    , decltype(_impl_.iffcode_){}
    , decltype(_impl_.lon_){}
    , decltype(_impl_.lat_){}
    , decltype(_impl_.amsl_){}
    , decltype(_impl_.ref_){}
    , decltype(_impl_.roll_){}
    , decltype(_impl_.pitch_){}
    , decltype(_impl_.yaw_){}
    , decltype(_impl_.speed_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.agentid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.agentid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_agentid().empty()) {
    _this->_impl_.agentid_.Set(from._internal_agentid(), 
      _this->GetArenaForAllocation());
  }
  _impl_.sensingmediaid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sensingmediaid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_sensingmediaid().empty()) {
    _this->_impl_.sensingmediaid_.Set(from._internal_sensingmediaid(), 
      _this->GetArenaForAllocation());
  }
  _impl_.timestamp_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.timestamp_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_timestamp().empty()) {
    _this->_impl_.timestamp_.Set(from._internal_timestamp(), 
      _this->GetArenaForAllocation());
  }
  _impl_.sim_timestamp_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sim_timestamp_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_sim_timestamp().empty()) {
    _this->_impl_.sim_timestamp_.Set(from._internal_sim_timestamp(), 
      _this->GetArenaForAllocation());
  }
  _impl_.iffcode_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.iffcode_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_iffcode().empty()) {
    _this->_impl_.iffcode_.Set(from._internal_iffcode(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.lon_, &from._impl_.lon_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.speed_) -
    reinterpret_cast<char*>(&_impl_.lon_)) + sizeof(_impl_.speed_));
  // @@protoc_insertion_point(copy_constructor:msg.AgentRelationInfo.msg_AgentInfo)
}

inline void msg_AgentInfo::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.agentid_){}
    , decltype(_impl_.sensingmediaid_){}
    , decltype(_impl_.timestamp_){}
    , decltype(_impl_.sim_timestamp_){}
    , decltype(_impl_.iffcode_){}
    , decltype(_impl_.lon_){0}
    , decltype(_impl_.lat_){0}
    , decltype(_impl_.amsl_){0}
    , decltype(_impl_.ref_){0}
    , decltype(_impl_.roll_){0}
    , decltype(_impl_.pitch_){0}
    , decltype(_impl_.yaw_){0}
    , decltype(_impl_.speed_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.agentid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.agentid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.sensingmediaid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sensingmediaid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.timestamp_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.timestamp_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.sim_timestamp_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sim_timestamp_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.iffcode_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.iffcode_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

msg_AgentInfo::~msg_AgentInfo() {
  // @@protoc_insertion_point(destructor:msg.AgentRelationInfo.msg_AgentInfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void msg_AgentInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.agentid_.Destroy();
  _impl_.sensingmediaid_.Destroy();
  _impl_.timestamp_.Destroy();
  _impl_.sim_timestamp_.Destroy();
  _impl_.iffcode_.Destroy();
}

void msg_AgentInfo::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void msg_AgentInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:msg.AgentRelationInfo.msg_AgentInfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.agentid_.ClearToEmpty();
  _impl_.sensingmediaid_.ClearToEmpty();
  _impl_.timestamp_.ClearToEmpty();
  _impl_.sim_timestamp_.ClearToEmpty();
  _impl_.iffcode_.ClearToEmpty();
  ::memset(&_impl_.lon_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.speed_) -
      reinterpret_cast<char*>(&_impl_.lon_)) + sizeof(_impl_.speed_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* msg_AgentInfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string agentid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_agentid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "msg.AgentRelationInfo.msg_AgentInfo.agentid"));
        } else
          goto handle_unusual;
        continue;
      // string sensingmediaid = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_sensingmediaid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "msg.AgentRelationInfo.msg_AgentInfo.sensingmediaid"));
        } else
          goto handle_unusual;
        continue;
      // string timestamp = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_timestamp();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "msg.AgentRelationInfo.msg_AgentInfo.timestamp"));
        } else
          goto handle_unusual;
        continue;
      // string sim_timestamp = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_sim_timestamp();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "msg.AgentRelationInfo.msg_AgentInfo.sim_timestamp"));
        } else
          goto handle_unusual;
        continue;
      // double lon = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 41)) {
          _impl_.lon_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double lat = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 49)) {
          _impl_.lat_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double amsl = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 57)) {
          _impl_.amsl_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // int32 ref = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          _impl_.ref_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // float roll = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 77)) {
          _impl_.roll_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float pitch = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 85)) {
          _impl_.pitch_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float yaw = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 93)) {
          _impl_.yaw_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float speed = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 101)) {
          _impl_.speed_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // string iffcode = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 106)) {
          auto str = _internal_mutable_iffcode();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "msg.AgentRelationInfo.msg_AgentInfo.iffcode"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* msg_AgentInfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:msg.AgentRelationInfo.msg_AgentInfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string agentid = 1;
  if (!this->_internal_agentid().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_agentid().data(), static_cast<int>(this->_internal_agentid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "msg.AgentRelationInfo.msg_AgentInfo.agentid");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_agentid(), target);
  }

  // string sensingmediaid = 2;
  if (!this->_internal_sensingmediaid().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sensingmediaid().data(), static_cast<int>(this->_internal_sensingmediaid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "msg.AgentRelationInfo.msg_AgentInfo.sensingmediaid");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_sensingmediaid(), target);
  }

  // string timestamp = 3;
  if (!this->_internal_timestamp().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_timestamp().data(), static_cast<int>(this->_internal_timestamp().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "msg.AgentRelationInfo.msg_AgentInfo.timestamp");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_timestamp(), target);
  }

  // string sim_timestamp = 4;
  if (!this->_internal_sim_timestamp().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sim_timestamp().data(), static_cast<int>(this->_internal_sim_timestamp().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "msg.AgentRelationInfo.msg_AgentInfo.sim_timestamp");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_sim_timestamp(), target);
  }

  // double lon = 5;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_lon = this->_internal_lon();
  uint64_t raw_lon;
  memcpy(&raw_lon, &tmp_lon, sizeof(tmp_lon));
  if (raw_lon != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(5, this->_internal_lon(), target);
  }

  // double lat = 6;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_lat = this->_internal_lat();
  uint64_t raw_lat;
  memcpy(&raw_lat, &tmp_lat, sizeof(tmp_lat));
  if (raw_lat != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(6, this->_internal_lat(), target);
  }

  // double amsl = 7;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_amsl = this->_internal_amsl();
  uint64_t raw_amsl;
  memcpy(&raw_amsl, &tmp_amsl, sizeof(tmp_amsl));
  if (raw_amsl != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(7, this->_internal_amsl(), target);
  }

  // int32 ref = 8;
  if (this->_internal_ref() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(8, this->_internal_ref(), target);
  }

  // float roll = 9;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_roll = this->_internal_roll();
  uint32_t raw_roll;
  memcpy(&raw_roll, &tmp_roll, sizeof(tmp_roll));
  if (raw_roll != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(9, this->_internal_roll(), target);
  }

  // float pitch = 10;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_pitch = this->_internal_pitch();
  uint32_t raw_pitch;
  memcpy(&raw_pitch, &tmp_pitch, sizeof(tmp_pitch));
  if (raw_pitch != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(10, this->_internal_pitch(), target);
  }

  // float yaw = 11;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_yaw = this->_internal_yaw();
  uint32_t raw_yaw;
  memcpy(&raw_yaw, &tmp_yaw, sizeof(tmp_yaw));
  if (raw_yaw != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(11, this->_internal_yaw(), target);
  }

  // float speed = 12;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_speed = this->_internal_speed();
  uint32_t raw_speed;
  memcpy(&raw_speed, &tmp_speed, sizeof(tmp_speed));
  if (raw_speed != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(12, this->_internal_speed(), target);
  }

  // string iffcode = 13;
  if (!this->_internal_iffcode().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_iffcode().data(), static_cast<int>(this->_internal_iffcode().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "msg.AgentRelationInfo.msg_AgentInfo.iffcode");
    target = stream->WriteStringMaybeAliased(
        13, this->_internal_iffcode(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:msg.AgentRelationInfo.msg_AgentInfo)
  return target;
}

size_t msg_AgentInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:msg.AgentRelationInfo.msg_AgentInfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string agentid = 1;
  if (!this->_internal_agentid().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_agentid());
  }

  // string sensingmediaid = 2;
  if (!this->_internal_sensingmediaid().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sensingmediaid());
  }

  // string timestamp = 3;
  if (!this->_internal_timestamp().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_timestamp());
  }

  // string sim_timestamp = 4;
  if (!this->_internal_sim_timestamp().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sim_timestamp());
  }

  // string iffcode = 13;
  if (!this->_internal_iffcode().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_iffcode());
  }

  // double lon = 5;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_lon = this->_internal_lon();
  uint64_t raw_lon;
  memcpy(&raw_lon, &tmp_lon, sizeof(tmp_lon));
  if (raw_lon != 0) {
    total_size += 1 + 8;
  }

  // double lat = 6;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_lat = this->_internal_lat();
  uint64_t raw_lat;
  memcpy(&raw_lat, &tmp_lat, sizeof(tmp_lat));
  if (raw_lat != 0) {
    total_size += 1 + 8;
  }

  // double amsl = 7;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_amsl = this->_internal_amsl();
  uint64_t raw_amsl;
  memcpy(&raw_amsl, &tmp_amsl, sizeof(tmp_amsl));
  if (raw_amsl != 0) {
    total_size += 1 + 8;
  }

  // int32 ref = 8;
  if (this->_internal_ref() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_ref());
  }

  // float roll = 9;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_roll = this->_internal_roll();
  uint32_t raw_roll;
  memcpy(&raw_roll, &tmp_roll, sizeof(tmp_roll));
  if (raw_roll != 0) {
    total_size += 1 + 4;
  }

  // float pitch = 10;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_pitch = this->_internal_pitch();
  uint32_t raw_pitch;
  memcpy(&raw_pitch, &tmp_pitch, sizeof(tmp_pitch));
  if (raw_pitch != 0) {
    total_size += 1 + 4;
  }

  // float yaw = 11;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_yaw = this->_internal_yaw();
  uint32_t raw_yaw;
  memcpy(&raw_yaw, &tmp_yaw, sizeof(tmp_yaw));
  if (raw_yaw != 0) {
    total_size += 1 + 4;
  }

  // float speed = 12;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_speed = this->_internal_speed();
  uint32_t raw_speed;
  memcpy(&raw_speed, &tmp_speed, sizeof(tmp_speed));
  if (raw_speed != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData msg_AgentInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    msg_AgentInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*msg_AgentInfo::GetClassData() const { return &_class_data_; }


void msg_AgentInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<msg_AgentInfo*>(&to_msg);
  auto& from = static_cast<const msg_AgentInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:msg.AgentRelationInfo.msg_AgentInfo)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_agentid().empty()) {
    _this->_internal_set_agentid(from._internal_agentid());
  }
  if (!from._internal_sensingmediaid().empty()) {
    _this->_internal_set_sensingmediaid(from._internal_sensingmediaid());
  }
  if (!from._internal_timestamp().empty()) {
    _this->_internal_set_timestamp(from._internal_timestamp());
  }
  if (!from._internal_sim_timestamp().empty()) {
    _this->_internal_set_sim_timestamp(from._internal_sim_timestamp());
  }
  if (!from._internal_iffcode().empty()) {
    _this->_internal_set_iffcode(from._internal_iffcode());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_lon = from._internal_lon();
  uint64_t raw_lon;
  memcpy(&raw_lon, &tmp_lon, sizeof(tmp_lon));
  if (raw_lon != 0) {
    _this->_internal_set_lon(from._internal_lon());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_lat = from._internal_lat();
  uint64_t raw_lat;
  memcpy(&raw_lat, &tmp_lat, sizeof(tmp_lat));
  if (raw_lat != 0) {
    _this->_internal_set_lat(from._internal_lat());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_amsl = from._internal_amsl();
  uint64_t raw_amsl;
  memcpy(&raw_amsl, &tmp_amsl, sizeof(tmp_amsl));
  if (raw_amsl != 0) {
    _this->_internal_set_amsl(from._internal_amsl());
  }
  if (from._internal_ref() != 0) {
    _this->_internal_set_ref(from._internal_ref());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_roll = from._internal_roll();
  uint32_t raw_roll;
  memcpy(&raw_roll, &tmp_roll, sizeof(tmp_roll));
  if (raw_roll != 0) {
    _this->_internal_set_roll(from._internal_roll());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_pitch = from._internal_pitch();
  uint32_t raw_pitch;
  memcpy(&raw_pitch, &tmp_pitch, sizeof(tmp_pitch));
  if (raw_pitch != 0) {
    _this->_internal_set_pitch(from._internal_pitch());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_yaw = from._internal_yaw();
  uint32_t raw_yaw;
  memcpy(&raw_yaw, &tmp_yaw, sizeof(tmp_yaw));
  if (raw_yaw != 0) {
    _this->_internal_set_yaw(from._internal_yaw());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_speed = from._internal_speed();
  uint32_t raw_speed;
  memcpy(&raw_speed, &tmp_speed, sizeof(tmp_speed));
  if (raw_speed != 0) {
    _this->_internal_set_speed(from._internal_speed());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void msg_AgentInfo::CopyFrom(const msg_AgentInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:msg.AgentRelationInfo.msg_AgentInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool msg_AgentInfo::IsInitialized() const {
  return true;
}

void msg_AgentInfo::InternalSwap(msg_AgentInfo* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.agentid_, lhs_arena,
      &other->_impl_.agentid_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.sensingmediaid_, lhs_arena,
      &other->_impl_.sensingmediaid_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.timestamp_, lhs_arena,
      &other->_impl_.timestamp_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.sim_timestamp_, lhs_arena,
      &other->_impl_.sim_timestamp_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.iffcode_, lhs_arena,
      &other->_impl_.iffcode_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(msg_AgentInfo, _impl_.speed_)
      + sizeof(msg_AgentInfo::_impl_.speed_)
      - PROTOBUF_FIELD_OFFSET(msg_AgentInfo, _impl_.lon_)>(
          reinterpret_cast<char*>(&_impl_.lon_),
          reinterpret_cast<char*>(&other->_impl_.lon_));
}

::PROTOBUF_NAMESPACE_ID::Metadata msg_AgentInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_AgentRelationInfo_2eproto_getter, &descriptor_table_AgentRelationInfo_2eproto_once,
      file_level_metadata_AgentRelationInfo_2eproto[0]);
}

// ===================================================================

class msg_AgentRelationInfo::_Internal {
 public:
  static const ::msg::AgentRelationInfo::msg_AgentInfo& src_agent(const msg_AgentRelationInfo* msg);
  static const ::msg::AgentRelationInfo::msg_AgentInfo& dst_agent(const msg_AgentRelationInfo* msg);
};

const ::msg::AgentRelationInfo::msg_AgentInfo&
msg_AgentRelationInfo::_Internal::src_agent(const msg_AgentRelationInfo* msg) {
  return *msg->_impl_.src_agent_;
}
const ::msg::AgentRelationInfo::msg_AgentInfo&
msg_AgentRelationInfo::_Internal::dst_agent(const msg_AgentRelationInfo* msg) {
  return *msg->_impl_.dst_agent_;
}
msg_AgentRelationInfo::msg_AgentRelationInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:msg.AgentRelationInfo.msg_AgentRelationInfo)
}
msg_AgentRelationInfo::msg_AgentRelationInfo(const msg_AgentRelationInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  msg_AgentRelationInfo* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.updatetimestamp_){}
    , decltype(_impl_.src_agent_){nullptr}
    , decltype(_impl_.dst_agent_){nullptr}
    , decltype(_impl_.relationtype_){}
    , decltype(_impl_.refreshtype_){}
    , decltype(_impl_.distance_){}
    , decltype(_impl_.usage_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.updatetimestamp_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.updatetimestamp_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_updatetimestamp().empty()) {
    _this->_impl_.updatetimestamp_.Set(from._internal_updatetimestamp(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_src_agent()) {
    _this->_impl_.src_agent_ = new ::msg::AgentRelationInfo::msg_AgentInfo(*from._impl_.src_agent_);
  }
  if (from._internal_has_dst_agent()) {
    _this->_impl_.dst_agent_ = new ::msg::AgentRelationInfo::msg_AgentInfo(*from._impl_.dst_agent_);
  }
  ::memcpy(&_impl_.relationtype_, &from._impl_.relationtype_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.usage_) -
    reinterpret_cast<char*>(&_impl_.relationtype_)) + sizeof(_impl_.usage_));
  // @@protoc_insertion_point(copy_constructor:msg.AgentRelationInfo.msg_AgentRelationInfo)
}

inline void msg_AgentRelationInfo::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.updatetimestamp_){}
    , decltype(_impl_.src_agent_){nullptr}
    , decltype(_impl_.dst_agent_){nullptr}
    , decltype(_impl_.relationtype_){0}
    , decltype(_impl_.refreshtype_){0}
    , decltype(_impl_.distance_){0}
    , decltype(_impl_.usage_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.updatetimestamp_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.updatetimestamp_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

msg_AgentRelationInfo::~msg_AgentRelationInfo() {
  // @@protoc_insertion_point(destructor:msg.AgentRelationInfo.msg_AgentRelationInfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void msg_AgentRelationInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.updatetimestamp_.Destroy();
  if (this != internal_default_instance()) delete _impl_.src_agent_;
  if (this != internal_default_instance()) delete _impl_.dst_agent_;
}

void msg_AgentRelationInfo::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void msg_AgentRelationInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:msg.AgentRelationInfo.msg_AgentRelationInfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.updatetimestamp_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.src_agent_ != nullptr) {
    delete _impl_.src_agent_;
  }
  _impl_.src_agent_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.dst_agent_ != nullptr) {
    delete _impl_.dst_agent_;
  }
  _impl_.dst_agent_ = nullptr;
  ::memset(&_impl_.relationtype_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.usage_) -
      reinterpret_cast<char*>(&_impl_.relationtype_)) + sizeof(_impl_.usage_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* msg_AgentRelationInfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .msg.AgentRelationInfo.msg_AgentInfo src_agent = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_src_agent(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .msg.AgentRelationInfo.msg_AgentInfo dst_agent = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_dst_agent(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .msg.AgentRelationInfo.E_RELATIONTYPE relationtype = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_relationtype(static_cast<::msg::AgentRelationInfo::E_RELATIONTYPE>(val));
        } else
          goto handle_unusual;
        continue;
      // .msg.AgentRelationInfo.E_REFRESHTYPE refreshtype = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_refreshtype(static_cast<::msg::AgentRelationInfo::E_REFRESHTYPE>(val));
        } else
          goto handle_unusual;
        continue;
      // string updatetimestamp = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_updatetimestamp();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "msg.AgentRelationInfo.msg_AgentRelationInfo.updatetimestamp"));
        } else
          goto handle_unusual;
        continue;
      // double distance = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 49)) {
          _impl_.distance_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // int32 usage = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.usage_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* msg_AgentRelationInfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:msg.AgentRelationInfo.msg_AgentRelationInfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .msg.AgentRelationInfo.msg_AgentInfo src_agent = 1;
  if (this->_internal_has_src_agent()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::src_agent(this),
        _Internal::src_agent(this).GetCachedSize(), target, stream);
  }

  // .msg.AgentRelationInfo.msg_AgentInfo dst_agent = 2;
  if (this->_internal_has_dst_agent()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::dst_agent(this),
        _Internal::dst_agent(this).GetCachedSize(), target, stream);
  }

  // .msg.AgentRelationInfo.E_RELATIONTYPE relationtype = 3;
  if (this->_internal_relationtype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      3, this->_internal_relationtype(), target);
  }

  // .msg.AgentRelationInfo.E_REFRESHTYPE refreshtype = 4;
  if (this->_internal_refreshtype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      4, this->_internal_refreshtype(), target);
  }

  // string updatetimestamp = 5;
  if (!this->_internal_updatetimestamp().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_updatetimestamp().data(), static_cast<int>(this->_internal_updatetimestamp().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "msg.AgentRelationInfo.msg_AgentRelationInfo.updatetimestamp");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_updatetimestamp(), target);
  }

  // double distance = 6;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_distance = this->_internal_distance();
  uint64_t raw_distance;
  memcpy(&raw_distance, &tmp_distance, sizeof(tmp_distance));
  if (raw_distance != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(6, this->_internal_distance(), target);
  }

  // int32 usage = 7;
  if (this->_internal_usage() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(7, this->_internal_usage(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:msg.AgentRelationInfo.msg_AgentRelationInfo)
  return target;
}

size_t msg_AgentRelationInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:msg.AgentRelationInfo.msg_AgentRelationInfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string updatetimestamp = 5;
  if (!this->_internal_updatetimestamp().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_updatetimestamp());
  }

  // .msg.AgentRelationInfo.msg_AgentInfo src_agent = 1;
  if (this->_internal_has_src_agent()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.src_agent_);
  }

  // .msg.AgentRelationInfo.msg_AgentInfo dst_agent = 2;
  if (this->_internal_has_dst_agent()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.dst_agent_);
  }

  // .msg.AgentRelationInfo.E_RELATIONTYPE relationtype = 3;
  if (this->_internal_relationtype() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_relationtype());
  }

  // .msg.AgentRelationInfo.E_REFRESHTYPE refreshtype = 4;
  if (this->_internal_refreshtype() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_refreshtype());
  }

  // double distance = 6;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_distance = this->_internal_distance();
  uint64_t raw_distance;
  memcpy(&raw_distance, &tmp_distance, sizeof(tmp_distance));
  if (raw_distance != 0) {
    total_size += 1 + 8;
  }

  // int32 usage = 7;
  if (this->_internal_usage() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_usage());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData msg_AgentRelationInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    msg_AgentRelationInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*msg_AgentRelationInfo::GetClassData() const { return &_class_data_; }


void msg_AgentRelationInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<msg_AgentRelationInfo*>(&to_msg);
  auto& from = static_cast<const msg_AgentRelationInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:msg.AgentRelationInfo.msg_AgentRelationInfo)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_updatetimestamp().empty()) {
    _this->_internal_set_updatetimestamp(from._internal_updatetimestamp());
  }
  if (from._internal_has_src_agent()) {
    _this->_internal_mutable_src_agent()->::msg::AgentRelationInfo::msg_AgentInfo::MergeFrom(
        from._internal_src_agent());
  }
  if (from._internal_has_dst_agent()) {
    _this->_internal_mutable_dst_agent()->::msg::AgentRelationInfo::msg_AgentInfo::MergeFrom(
        from._internal_dst_agent());
  }
  if (from._internal_relationtype() != 0) {
    _this->_internal_set_relationtype(from._internal_relationtype());
  }
  if (from._internal_refreshtype() != 0) {
    _this->_internal_set_refreshtype(from._internal_refreshtype());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_distance = from._internal_distance();
  uint64_t raw_distance;
  memcpy(&raw_distance, &tmp_distance, sizeof(tmp_distance));
  if (raw_distance != 0) {
    _this->_internal_set_distance(from._internal_distance());
  }
  if (from._internal_usage() != 0) {
    _this->_internal_set_usage(from._internal_usage());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void msg_AgentRelationInfo::CopyFrom(const msg_AgentRelationInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:msg.AgentRelationInfo.msg_AgentRelationInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool msg_AgentRelationInfo::IsInitialized() const {
  return true;
}

void msg_AgentRelationInfo::InternalSwap(msg_AgentRelationInfo* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.updatetimestamp_, lhs_arena,
      &other->_impl_.updatetimestamp_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(msg_AgentRelationInfo, _impl_.usage_)
      + sizeof(msg_AgentRelationInfo::_impl_.usage_)
      - PROTOBUF_FIELD_OFFSET(msg_AgentRelationInfo, _impl_.src_agent_)>(
          reinterpret_cast<char*>(&_impl_.src_agent_),
          reinterpret_cast<char*>(&other->_impl_.src_agent_));
}

::PROTOBUF_NAMESPACE_ID::Metadata msg_AgentRelationInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_AgentRelationInfo_2eproto_getter, &descriptor_table_AgentRelationInfo_2eproto_once,
      file_level_metadata_AgentRelationInfo_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace AgentRelationInfo
}  // namespace msg
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::msg::AgentRelationInfo::msg_AgentInfo*
Arena::CreateMaybeMessage< ::msg::AgentRelationInfo::msg_AgentInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::msg::AgentRelationInfo::msg_AgentInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::msg::AgentRelationInfo::msg_AgentRelationInfo*
Arena::CreateMaybeMessage< ::msg::AgentRelationInfo::msg_AgentRelationInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::msg::AgentRelationInfo::msg_AgentRelationInfo >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
