// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AgentCommSnrInfo.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_AgentCommSnrInfo_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_AgentCommSnrInfo_2eproto

#include "gaeactor_comm_global.h"

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_AgentCommSnrInfo_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_AgentCommSnrInfo_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_AgentCommSnrInfo_2eproto;
namespace msg {
namespace AgentCommSnrInfo {
class msg_AgentCommSnrInfo;
struct msg_AgentCommSnrInfoDefaultTypeInternal;
extern msg_AgentCommSnrInfoDefaultTypeInternal _msg_AgentCommSnrInfo_default_instance_;
}  // namespace AgentCommSnrInfo
}  // namespace msg
PROTOBUF_NAMESPACE_OPEN
template<> ::msg::AgentCommSnrInfo::msg_AgentCommSnrInfo* Arena::CreateMaybeMessage<::msg::AgentCommSnrInfo::msg_AgentCommSnrInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace msg {
namespace AgentCommSnrInfo {

// ===================================================================

class GAEACTOR_COMM_EXPORT msg_AgentCommSnrInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo) */ {
 public:
  inline msg_AgentCommSnrInfo() : msg_AgentCommSnrInfo(nullptr) {}
  ~msg_AgentCommSnrInfo() override;
  explicit PROTOBUF_CONSTEXPR msg_AgentCommSnrInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  msg_AgentCommSnrInfo(const msg_AgentCommSnrInfo& from);
  msg_AgentCommSnrInfo(msg_AgentCommSnrInfo&& from) noexcept
    : msg_AgentCommSnrInfo() {
    *this = ::std::move(from);
  }

  inline msg_AgentCommSnrInfo& operator=(const msg_AgentCommSnrInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline msg_AgentCommSnrInfo& operator=(msg_AgentCommSnrInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const msg_AgentCommSnrInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const msg_AgentCommSnrInfo* internal_default_instance() {
    return reinterpret_cast<const msg_AgentCommSnrInfo*>(
               &_msg_AgentCommSnrInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(msg_AgentCommSnrInfo& a, msg_AgentCommSnrInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(msg_AgentCommSnrInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(msg_AgentCommSnrInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  msg_AgentCommSnrInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<msg_AgentCommSnrInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const msg_AgentCommSnrInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const msg_AgentCommSnrInfo& from) {
    msg_AgentCommSnrInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(msg_AgentCommSnrInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg.AgentCommSnrInfo.msg_AgentCommSnrInfo";
  }
  protected:
  explicit msg_AgentCommSnrInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAClusterCodesFieldNumber = 12,
    kBClusterCodesFieldNumber = 13,
    kSrcAgentFieldNumber = 1,
    kDstAgentFieldNumber = 2,
    kSensingmediaidFieldNumber = 3,
    kTmplmodsigFieldNumber = 4,
    kAIffcodeFieldNumber = 10,
    kBIffcodeFieldNumber = 11,
    kBandwidthFieldNumber = 6,
    kSinrFieldNumber = 7,
    kSnrFieldNumber = 8,
    kFreqHzBFieldNumber = 9,
    kPositiveFieldNumber = 5,
    kPackindexFieldNumber = 14,
  };
  // repeated string a_clusterCodes = 12;
  int a_clustercodes_size() const;
  private:
  int _internal_a_clustercodes_size() const;
  public:
  void clear_a_clustercodes();
  const std::string& a_clustercodes(int index) const;
  std::string* mutable_a_clustercodes(int index);
  void set_a_clustercodes(int index, const std::string& value);
  void set_a_clustercodes(int index, std::string&& value);
  void set_a_clustercodes(int index, const char* value);
  void set_a_clustercodes(int index, const char* value, size_t size);
  std::string* add_a_clustercodes();
  void add_a_clustercodes(const std::string& value);
  void add_a_clustercodes(std::string&& value);
  void add_a_clustercodes(const char* value);
  void add_a_clustercodes(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& a_clustercodes() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_a_clustercodes();
  private:
  const std::string& _internal_a_clustercodes(int index) const;
  std::string* _internal_add_a_clustercodes();
  public:

  // repeated string b_clusterCodes = 13;
  int b_clustercodes_size() const;
  private:
  int _internal_b_clustercodes_size() const;
  public:
  void clear_b_clustercodes();
  const std::string& b_clustercodes(int index) const;
  std::string* mutable_b_clustercodes(int index);
  void set_b_clustercodes(int index, const std::string& value);
  void set_b_clustercodes(int index, std::string&& value);
  void set_b_clustercodes(int index, const char* value);
  void set_b_clustercodes(int index, const char* value, size_t size);
  std::string* add_b_clustercodes();
  void add_b_clustercodes(const std::string& value);
  void add_b_clustercodes(std::string&& value);
  void add_b_clustercodes(const char* value);
  void add_b_clustercodes(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& b_clustercodes() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_b_clustercodes();
  private:
  const std::string& _internal_b_clustercodes(int index) const;
  std::string* _internal_add_b_clustercodes();
  public:

  // string src_agent = 1;
  void clear_src_agent();
  const std::string& src_agent() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_src_agent(ArgT0&& arg0, ArgT... args);
  std::string* mutable_src_agent();
  PROTOBUF_NODISCARD std::string* release_src_agent();
  void set_allocated_src_agent(std::string* src_agent);
  private:
  const std::string& _internal_src_agent() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_src_agent(const std::string& value);
  std::string* _internal_mutable_src_agent();
  public:

  // string dst_agent = 2;
  void clear_dst_agent();
  const std::string& dst_agent() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_dst_agent(ArgT0&& arg0, ArgT... args);
  std::string* mutable_dst_agent();
  PROTOBUF_NODISCARD std::string* release_dst_agent();
  void set_allocated_dst_agent(std::string* dst_agent);
  private:
  const std::string& _internal_dst_agent() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_dst_agent(const std::string& value);
  std::string* _internal_mutable_dst_agent();
  public:

  // string sensingmediaid = 3;
  void clear_sensingmediaid();
  const std::string& sensingmediaid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sensingmediaid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sensingmediaid();
  PROTOBUF_NODISCARD std::string* release_sensingmediaid();
  void set_allocated_sensingmediaid(std::string* sensingmediaid);
  private:
  const std::string& _internal_sensingmediaid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sensingmediaid(const std::string& value);
  std::string* _internal_mutable_sensingmediaid();
  public:

  // string tmplmodsig = 4;
  void clear_tmplmodsig();
  const std::string& tmplmodsig() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_tmplmodsig(ArgT0&& arg0, ArgT... args);
  std::string* mutable_tmplmodsig();
  PROTOBUF_NODISCARD std::string* release_tmplmodsig();
  void set_allocated_tmplmodsig(std::string* tmplmodsig);
  private:
  const std::string& _internal_tmplmodsig() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_tmplmodsig(const std::string& value);
  std::string* _internal_mutable_tmplmodsig();
  public:

  // string a_iffcode = 10;
  void clear_a_iffcode();
  const std::string& a_iffcode() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_a_iffcode(ArgT0&& arg0, ArgT... args);
  std::string* mutable_a_iffcode();
  PROTOBUF_NODISCARD std::string* release_a_iffcode();
  void set_allocated_a_iffcode(std::string* a_iffcode);
  private:
  const std::string& _internal_a_iffcode() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_a_iffcode(const std::string& value);
  std::string* _internal_mutable_a_iffcode();
  public:

  // string b_iffcode = 11;
  void clear_b_iffcode();
  const std::string& b_iffcode() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_b_iffcode(ArgT0&& arg0, ArgT... args);
  std::string* mutable_b_iffcode();
  PROTOBUF_NODISCARD std::string* release_b_iffcode();
  void set_allocated_b_iffcode(std::string* b_iffcode);
  private:
  const std::string& _internal_b_iffcode() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_b_iffcode(const std::string& value);
  std::string* _internal_mutable_b_iffcode();
  public:

  // double bandwidth = 6;
  void clear_bandwidth();
  double bandwidth() const;
  void set_bandwidth(double value);
  private:
  double _internal_bandwidth() const;
  void _internal_set_bandwidth(double value);
  public:

  // double sinr = 7;
  void clear_sinr();
  double sinr() const;
  void set_sinr(double value);
  private:
  double _internal_sinr() const;
  void _internal_set_sinr(double value);
  public:

  // double snr = 8;
  void clear_snr();
  double snr() const;
  void set_snr(double value);
  private:
  double _internal_snr() const;
  void _internal_set_snr(double value);
  public:

  // double freqHzB = 9;
  void clear_freqhzb();
  double freqhzb() const;
  void set_freqhzb(double value);
  private:
  double _internal_freqhzb() const;
  void _internal_set_freqhzb(double value);
  public:

  // bool positive = 5;
  void clear_positive();
  bool positive() const;
  void set_positive(bool value);
  private:
  bool _internal_positive() const;
  void _internal_set_positive(bool value);
  public:

  // uint32 packindex = 14;
  void clear_packindex();
  uint32_t packindex() const;
  void set_packindex(uint32_t value);
  private:
  uint32_t _internal_packindex() const;
  void _internal_set_packindex(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> a_clustercodes_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> b_clustercodes_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr src_agent_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr dst_agent_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sensingmediaid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr tmplmodsig_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr a_iffcode_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr b_iffcode_;
    double bandwidth_;
    double sinr_;
    double snr_;
    double freqhzb_;
    bool positive_;
    uint32_t packindex_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_AgentCommSnrInfo_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// msg_AgentCommSnrInfo

// string src_agent = 1;
inline void msg_AgentCommSnrInfo::clear_src_agent() {
  _impl_.src_agent_.ClearToEmpty();
}
inline const std::string& msg_AgentCommSnrInfo::src_agent() const {
  // @@protoc_insertion_point(field_get:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.src_agent)
  return _internal_src_agent();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void msg_AgentCommSnrInfo::set_src_agent(ArgT0&& arg0, ArgT... args) {
 
 _impl_.src_agent_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.src_agent)
}
inline std::string* msg_AgentCommSnrInfo::mutable_src_agent() {
  std::string* _s = _internal_mutable_src_agent();
  // @@protoc_insertion_point(field_mutable:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.src_agent)
  return _s;
}
inline const std::string& msg_AgentCommSnrInfo::_internal_src_agent() const {
  return _impl_.src_agent_.Get();
}
inline void msg_AgentCommSnrInfo::_internal_set_src_agent(const std::string& value) {
  
  _impl_.src_agent_.Set(value, GetArenaForAllocation());
}
inline std::string* msg_AgentCommSnrInfo::_internal_mutable_src_agent() {
  
  return _impl_.src_agent_.Mutable(GetArenaForAllocation());
}
inline std::string* msg_AgentCommSnrInfo::release_src_agent() {
  // @@protoc_insertion_point(field_release:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.src_agent)
  return _impl_.src_agent_.Release();
}
inline void msg_AgentCommSnrInfo::set_allocated_src_agent(std::string* src_agent) {
  if (src_agent != nullptr) {
    
  } else {
    
  }
  _impl_.src_agent_.SetAllocated(src_agent, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.src_agent_.IsDefault()) {
    _impl_.src_agent_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.src_agent)
}

// string dst_agent = 2;
inline void msg_AgentCommSnrInfo::clear_dst_agent() {
  _impl_.dst_agent_.ClearToEmpty();
}
inline const std::string& msg_AgentCommSnrInfo::dst_agent() const {
  // @@protoc_insertion_point(field_get:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.dst_agent)
  return _internal_dst_agent();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void msg_AgentCommSnrInfo::set_dst_agent(ArgT0&& arg0, ArgT... args) {
 
 _impl_.dst_agent_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.dst_agent)
}
inline std::string* msg_AgentCommSnrInfo::mutable_dst_agent() {
  std::string* _s = _internal_mutable_dst_agent();
  // @@protoc_insertion_point(field_mutable:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.dst_agent)
  return _s;
}
inline const std::string& msg_AgentCommSnrInfo::_internal_dst_agent() const {
  return _impl_.dst_agent_.Get();
}
inline void msg_AgentCommSnrInfo::_internal_set_dst_agent(const std::string& value) {
  
  _impl_.dst_agent_.Set(value, GetArenaForAllocation());
}
inline std::string* msg_AgentCommSnrInfo::_internal_mutable_dst_agent() {
  
  return _impl_.dst_agent_.Mutable(GetArenaForAllocation());
}
inline std::string* msg_AgentCommSnrInfo::release_dst_agent() {
  // @@protoc_insertion_point(field_release:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.dst_agent)
  return _impl_.dst_agent_.Release();
}
inline void msg_AgentCommSnrInfo::set_allocated_dst_agent(std::string* dst_agent) {
  if (dst_agent != nullptr) {
    
  } else {
    
  }
  _impl_.dst_agent_.SetAllocated(dst_agent, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.dst_agent_.IsDefault()) {
    _impl_.dst_agent_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.dst_agent)
}

// string sensingmediaid = 3;
inline void msg_AgentCommSnrInfo::clear_sensingmediaid() {
  _impl_.sensingmediaid_.ClearToEmpty();
}
inline const std::string& msg_AgentCommSnrInfo::sensingmediaid() const {
  // @@protoc_insertion_point(field_get:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.sensingmediaid)
  return _internal_sensingmediaid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void msg_AgentCommSnrInfo::set_sensingmediaid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.sensingmediaid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.sensingmediaid)
}
inline std::string* msg_AgentCommSnrInfo::mutable_sensingmediaid() {
  std::string* _s = _internal_mutable_sensingmediaid();
  // @@protoc_insertion_point(field_mutable:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.sensingmediaid)
  return _s;
}
inline const std::string& msg_AgentCommSnrInfo::_internal_sensingmediaid() const {
  return _impl_.sensingmediaid_.Get();
}
inline void msg_AgentCommSnrInfo::_internal_set_sensingmediaid(const std::string& value) {
  
  _impl_.sensingmediaid_.Set(value, GetArenaForAllocation());
}
inline std::string* msg_AgentCommSnrInfo::_internal_mutable_sensingmediaid() {
  
  return _impl_.sensingmediaid_.Mutable(GetArenaForAllocation());
}
inline std::string* msg_AgentCommSnrInfo::release_sensingmediaid() {
  // @@protoc_insertion_point(field_release:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.sensingmediaid)
  return _impl_.sensingmediaid_.Release();
}
inline void msg_AgentCommSnrInfo::set_allocated_sensingmediaid(std::string* sensingmediaid) {
  if (sensingmediaid != nullptr) {
    
  } else {
    
  }
  _impl_.sensingmediaid_.SetAllocated(sensingmediaid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.sensingmediaid_.IsDefault()) {
    _impl_.sensingmediaid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.sensingmediaid)
}

// string tmplmodsig = 4;
inline void msg_AgentCommSnrInfo::clear_tmplmodsig() {
  _impl_.tmplmodsig_.ClearToEmpty();
}
inline const std::string& msg_AgentCommSnrInfo::tmplmodsig() const {
  // @@protoc_insertion_point(field_get:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.tmplmodsig)
  return _internal_tmplmodsig();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void msg_AgentCommSnrInfo::set_tmplmodsig(ArgT0&& arg0, ArgT... args) {
 
 _impl_.tmplmodsig_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.tmplmodsig)
}
inline std::string* msg_AgentCommSnrInfo::mutable_tmplmodsig() {
  std::string* _s = _internal_mutable_tmplmodsig();
  // @@protoc_insertion_point(field_mutable:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.tmplmodsig)
  return _s;
}
inline const std::string& msg_AgentCommSnrInfo::_internal_tmplmodsig() const {
  return _impl_.tmplmodsig_.Get();
}
inline void msg_AgentCommSnrInfo::_internal_set_tmplmodsig(const std::string& value) {
  
  _impl_.tmplmodsig_.Set(value, GetArenaForAllocation());
}
inline std::string* msg_AgentCommSnrInfo::_internal_mutable_tmplmodsig() {
  
  return _impl_.tmplmodsig_.Mutable(GetArenaForAllocation());
}
inline std::string* msg_AgentCommSnrInfo::release_tmplmodsig() {
  // @@protoc_insertion_point(field_release:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.tmplmodsig)
  return _impl_.tmplmodsig_.Release();
}
inline void msg_AgentCommSnrInfo::set_allocated_tmplmodsig(std::string* tmplmodsig) {
  if (tmplmodsig != nullptr) {
    
  } else {
    
  }
  _impl_.tmplmodsig_.SetAllocated(tmplmodsig, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.tmplmodsig_.IsDefault()) {
    _impl_.tmplmodsig_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.tmplmodsig)
}

// bool positive = 5;
inline void msg_AgentCommSnrInfo::clear_positive() {
  _impl_.positive_ = false;
}
inline bool msg_AgentCommSnrInfo::_internal_positive() const {
  return _impl_.positive_;
}
inline bool msg_AgentCommSnrInfo::positive() const {
  // @@protoc_insertion_point(field_get:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.positive)
  return _internal_positive();
}
inline void msg_AgentCommSnrInfo::_internal_set_positive(bool value) {
  
  _impl_.positive_ = value;
}
inline void msg_AgentCommSnrInfo::set_positive(bool value) {
  _internal_set_positive(value);
  // @@protoc_insertion_point(field_set:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.positive)
}

// double bandwidth = 6;
inline void msg_AgentCommSnrInfo::clear_bandwidth() {
  _impl_.bandwidth_ = 0;
}
inline double msg_AgentCommSnrInfo::_internal_bandwidth() const {
  return _impl_.bandwidth_;
}
inline double msg_AgentCommSnrInfo::bandwidth() const {
  // @@protoc_insertion_point(field_get:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.bandwidth)
  return _internal_bandwidth();
}
inline void msg_AgentCommSnrInfo::_internal_set_bandwidth(double value) {
  
  _impl_.bandwidth_ = value;
}
inline void msg_AgentCommSnrInfo::set_bandwidth(double value) {
  _internal_set_bandwidth(value);
  // @@protoc_insertion_point(field_set:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.bandwidth)
}

// double sinr = 7;
inline void msg_AgentCommSnrInfo::clear_sinr() {
  _impl_.sinr_ = 0;
}
inline double msg_AgentCommSnrInfo::_internal_sinr() const {
  return _impl_.sinr_;
}
inline double msg_AgentCommSnrInfo::sinr() const {
  // @@protoc_insertion_point(field_get:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.sinr)
  return _internal_sinr();
}
inline void msg_AgentCommSnrInfo::_internal_set_sinr(double value) {
  
  _impl_.sinr_ = value;
}
inline void msg_AgentCommSnrInfo::set_sinr(double value) {
  _internal_set_sinr(value);
  // @@protoc_insertion_point(field_set:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.sinr)
}

// double snr = 8;
inline void msg_AgentCommSnrInfo::clear_snr() {
  _impl_.snr_ = 0;
}
inline double msg_AgentCommSnrInfo::_internal_snr() const {
  return _impl_.snr_;
}
inline double msg_AgentCommSnrInfo::snr() const {
  // @@protoc_insertion_point(field_get:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.snr)
  return _internal_snr();
}
inline void msg_AgentCommSnrInfo::_internal_set_snr(double value) {
  
  _impl_.snr_ = value;
}
inline void msg_AgentCommSnrInfo::set_snr(double value) {
  _internal_set_snr(value);
  // @@protoc_insertion_point(field_set:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.snr)
}

// double freqHzB = 9;
inline void msg_AgentCommSnrInfo::clear_freqhzb() {
  _impl_.freqhzb_ = 0;
}
inline double msg_AgentCommSnrInfo::_internal_freqhzb() const {
  return _impl_.freqhzb_;
}
inline double msg_AgentCommSnrInfo::freqhzb() const {
  // @@protoc_insertion_point(field_get:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.freqHzB)
  return _internal_freqhzb();
}
inline void msg_AgentCommSnrInfo::_internal_set_freqhzb(double value) {
  
  _impl_.freqhzb_ = value;
}
inline void msg_AgentCommSnrInfo::set_freqhzb(double value) {
  _internal_set_freqhzb(value);
  // @@protoc_insertion_point(field_set:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.freqHzB)
}

// string a_iffcode = 10;
inline void msg_AgentCommSnrInfo::clear_a_iffcode() {
  _impl_.a_iffcode_.ClearToEmpty();
}
inline const std::string& msg_AgentCommSnrInfo::a_iffcode() const {
  // @@protoc_insertion_point(field_get:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.a_iffcode)
  return _internal_a_iffcode();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void msg_AgentCommSnrInfo::set_a_iffcode(ArgT0&& arg0, ArgT... args) {
 
 _impl_.a_iffcode_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.a_iffcode)
}
inline std::string* msg_AgentCommSnrInfo::mutable_a_iffcode() {
  std::string* _s = _internal_mutable_a_iffcode();
  // @@protoc_insertion_point(field_mutable:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.a_iffcode)
  return _s;
}
inline const std::string& msg_AgentCommSnrInfo::_internal_a_iffcode() const {
  return _impl_.a_iffcode_.Get();
}
inline void msg_AgentCommSnrInfo::_internal_set_a_iffcode(const std::string& value) {
  
  _impl_.a_iffcode_.Set(value, GetArenaForAllocation());
}
inline std::string* msg_AgentCommSnrInfo::_internal_mutable_a_iffcode() {
  
  return _impl_.a_iffcode_.Mutable(GetArenaForAllocation());
}
inline std::string* msg_AgentCommSnrInfo::release_a_iffcode() {
  // @@protoc_insertion_point(field_release:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.a_iffcode)
  return _impl_.a_iffcode_.Release();
}
inline void msg_AgentCommSnrInfo::set_allocated_a_iffcode(std::string* a_iffcode) {
  if (a_iffcode != nullptr) {
    
  } else {
    
  }
  _impl_.a_iffcode_.SetAllocated(a_iffcode, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.a_iffcode_.IsDefault()) {
    _impl_.a_iffcode_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.a_iffcode)
}

// string b_iffcode = 11;
inline void msg_AgentCommSnrInfo::clear_b_iffcode() {
  _impl_.b_iffcode_.ClearToEmpty();
}
inline const std::string& msg_AgentCommSnrInfo::b_iffcode() const {
  // @@protoc_insertion_point(field_get:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.b_iffcode)
  return _internal_b_iffcode();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void msg_AgentCommSnrInfo::set_b_iffcode(ArgT0&& arg0, ArgT... args) {
 
 _impl_.b_iffcode_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.b_iffcode)
}
inline std::string* msg_AgentCommSnrInfo::mutable_b_iffcode() {
  std::string* _s = _internal_mutable_b_iffcode();
  // @@protoc_insertion_point(field_mutable:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.b_iffcode)
  return _s;
}
inline const std::string& msg_AgentCommSnrInfo::_internal_b_iffcode() const {
  return _impl_.b_iffcode_.Get();
}
inline void msg_AgentCommSnrInfo::_internal_set_b_iffcode(const std::string& value) {
  
  _impl_.b_iffcode_.Set(value, GetArenaForAllocation());
}
inline std::string* msg_AgentCommSnrInfo::_internal_mutable_b_iffcode() {
  
  return _impl_.b_iffcode_.Mutable(GetArenaForAllocation());
}
inline std::string* msg_AgentCommSnrInfo::release_b_iffcode() {
  // @@protoc_insertion_point(field_release:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.b_iffcode)
  return _impl_.b_iffcode_.Release();
}
inline void msg_AgentCommSnrInfo::set_allocated_b_iffcode(std::string* b_iffcode) {
  if (b_iffcode != nullptr) {
    
  } else {
    
  }
  _impl_.b_iffcode_.SetAllocated(b_iffcode, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.b_iffcode_.IsDefault()) {
    _impl_.b_iffcode_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.b_iffcode)
}

// repeated string a_clusterCodes = 12;
inline int msg_AgentCommSnrInfo::_internal_a_clustercodes_size() const {
  return _impl_.a_clustercodes_.size();
}
inline int msg_AgentCommSnrInfo::a_clustercodes_size() const {
  return _internal_a_clustercodes_size();
}
inline void msg_AgentCommSnrInfo::clear_a_clustercodes() {
  _impl_.a_clustercodes_.Clear();
}
inline std::string* msg_AgentCommSnrInfo::add_a_clustercodes() {
  std::string* _s = _internal_add_a_clustercodes();
  // @@protoc_insertion_point(field_add_mutable:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.a_clusterCodes)
  return _s;
}
inline const std::string& msg_AgentCommSnrInfo::_internal_a_clustercodes(int index) const {
  return _impl_.a_clustercodes_.Get(index);
}
inline const std::string& msg_AgentCommSnrInfo::a_clustercodes(int index) const {
  // @@protoc_insertion_point(field_get:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.a_clusterCodes)
  return _internal_a_clustercodes(index);
}
inline std::string* msg_AgentCommSnrInfo::mutable_a_clustercodes(int index) {
  // @@protoc_insertion_point(field_mutable:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.a_clusterCodes)
  return _impl_.a_clustercodes_.Mutable(index);
}
inline void msg_AgentCommSnrInfo::set_a_clustercodes(int index, const std::string& value) {
  _impl_.a_clustercodes_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.a_clusterCodes)
}
inline void msg_AgentCommSnrInfo::set_a_clustercodes(int index, std::string&& value) {
  _impl_.a_clustercodes_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.a_clusterCodes)
}
inline void msg_AgentCommSnrInfo::set_a_clustercodes(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.a_clustercodes_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.a_clusterCodes)
}
inline void msg_AgentCommSnrInfo::set_a_clustercodes(int index, const char* value, size_t size) {
  _impl_.a_clustercodes_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.a_clusterCodes)
}
inline std::string* msg_AgentCommSnrInfo::_internal_add_a_clustercodes() {
  return _impl_.a_clustercodes_.Add();
}
inline void msg_AgentCommSnrInfo::add_a_clustercodes(const std::string& value) {
  _impl_.a_clustercodes_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.a_clusterCodes)
}
inline void msg_AgentCommSnrInfo::add_a_clustercodes(std::string&& value) {
  _impl_.a_clustercodes_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.a_clusterCodes)
}
inline void msg_AgentCommSnrInfo::add_a_clustercodes(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.a_clustercodes_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.a_clusterCodes)
}
inline void msg_AgentCommSnrInfo::add_a_clustercodes(const char* value, size_t size) {
  _impl_.a_clustercodes_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.a_clusterCodes)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
msg_AgentCommSnrInfo::a_clustercodes() const {
  // @@protoc_insertion_point(field_list:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.a_clusterCodes)
  return _impl_.a_clustercodes_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
msg_AgentCommSnrInfo::mutable_a_clustercodes() {
  // @@protoc_insertion_point(field_mutable_list:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.a_clusterCodes)
  return &_impl_.a_clustercodes_;
}

// repeated string b_clusterCodes = 13;
inline int msg_AgentCommSnrInfo::_internal_b_clustercodes_size() const {
  return _impl_.b_clustercodes_.size();
}
inline int msg_AgentCommSnrInfo::b_clustercodes_size() const {
  return _internal_b_clustercodes_size();
}
inline void msg_AgentCommSnrInfo::clear_b_clustercodes() {
  _impl_.b_clustercodes_.Clear();
}
inline std::string* msg_AgentCommSnrInfo::add_b_clustercodes() {
  std::string* _s = _internal_add_b_clustercodes();
  // @@protoc_insertion_point(field_add_mutable:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.b_clusterCodes)
  return _s;
}
inline const std::string& msg_AgentCommSnrInfo::_internal_b_clustercodes(int index) const {
  return _impl_.b_clustercodes_.Get(index);
}
inline const std::string& msg_AgentCommSnrInfo::b_clustercodes(int index) const {
  // @@protoc_insertion_point(field_get:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.b_clusterCodes)
  return _internal_b_clustercodes(index);
}
inline std::string* msg_AgentCommSnrInfo::mutable_b_clustercodes(int index) {
  // @@protoc_insertion_point(field_mutable:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.b_clusterCodes)
  return _impl_.b_clustercodes_.Mutable(index);
}
inline void msg_AgentCommSnrInfo::set_b_clustercodes(int index, const std::string& value) {
  _impl_.b_clustercodes_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.b_clusterCodes)
}
inline void msg_AgentCommSnrInfo::set_b_clustercodes(int index, std::string&& value) {
  _impl_.b_clustercodes_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.b_clusterCodes)
}
inline void msg_AgentCommSnrInfo::set_b_clustercodes(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.b_clustercodes_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.b_clusterCodes)
}
inline void msg_AgentCommSnrInfo::set_b_clustercodes(int index, const char* value, size_t size) {
  _impl_.b_clustercodes_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.b_clusterCodes)
}
inline std::string* msg_AgentCommSnrInfo::_internal_add_b_clustercodes() {
  return _impl_.b_clustercodes_.Add();
}
inline void msg_AgentCommSnrInfo::add_b_clustercodes(const std::string& value) {
  _impl_.b_clustercodes_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.b_clusterCodes)
}
inline void msg_AgentCommSnrInfo::add_b_clustercodes(std::string&& value) {
  _impl_.b_clustercodes_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.b_clusterCodes)
}
inline void msg_AgentCommSnrInfo::add_b_clustercodes(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.b_clustercodes_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.b_clusterCodes)
}
inline void msg_AgentCommSnrInfo::add_b_clustercodes(const char* value, size_t size) {
  _impl_.b_clustercodes_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.b_clusterCodes)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
msg_AgentCommSnrInfo::b_clustercodes() const {
  // @@protoc_insertion_point(field_list:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.b_clusterCodes)
  return _impl_.b_clustercodes_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
msg_AgentCommSnrInfo::mutable_b_clustercodes() {
  // @@protoc_insertion_point(field_mutable_list:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.b_clusterCodes)
  return &_impl_.b_clustercodes_;
}

// uint32 packindex = 14;
inline void msg_AgentCommSnrInfo::clear_packindex() {
  _impl_.packindex_ = 0u;
}
inline uint32_t msg_AgentCommSnrInfo::_internal_packindex() const {
  return _impl_.packindex_;
}
inline uint32_t msg_AgentCommSnrInfo::packindex() const {
  // @@protoc_insertion_point(field_get:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.packindex)
  return _internal_packindex();
}
inline void msg_AgentCommSnrInfo::_internal_set_packindex(uint32_t value) {
  
  _impl_.packindex_ = value;
}
inline void msg_AgentCommSnrInfo::set_packindex(uint32_t value) {
  _internal_set_packindex(value);
  // @@protoc_insertion_point(field_set:msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.packindex)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace AgentCommSnrInfo
}  // namespace msg

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_AgentCommSnrInfo_2eproto
