// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AgentRelationInfo.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_AgentRelationInfo_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_AgentRelationInfo_2eproto

#include "gaeactor_comm_global.h"

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_AgentRelationInfo_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_AgentRelationInfo_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_AgentRelationInfo_2eproto;
namespace msg {
namespace AgentRelationInfo {
class msg_AgentInfo;
struct msg_AgentInfoDefaultTypeInternal;
extern msg_AgentInfoDefaultTypeInternal _msg_AgentInfo_default_instance_;
class msg_AgentRelationInfo;
struct msg_AgentRelationInfoDefaultTypeInternal;
extern msg_AgentRelationInfoDefaultTypeInternal _msg_AgentRelationInfo_default_instance_;
}  // namespace AgentRelationInfo
}  // namespace msg
PROTOBUF_NAMESPACE_OPEN
template<> ::msg::AgentRelationInfo::msg_AgentInfo* Arena::CreateMaybeMessage<::msg::AgentRelationInfo::msg_AgentInfo>(Arena*);
template<> ::msg::AgentRelationInfo::msg_AgentRelationInfo* Arena::CreateMaybeMessage<::msg::AgentRelationInfo::msg_AgentRelationInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace msg {
namespace AgentRelationInfo {

enum E_RELATIONTYPE : int {
  E_RELATIONTYPE_UNKNOWN = 0,
  E_RELATIONTYPE_COMM = 1,
  E_RELATIONTYPE_TRACK = 2,
  E_RELATIONTYPE_DETECT = 3,
  E_RELATIONTYPE_IFF_REQUEST = 4,
  E_RELATIONTYPE_IFF_RESPONSE = 5,
  E_RELATIONTYPE_IFF_THREAT = 6,
  E_RELATIONTYPE_IFF_NOTHREAT = 7,
  E_RELATIONTYPE_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  E_RELATIONTYPE_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool E_RELATIONTYPE_IsValid(int value);
constexpr E_RELATIONTYPE E_RELATIONTYPE_MIN = E_RELATIONTYPE_UNKNOWN;
constexpr E_RELATIONTYPE E_RELATIONTYPE_MAX = E_RELATIONTYPE_IFF_NOTHREAT;
constexpr int E_RELATIONTYPE_ARRAYSIZE = E_RELATIONTYPE_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* E_RELATIONTYPE_descriptor();
template<typename T>
inline const std::string& E_RELATIONTYPE_Name(T enum_t_value) {
  static_assert(::std::is_same<T, E_RELATIONTYPE>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function E_RELATIONTYPE_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    E_RELATIONTYPE_descriptor(), enum_t_value);
}
inline bool E_RELATIONTYPE_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, E_RELATIONTYPE* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<E_RELATIONTYPE>(
    E_RELATIONTYPE_descriptor(), name, value);
}
enum E_REFRESHTYPE : int {
  E_REFRESHTYPE_UNKNOWN = 0,
  E_REFRESHTYPE_ADD = 1,
  E_REFRESHTYPE_REMOVE = 2,
  E_REFRESHTYPE_UPDATE = 3,
  E_REFRESHTYPE_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  E_REFRESHTYPE_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool E_REFRESHTYPE_IsValid(int value);
constexpr E_REFRESHTYPE E_REFRESHTYPE_MIN = E_REFRESHTYPE_UNKNOWN;
constexpr E_REFRESHTYPE E_REFRESHTYPE_MAX = E_REFRESHTYPE_UPDATE;
constexpr int E_REFRESHTYPE_ARRAYSIZE = E_REFRESHTYPE_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* E_REFRESHTYPE_descriptor();
template<typename T>
inline const std::string& E_REFRESHTYPE_Name(T enum_t_value) {
  static_assert(::std::is_same<T, E_REFRESHTYPE>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function E_REFRESHTYPE_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    E_REFRESHTYPE_descriptor(), enum_t_value);
}
inline bool E_REFRESHTYPE_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, E_REFRESHTYPE* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<E_REFRESHTYPE>(
    E_REFRESHTYPE_descriptor(), name, value);
}
// ===================================================================

class GAEACTOR_COMM_EXPORT msg_AgentInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg.AgentRelationInfo.msg_AgentInfo) */ {
 public:
  inline msg_AgentInfo() : msg_AgentInfo(nullptr) {}
  ~msg_AgentInfo() override;
  explicit PROTOBUF_CONSTEXPR msg_AgentInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  msg_AgentInfo(const msg_AgentInfo& from);
  msg_AgentInfo(msg_AgentInfo&& from) noexcept
    : msg_AgentInfo() {
    *this = ::std::move(from);
  }

  inline msg_AgentInfo& operator=(const msg_AgentInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline msg_AgentInfo& operator=(msg_AgentInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const msg_AgentInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const msg_AgentInfo* internal_default_instance() {
    return reinterpret_cast<const msg_AgentInfo*>(
               &_msg_AgentInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(msg_AgentInfo& a, msg_AgentInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(msg_AgentInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(msg_AgentInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  msg_AgentInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<msg_AgentInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const msg_AgentInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const msg_AgentInfo& from) {
    msg_AgentInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(msg_AgentInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg.AgentRelationInfo.msg_AgentInfo";
  }
  protected:
  explicit msg_AgentInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAgentidFieldNumber = 1,
    kSensingmediaidFieldNumber = 2,
    kTimestampFieldNumber = 3,
    kSimTimestampFieldNumber = 4,
    kIffcodeFieldNumber = 13,
    kLonFieldNumber = 5,
    kLatFieldNumber = 6,
    kAmslFieldNumber = 7,
    kRefFieldNumber = 8,
    kRollFieldNumber = 9,
    kPitchFieldNumber = 10,
    kYawFieldNumber = 11,
    kSpeedFieldNumber = 12,
  };
  // string agentid = 1;
  void clear_agentid();
  const std::string& agentid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_agentid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_agentid();
  PROTOBUF_NODISCARD std::string* release_agentid();
  void set_allocated_agentid(std::string* agentid);
  private:
  const std::string& _internal_agentid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_agentid(const std::string& value);
  std::string* _internal_mutable_agentid();
  public:

  // string sensingmediaid = 2;
  void clear_sensingmediaid();
  const std::string& sensingmediaid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sensingmediaid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sensingmediaid();
  PROTOBUF_NODISCARD std::string* release_sensingmediaid();
  void set_allocated_sensingmediaid(std::string* sensingmediaid);
  private:
  const std::string& _internal_sensingmediaid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sensingmediaid(const std::string& value);
  std::string* _internal_mutable_sensingmediaid();
  public:

  // string timestamp = 3;
  void clear_timestamp();
  const std::string& timestamp() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_timestamp(ArgT0&& arg0, ArgT... args);
  std::string* mutable_timestamp();
  PROTOBUF_NODISCARD std::string* release_timestamp();
  void set_allocated_timestamp(std::string* timestamp);
  private:
  const std::string& _internal_timestamp() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_timestamp(const std::string& value);
  std::string* _internal_mutable_timestamp();
  public:

  // string sim_timestamp = 4;
  void clear_sim_timestamp();
  const std::string& sim_timestamp() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sim_timestamp(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sim_timestamp();
  PROTOBUF_NODISCARD std::string* release_sim_timestamp();
  void set_allocated_sim_timestamp(std::string* sim_timestamp);
  private:
  const std::string& _internal_sim_timestamp() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sim_timestamp(const std::string& value);
  std::string* _internal_mutable_sim_timestamp();
  public:

  // string iffcode = 13;
  void clear_iffcode();
  const std::string& iffcode() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_iffcode(ArgT0&& arg0, ArgT... args);
  std::string* mutable_iffcode();
  PROTOBUF_NODISCARD std::string* release_iffcode();
  void set_allocated_iffcode(std::string* iffcode);
  private:
  const std::string& _internal_iffcode() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_iffcode(const std::string& value);
  std::string* _internal_mutable_iffcode();
  public:

  // double lon = 5;
  void clear_lon();
  double lon() const;
  void set_lon(double value);
  private:
  double _internal_lon() const;
  void _internal_set_lon(double value);
  public:

  // double lat = 6;
  void clear_lat();
  double lat() const;
  void set_lat(double value);
  private:
  double _internal_lat() const;
  void _internal_set_lat(double value);
  public:

  // double amsl = 7;
  void clear_amsl();
  double amsl() const;
  void set_amsl(double value);
  private:
  double _internal_amsl() const;
  void _internal_set_amsl(double value);
  public:

  // int32 ref = 8;
  void clear_ref();
  int32_t ref() const;
  void set_ref(int32_t value);
  private:
  int32_t _internal_ref() const;
  void _internal_set_ref(int32_t value);
  public:

  // float roll = 9;
  void clear_roll();
  float roll() const;
  void set_roll(float value);
  private:
  float _internal_roll() const;
  void _internal_set_roll(float value);
  public:

  // float pitch = 10;
  void clear_pitch();
  float pitch() const;
  void set_pitch(float value);
  private:
  float _internal_pitch() const;
  void _internal_set_pitch(float value);
  public:

  // float yaw = 11;
  void clear_yaw();
  float yaw() const;
  void set_yaw(float value);
  private:
  float _internal_yaw() const;
  void _internal_set_yaw(float value);
  public:

  // float speed = 12;
  void clear_speed();
  float speed() const;
  void set_speed(float value);
  private:
  float _internal_speed() const;
  void _internal_set_speed(float value);
  public:

  // @@protoc_insertion_point(class_scope:msg.AgentRelationInfo.msg_AgentInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr agentid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sensingmediaid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr timestamp_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sim_timestamp_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr iffcode_;
    double lon_;
    double lat_;
    double amsl_;
    int32_t ref_;
    float roll_;
    float pitch_;
    float yaw_;
    float speed_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_AgentRelationInfo_2eproto;
};
// -------------------------------------------------------------------

class GAEACTOR_COMM_EXPORT msg_AgentRelationInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg.AgentRelationInfo.msg_AgentRelationInfo) */ {
 public:
  inline msg_AgentRelationInfo() : msg_AgentRelationInfo(nullptr) {}
  ~msg_AgentRelationInfo() override;
  explicit PROTOBUF_CONSTEXPR msg_AgentRelationInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  msg_AgentRelationInfo(const msg_AgentRelationInfo& from);
  msg_AgentRelationInfo(msg_AgentRelationInfo&& from) noexcept
    : msg_AgentRelationInfo() {
    *this = ::std::move(from);
  }

  inline msg_AgentRelationInfo& operator=(const msg_AgentRelationInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline msg_AgentRelationInfo& operator=(msg_AgentRelationInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const msg_AgentRelationInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const msg_AgentRelationInfo* internal_default_instance() {
    return reinterpret_cast<const msg_AgentRelationInfo*>(
               &_msg_AgentRelationInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(msg_AgentRelationInfo& a, msg_AgentRelationInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(msg_AgentRelationInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(msg_AgentRelationInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  msg_AgentRelationInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<msg_AgentRelationInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const msg_AgentRelationInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const msg_AgentRelationInfo& from) {
    msg_AgentRelationInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(msg_AgentRelationInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg.AgentRelationInfo.msg_AgentRelationInfo";
  }
  protected:
  explicit msg_AgentRelationInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUpdatetimestampFieldNumber = 5,
    kSrcAgentFieldNumber = 1,
    kDstAgentFieldNumber = 2,
    kRelationtypeFieldNumber = 3,
    kRefreshtypeFieldNumber = 4,
    kDistanceFieldNumber = 6,
    kUsageFieldNumber = 7,
  };
  // string updatetimestamp = 5;
  void clear_updatetimestamp();
  const std::string& updatetimestamp() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_updatetimestamp(ArgT0&& arg0, ArgT... args);
  std::string* mutable_updatetimestamp();
  PROTOBUF_NODISCARD std::string* release_updatetimestamp();
  void set_allocated_updatetimestamp(std::string* updatetimestamp);
  private:
  const std::string& _internal_updatetimestamp() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_updatetimestamp(const std::string& value);
  std::string* _internal_mutable_updatetimestamp();
  public:

  // .msg.AgentRelationInfo.msg_AgentInfo src_agent = 1;
  bool has_src_agent() const;
  private:
  bool _internal_has_src_agent() const;
  public:
  void clear_src_agent();
  const ::msg::AgentRelationInfo::msg_AgentInfo& src_agent() const;
  PROTOBUF_NODISCARD ::msg::AgentRelationInfo::msg_AgentInfo* release_src_agent();
  ::msg::AgentRelationInfo::msg_AgentInfo* mutable_src_agent();
  void set_allocated_src_agent(::msg::AgentRelationInfo::msg_AgentInfo* src_agent);
  private:
  const ::msg::AgentRelationInfo::msg_AgentInfo& _internal_src_agent() const;
  ::msg::AgentRelationInfo::msg_AgentInfo* _internal_mutable_src_agent();
  public:
  void unsafe_arena_set_allocated_src_agent(
      ::msg::AgentRelationInfo::msg_AgentInfo* src_agent);
  ::msg::AgentRelationInfo::msg_AgentInfo* unsafe_arena_release_src_agent();

  // .msg.AgentRelationInfo.msg_AgentInfo dst_agent = 2;
  bool has_dst_agent() const;
  private:
  bool _internal_has_dst_agent() const;
  public:
  void clear_dst_agent();
  const ::msg::AgentRelationInfo::msg_AgentInfo& dst_agent() const;
  PROTOBUF_NODISCARD ::msg::AgentRelationInfo::msg_AgentInfo* release_dst_agent();
  ::msg::AgentRelationInfo::msg_AgentInfo* mutable_dst_agent();
  void set_allocated_dst_agent(::msg::AgentRelationInfo::msg_AgentInfo* dst_agent);
  private:
  const ::msg::AgentRelationInfo::msg_AgentInfo& _internal_dst_agent() const;
  ::msg::AgentRelationInfo::msg_AgentInfo* _internal_mutable_dst_agent();
  public:
  void unsafe_arena_set_allocated_dst_agent(
      ::msg::AgentRelationInfo::msg_AgentInfo* dst_agent);
  ::msg::AgentRelationInfo::msg_AgentInfo* unsafe_arena_release_dst_agent();

  // .msg.AgentRelationInfo.E_RELATIONTYPE relationtype = 3;
  void clear_relationtype();
  ::msg::AgentRelationInfo::E_RELATIONTYPE relationtype() const;
  void set_relationtype(::msg::AgentRelationInfo::E_RELATIONTYPE value);
  private:
  ::msg::AgentRelationInfo::E_RELATIONTYPE _internal_relationtype() const;
  void _internal_set_relationtype(::msg::AgentRelationInfo::E_RELATIONTYPE value);
  public:

  // .msg.AgentRelationInfo.E_REFRESHTYPE refreshtype = 4;
  void clear_refreshtype();
  ::msg::AgentRelationInfo::E_REFRESHTYPE refreshtype() const;
  void set_refreshtype(::msg::AgentRelationInfo::E_REFRESHTYPE value);
  private:
  ::msg::AgentRelationInfo::E_REFRESHTYPE _internal_refreshtype() const;
  void _internal_set_refreshtype(::msg::AgentRelationInfo::E_REFRESHTYPE value);
  public:

  // double distance = 6;
  void clear_distance();
  double distance() const;
  void set_distance(double value);
  private:
  double _internal_distance() const;
  void _internal_set_distance(double value);
  public:

  // int32 usage = 7;
  void clear_usage();
  int32_t usage() const;
  void set_usage(int32_t value);
  private:
  int32_t _internal_usage() const;
  void _internal_set_usage(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:msg.AgentRelationInfo.msg_AgentRelationInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr updatetimestamp_;
    ::msg::AgentRelationInfo::msg_AgentInfo* src_agent_;
    ::msg::AgentRelationInfo::msg_AgentInfo* dst_agent_;
    int relationtype_;
    int refreshtype_;
    double distance_;
    int32_t usage_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_AgentRelationInfo_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// msg_AgentInfo

// string agentid = 1;
inline void msg_AgentInfo::clear_agentid() {
  _impl_.agentid_.ClearToEmpty();
}
inline const std::string& msg_AgentInfo::agentid() const {
  // @@protoc_insertion_point(field_get:msg.AgentRelationInfo.msg_AgentInfo.agentid)
  return _internal_agentid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void msg_AgentInfo::set_agentid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.agentid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg.AgentRelationInfo.msg_AgentInfo.agentid)
}
inline std::string* msg_AgentInfo::mutable_agentid() {
  std::string* _s = _internal_mutable_agentid();
  // @@protoc_insertion_point(field_mutable:msg.AgentRelationInfo.msg_AgentInfo.agentid)
  return _s;
}
inline const std::string& msg_AgentInfo::_internal_agentid() const {
  return _impl_.agentid_.Get();
}
inline void msg_AgentInfo::_internal_set_agentid(const std::string& value) {
  
  _impl_.agentid_.Set(value, GetArenaForAllocation());
}
inline std::string* msg_AgentInfo::_internal_mutable_agentid() {
  
  return _impl_.agentid_.Mutable(GetArenaForAllocation());
}
inline std::string* msg_AgentInfo::release_agentid() {
  // @@protoc_insertion_point(field_release:msg.AgentRelationInfo.msg_AgentInfo.agentid)
  return _impl_.agentid_.Release();
}
inline void msg_AgentInfo::set_allocated_agentid(std::string* agentid) {
  if (agentid != nullptr) {
    
  } else {
    
  }
  _impl_.agentid_.SetAllocated(agentid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.agentid_.IsDefault()) {
    _impl_.agentid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg.AgentRelationInfo.msg_AgentInfo.agentid)
}

// string sensingmediaid = 2;
inline void msg_AgentInfo::clear_sensingmediaid() {
  _impl_.sensingmediaid_.ClearToEmpty();
}
inline const std::string& msg_AgentInfo::sensingmediaid() const {
  // @@protoc_insertion_point(field_get:msg.AgentRelationInfo.msg_AgentInfo.sensingmediaid)
  return _internal_sensingmediaid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void msg_AgentInfo::set_sensingmediaid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.sensingmediaid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg.AgentRelationInfo.msg_AgentInfo.sensingmediaid)
}
inline std::string* msg_AgentInfo::mutable_sensingmediaid() {
  std::string* _s = _internal_mutable_sensingmediaid();
  // @@protoc_insertion_point(field_mutable:msg.AgentRelationInfo.msg_AgentInfo.sensingmediaid)
  return _s;
}
inline const std::string& msg_AgentInfo::_internal_sensingmediaid() const {
  return _impl_.sensingmediaid_.Get();
}
inline void msg_AgentInfo::_internal_set_sensingmediaid(const std::string& value) {
  
  _impl_.sensingmediaid_.Set(value, GetArenaForAllocation());
}
inline std::string* msg_AgentInfo::_internal_mutable_sensingmediaid() {
  
  return _impl_.sensingmediaid_.Mutable(GetArenaForAllocation());
}
inline std::string* msg_AgentInfo::release_sensingmediaid() {
  // @@protoc_insertion_point(field_release:msg.AgentRelationInfo.msg_AgentInfo.sensingmediaid)
  return _impl_.sensingmediaid_.Release();
}
inline void msg_AgentInfo::set_allocated_sensingmediaid(std::string* sensingmediaid) {
  if (sensingmediaid != nullptr) {
    
  } else {
    
  }
  _impl_.sensingmediaid_.SetAllocated(sensingmediaid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.sensingmediaid_.IsDefault()) {
    _impl_.sensingmediaid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg.AgentRelationInfo.msg_AgentInfo.sensingmediaid)
}

// string timestamp = 3;
inline void msg_AgentInfo::clear_timestamp() {
  _impl_.timestamp_.ClearToEmpty();
}
inline const std::string& msg_AgentInfo::timestamp() const {
  // @@protoc_insertion_point(field_get:msg.AgentRelationInfo.msg_AgentInfo.timestamp)
  return _internal_timestamp();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void msg_AgentInfo::set_timestamp(ArgT0&& arg0, ArgT... args) {
 
 _impl_.timestamp_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg.AgentRelationInfo.msg_AgentInfo.timestamp)
}
inline std::string* msg_AgentInfo::mutable_timestamp() {
  std::string* _s = _internal_mutable_timestamp();
  // @@protoc_insertion_point(field_mutable:msg.AgentRelationInfo.msg_AgentInfo.timestamp)
  return _s;
}
inline const std::string& msg_AgentInfo::_internal_timestamp() const {
  return _impl_.timestamp_.Get();
}
inline void msg_AgentInfo::_internal_set_timestamp(const std::string& value) {
  
  _impl_.timestamp_.Set(value, GetArenaForAllocation());
}
inline std::string* msg_AgentInfo::_internal_mutable_timestamp() {
  
  return _impl_.timestamp_.Mutable(GetArenaForAllocation());
}
inline std::string* msg_AgentInfo::release_timestamp() {
  // @@protoc_insertion_point(field_release:msg.AgentRelationInfo.msg_AgentInfo.timestamp)
  return _impl_.timestamp_.Release();
}
inline void msg_AgentInfo::set_allocated_timestamp(std::string* timestamp) {
  if (timestamp != nullptr) {
    
  } else {
    
  }
  _impl_.timestamp_.SetAllocated(timestamp, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.timestamp_.IsDefault()) {
    _impl_.timestamp_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg.AgentRelationInfo.msg_AgentInfo.timestamp)
}

// string sim_timestamp = 4;
inline void msg_AgentInfo::clear_sim_timestamp() {
  _impl_.sim_timestamp_.ClearToEmpty();
}
inline const std::string& msg_AgentInfo::sim_timestamp() const {
  // @@protoc_insertion_point(field_get:msg.AgentRelationInfo.msg_AgentInfo.sim_timestamp)
  return _internal_sim_timestamp();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void msg_AgentInfo::set_sim_timestamp(ArgT0&& arg0, ArgT... args) {
 
 _impl_.sim_timestamp_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg.AgentRelationInfo.msg_AgentInfo.sim_timestamp)
}
inline std::string* msg_AgentInfo::mutable_sim_timestamp() {
  std::string* _s = _internal_mutable_sim_timestamp();
  // @@protoc_insertion_point(field_mutable:msg.AgentRelationInfo.msg_AgentInfo.sim_timestamp)
  return _s;
}
inline const std::string& msg_AgentInfo::_internal_sim_timestamp() const {
  return _impl_.sim_timestamp_.Get();
}
inline void msg_AgentInfo::_internal_set_sim_timestamp(const std::string& value) {
  
  _impl_.sim_timestamp_.Set(value, GetArenaForAllocation());
}
inline std::string* msg_AgentInfo::_internal_mutable_sim_timestamp() {
  
  return _impl_.sim_timestamp_.Mutable(GetArenaForAllocation());
}
inline std::string* msg_AgentInfo::release_sim_timestamp() {
  // @@protoc_insertion_point(field_release:msg.AgentRelationInfo.msg_AgentInfo.sim_timestamp)
  return _impl_.sim_timestamp_.Release();
}
inline void msg_AgentInfo::set_allocated_sim_timestamp(std::string* sim_timestamp) {
  if (sim_timestamp != nullptr) {
    
  } else {
    
  }
  _impl_.sim_timestamp_.SetAllocated(sim_timestamp, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.sim_timestamp_.IsDefault()) {
    _impl_.sim_timestamp_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg.AgentRelationInfo.msg_AgentInfo.sim_timestamp)
}

// double lon = 5;
inline void msg_AgentInfo::clear_lon() {
  _impl_.lon_ = 0;
}
inline double msg_AgentInfo::_internal_lon() const {
  return _impl_.lon_;
}
inline double msg_AgentInfo::lon() const {
  // @@protoc_insertion_point(field_get:msg.AgentRelationInfo.msg_AgentInfo.lon)
  return _internal_lon();
}
inline void msg_AgentInfo::_internal_set_lon(double value) {
  
  _impl_.lon_ = value;
}
inline void msg_AgentInfo::set_lon(double value) {
  _internal_set_lon(value);
  // @@protoc_insertion_point(field_set:msg.AgentRelationInfo.msg_AgentInfo.lon)
}

// double lat = 6;
inline void msg_AgentInfo::clear_lat() {
  _impl_.lat_ = 0;
}
inline double msg_AgentInfo::_internal_lat() const {
  return _impl_.lat_;
}
inline double msg_AgentInfo::lat() const {
  // @@protoc_insertion_point(field_get:msg.AgentRelationInfo.msg_AgentInfo.lat)
  return _internal_lat();
}
inline void msg_AgentInfo::_internal_set_lat(double value) {
  
  _impl_.lat_ = value;
}
inline void msg_AgentInfo::set_lat(double value) {
  _internal_set_lat(value);
  // @@protoc_insertion_point(field_set:msg.AgentRelationInfo.msg_AgentInfo.lat)
}

// double amsl = 7;
inline void msg_AgentInfo::clear_amsl() {
  _impl_.amsl_ = 0;
}
inline double msg_AgentInfo::_internal_amsl() const {
  return _impl_.amsl_;
}
inline double msg_AgentInfo::amsl() const {
  // @@protoc_insertion_point(field_get:msg.AgentRelationInfo.msg_AgentInfo.amsl)
  return _internal_amsl();
}
inline void msg_AgentInfo::_internal_set_amsl(double value) {
  
  _impl_.amsl_ = value;
}
inline void msg_AgentInfo::set_amsl(double value) {
  _internal_set_amsl(value);
  // @@protoc_insertion_point(field_set:msg.AgentRelationInfo.msg_AgentInfo.amsl)
}

// int32 ref = 8;
inline void msg_AgentInfo::clear_ref() {
  _impl_.ref_ = 0;
}
inline int32_t msg_AgentInfo::_internal_ref() const {
  return _impl_.ref_;
}
inline int32_t msg_AgentInfo::ref() const {
  // @@protoc_insertion_point(field_get:msg.AgentRelationInfo.msg_AgentInfo.ref)
  return _internal_ref();
}
inline void msg_AgentInfo::_internal_set_ref(int32_t value) {
  
  _impl_.ref_ = value;
}
inline void msg_AgentInfo::set_ref(int32_t value) {
  _internal_set_ref(value);
  // @@protoc_insertion_point(field_set:msg.AgentRelationInfo.msg_AgentInfo.ref)
}

// float roll = 9;
inline void msg_AgentInfo::clear_roll() {
  _impl_.roll_ = 0;
}
inline float msg_AgentInfo::_internal_roll() const {
  return _impl_.roll_;
}
inline float msg_AgentInfo::roll() const {
  // @@protoc_insertion_point(field_get:msg.AgentRelationInfo.msg_AgentInfo.roll)
  return _internal_roll();
}
inline void msg_AgentInfo::_internal_set_roll(float value) {
  
  _impl_.roll_ = value;
}
inline void msg_AgentInfo::set_roll(float value) {
  _internal_set_roll(value);
  // @@protoc_insertion_point(field_set:msg.AgentRelationInfo.msg_AgentInfo.roll)
}

// float pitch = 10;
inline void msg_AgentInfo::clear_pitch() {
  _impl_.pitch_ = 0;
}
inline float msg_AgentInfo::_internal_pitch() const {
  return _impl_.pitch_;
}
inline float msg_AgentInfo::pitch() const {
  // @@protoc_insertion_point(field_get:msg.AgentRelationInfo.msg_AgentInfo.pitch)
  return _internal_pitch();
}
inline void msg_AgentInfo::_internal_set_pitch(float value) {
  
  _impl_.pitch_ = value;
}
inline void msg_AgentInfo::set_pitch(float value) {
  _internal_set_pitch(value);
  // @@protoc_insertion_point(field_set:msg.AgentRelationInfo.msg_AgentInfo.pitch)
}

// float yaw = 11;
inline void msg_AgentInfo::clear_yaw() {
  _impl_.yaw_ = 0;
}
inline float msg_AgentInfo::_internal_yaw() const {
  return _impl_.yaw_;
}
inline float msg_AgentInfo::yaw() const {
  // @@protoc_insertion_point(field_get:msg.AgentRelationInfo.msg_AgentInfo.yaw)
  return _internal_yaw();
}
inline void msg_AgentInfo::_internal_set_yaw(float value) {
  
  _impl_.yaw_ = value;
}
inline void msg_AgentInfo::set_yaw(float value) {
  _internal_set_yaw(value);
  // @@protoc_insertion_point(field_set:msg.AgentRelationInfo.msg_AgentInfo.yaw)
}

// float speed = 12;
inline void msg_AgentInfo::clear_speed() {
  _impl_.speed_ = 0;
}
inline float msg_AgentInfo::_internal_speed() const {
  return _impl_.speed_;
}
inline float msg_AgentInfo::speed() const {
  // @@protoc_insertion_point(field_get:msg.AgentRelationInfo.msg_AgentInfo.speed)
  return _internal_speed();
}
inline void msg_AgentInfo::_internal_set_speed(float value) {
  
  _impl_.speed_ = value;
}
inline void msg_AgentInfo::set_speed(float value) {
  _internal_set_speed(value);
  // @@protoc_insertion_point(field_set:msg.AgentRelationInfo.msg_AgentInfo.speed)
}

// string iffcode = 13;
inline void msg_AgentInfo::clear_iffcode() {
  _impl_.iffcode_.ClearToEmpty();
}
inline const std::string& msg_AgentInfo::iffcode() const {
  // @@protoc_insertion_point(field_get:msg.AgentRelationInfo.msg_AgentInfo.iffcode)
  return _internal_iffcode();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void msg_AgentInfo::set_iffcode(ArgT0&& arg0, ArgT... args) {
 
 _impl_.iffcode_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg.AgentRelationInfo.msg_AgentInfo.iffcode)
}
inline std::string* msg_AgentInfo::mutable_iffcode() {
  std::string* _s = _internal_mutable_iffcode();
  // @@protoc_insertion_point(field_mutable:msg.AgentRelationInfo.msg_AgentInfo.iffcode)
  return _s;
}
inline const std::string& msg_AgentInfo::_internal_iffcode() const {
  return _impl_.iffcode_.Get();
}
inline void msg_AgentInfo::_internal_set_iffcode(const std::string& value) {
  
  _impl_.iffcode_.Set(value, GetArenaForAllocation());
}
inline std::string* msg_AgentInfo::_internal_mutable_iffcode() {
  
  return _impl_.iffcode_.Mutable(GetArenaForAllocation());
}
inline std::string* msg_AgentInfo::release_iffcode() {
  // @@protoc_insertion_point(field_release:msg.AgentRelationInfo.msg_AgentInfo.iffcode)
  return _impl_.iffcode_.Release();
}
inline void msg_AgentInfo::set_allocated_iffcode(std::string* iffcode) {
  if (iffcode != nullptr) {
    
  } else {
    
  }
  _impl_.iffcode_.SetAllocated(iffcode, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.iffcode_.IsDefault()) {
    _impl_.iffcode_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg.AgentRelationInfo.msg_AgentInfo.iffcode)
}

// -------------------------------------------------------------------

// msg_AgentRelationInfo

// .msg.AgentRelationInfo.msg_AgentInfo src_agent = 1;
inline bool msg_AgentRelationInfo::_internal_has_src_agent() const {
  return this != internal_default_instance() && _impl_.src_agent_ != nullptr;
}
inline bool msg_AgentRelationInfo::has_src_agent() const {
  return _internal_has_src_agent();
}
inline void msg_AgentRelationInfo::clear_src_agent() {
  if (GetArenaForAllocation() == nullptr && _impl_.src_agent_ != nullptr) {
    delete _impl_.src_agent_;
  }
  _impl_.src_agent_ = nullptr;
}
inline const ::msg::AgentRelationInfo::msg_AgentInfo& msg_AgentRelationInfo::_internal_src_agent() const {
  const ::msg::AgentRelationInfo::msg_AgentInfo* p = _impl_.src_agent_;
  return p != nullptr ? *p : reinterpret_cast<const ::msg::AgentRelationInfo::msg_AgentInfo&>(
      ::msg::AgentRelationInfo::_msg_AgentInfo_default_instance_);
}
inline const ::msg::AgentRelationInfo::msg_AgentInfo& msg_AgentRelationInfo::src_agent() const {
  // @@protoc_insertion_point(field_get:msg.AgentRelationInfo.msg_AgentRelationInfo.src_agent)
  return _internal_src_agent();
}
inline void msg_AgentRelationInfo::unsafe_arena_set_allocated_src_agent(
    ::msg::AgentRelationInfo::msg_AgentInfo* src_agent) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.src_agent_);
  }
  _impl_.src_agent_ = src_agent;
  if (src_agent) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:msg.AgentRelationInfo.msg_AgentRelationInfo.src_agent)
}
inline ::msg::AgentRelationInfo::msg_AgentInfo* msg_AgentRelationInfo::release_src_agent() {
  
  ::msg::AgentRelationInfo::msg_AgentInfo* temp = _impl_.src_agent_;
  _impl_.src_agent_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::msg::AgentRelationInfo::msg_AgentInfo* msg_AgentRelationInfo::unsafe_arena_release_src_agent() {
  // @@protoc_insertion_point(field_release:msg.AgentRelationInfo.msg_AgentRelationInfo.src_agent)
  
  ::msg::AgentRelationInfo::msg_AgentInfo* temp = _impl_.src_agent_;
  _impl_.src_agent_ = nullptr;
  return temp;
}
inline ::msg::AgentRelationInfo::msg_AgentInfo* msg_AgentRelationInfo::_internal_mutable_src_agent() {
  
  if (_impl_.src_agent_ == nullptr) {
    auto* p = CreateMaybeMessage<::msg::AgentRelationInfo::msg_AgentInfo>(GetArenaForAllocation());
    _impl_.src_agent_ = p;
  }
  return _impl_.src_agent_;
}
inline ::msg::AgentRelationInfo::msg_AgentInfo* msg_AgentRelationInfo::mutable_src_agent() {
  ::msg::AgentRelationInfo::msg_AgentInfo* _msg = _internal_mutable_src_agent();
  // @@protoc_insertion_point(field_mutable:msg.AgentRelationInfo.msg_AgentRelationInfo.src_agent)
  return _msg;
}
inline void msg_AgentRelationInfo::set_allocated_src_agent(::msg::AgentRelationInfo::msg_AgentInfo* src_agent) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.src_agent_;
  }
  if (src_agent) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(src_agent);
    if (message_arena != submessage_arena) {
      src_agent = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, src_agent, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.src_agent_ = src_agent;
  // @@protoc_insertion_point(field_set_allocated:msg.AgentRelationInfo.msg_AgentRelationInfo.src_agent)
}

// .msg.AgentRelationInfo.msg_AgentInfo dst_agent = 2;
inline bool msg_AgentRelationInfo::_internal_has_dst_agent() const {
  return this != internal_default_instance() && _impl_.dst_agent_ != nullptr;
}
inline bool msg_AgentRelationInfo::has_dst_agent() const {
  return _internal_has_dst_agent();
}
inline void msg_AgentRelationInfo::clear_dst_agent() {
  if (GetArenaForAllocation() == nullptr && _impl_.dst_agent_ != nullptr) {
    delete _impl_.dst_agent_;
  }
  _impl_.dst_agent_ = nullptr;
}
inline const ::msg::AgentRelationInfo::msg_AgentInfo& msg_AgentRelationInfo::_internal_dst_agent() const {
  const ::msg::AgentRelationInfo::msg_AgentInfo* p = _impl_.dst_agent_;
  return p != nullptr ? *p : reinterpret_cast<const ::msg::AgentRelationInfo::msg_AgentInfo&>(
      ::msg::AgentRelationInfo::_msg_AgentInfo_default_instance_);
}
inline const ::msg::AgentRelationInfo::msg_AgentInfo& msg_AgentRelationInfo::dst_agent() const {
  // @@protoc_insertion_point(field_get:msg.AgentRelationInfo.msg_AgentRelationInfo.dst_agent)
  return _internal_dst_agent();
}
inline void msg_AgentRelationInfo::unsafe_arena_set_allocated_dst_agent(
    ::msg::AgentRelationInfo::msg_AgentInfo* dst_agent) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.dst_agent_);
  }
  _impl_.dst_agent_ = dst_agent;
  if (dst_agent) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:msg.AgentRelationInfo.msg_AgentRelationInfo.dst_agent)
}
inline ::msg::AgentRelationInfo::msg_AgentInfo* msg_AgentRelationInfo::release_dst_agent() {
  
  ::msg::AgentRelationInfo::msg_AgentInfo* temp = _impl_.dst_agent_;
  _impl_.dst_agent_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::msg::AgentRelationInfo::msg_AgentInfo* msg_AgentRelationInfo::unsafe_arena_release_dst_agent() {
  // @@protoc_insertion_point(field_release:msg.AgentRelationInfo.msg_AgentRelationInfo.dst_agent)
  
  ::msg::AgentRelationInfo::msg_AgentInfo* temp = _impl_.dst_agent_;
  _impl_.dst_agent_ = nullptr;
  return temp;
}
inline ::msg::AgentRelationInfo::msg_AgentInfo* msg_AgentRelationInfo::_internal_mutable_dst_agent() {
  
  if (_impl_.dst_agent_ == nullptr) {
    auto* p = CreateMaybeMessage<::msg::AgentRelationInfo::msg_AgentInfo>(GetArenaForAllocation());
    _impl_.dst_agent_ = p;
  }
  return _impl_.dst_agent_;
}
inline ::msg::AgentRelationInfo::msg_AgentInfo* msg_AgentRelationInfo::mutable_dst_agent() {
  ::msg::AgentRelationInfo::msg_AgentInfo* _msg = _internal_mutable_dst_agent();
  // @@protoc_insertion_point(field_mutable:msg.AgentRelationInfo.msg_AgentRelationInfo.dst_agent)
  return _msg;
}
inline void msg_AgentRelationInfo::set_allocated_dst_agent(::msg::AgentRelationInfo::msg_AgentInfo* dst_agent) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.dst_agent_;
  }
  if (dst_agent) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(dst_agent);
    if (message_arena != submessage_arena) {
      dst_agent = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, dst_agent, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.dst_agent_ = dst_agent;
  // @@protoc_insertion_point(field_set_allocated:msg.AgentRelationInfo.msg_AgentRelationInfo.dst_agent)
}

// .msg.AgentRelationInfo.E_RELATIONTYPE relationtype = 3;
inline void msg_AgentRelationInfo::clear_relationtype() {
  _impl_.relationtype_ = 0;
}
inline ::msg::AgentRelationInfo::E_RELATIONTYPE msg_AgentRelationInfo::_internal_relationtype() const {
  return static_cast< ::msg::AgentRelationInfo::E_RELATIONTYPE >(_impl_.relationtype_);
}
inline ::msg::AgentRelationInfo::E_RELATIONTYPE msg_AgentRelationInfo::relationtype() const {
  // @@protoc_insertion_point(field_get:msg.AgentRelationInfo.msg_AgentRelationInfo.relationtype)
  return _internal_relationtype();
}
inline void msg_AgentRelationInfo::_internal_set_relationtype(::msg::AgentRelationInfo::E_RELATIONTYPE value) {
  
  _impl_.relationtype_ = value;
}
inline void msg_AgentRelationInfo::set_relationtype(::msg::AgentRelationInfo::E_RELATIONTYPE value) {
  _internal_set_relationtype(value);
  // @@protoc_insertion_point(field_set:msg.AgentRelationInfo.msg_AgentRelationInfo.relationtype)
}

// .msg.AgentRelationInfo.E_REFRESHTYPE refreshtype = 4;
inline void msg_AgentRelationInfo::clear_refreshtype() {
  _impl_.refreshtype_ = 0;
}
inline ::msg::AgentRelationInfo::E_REFRESHTYPE msg_AgentRelationInfo::_internal_refreshtype() const {
  return static_cast< ::msg::AgentRelationInfo::E_REFRESHTYPE >(_impl_.refreshtype_);
}
inline ::msg::AgentRelationInfo::E_REFRESHTYPE msg_AgentRelationInfo::refreshtype() const {
  // @@protoc_insertion_point(field_get:msg.AgentRelationInfo.msg_AgentRelationInfo.refreshtype)
  return _internal_refreshtype();
}
inline void msg_AgentRelationInfo::_internal_set_refreshtype(::msg::AgentRelationInfo::E_REFRESHTYPE value) {
  
  _impl_.refreshtype_ = value;
}
inline void msg_AgentRelationInfo::set_refreshtype(::msg::AgentRelationInfo::E_REFRESHTYPE value) {
  _internal_set_refreshtype(value);
  // @@protoc_insertion_point(field_set:msg.AgentRelationInfo.msg_AgentRelationInfo.refreshtype)
}

// string updatetimestamp = 5;
inline void msg_AgentRelationInfo::clear_updatetimestamp() {
  _impl_.updatetimestamp_.ClearToEmpty();
}
inline const std::string& msg_AgentRelationInfo::updatetimestamp() const {
  // @@protoc_insertion_point(field_get:msg.AgentRelationInfo.msg_AgentRelationInfo.updatetimestamp)
  return _internal_updatetimestamp();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void msg_AgentRelationInfo::set_updatetimestamp(ArgT0&& arg0, ArgT... args) {
 
 _impl_.updatetimestamp_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg.AgentRelationInfo.msg_AgentRelationInfo.updatetimestamp)
}
inline std::string* msg_AgentRelationInfo::mutable_updatetimestamp() {
  std::string* _s = _internal_mutable_updatetimestamp();
  // @@protoc_insertion_point(field_mutable:msg.AgentRelationInfo.msg_AgentRelationInfo.updatetimestamp)
  return _s;
}
inline const std::string& msg_AgentRelationInfo::_internal_updatetimestamp() const {
  return _impl_.updatetimestamp_.Get();
}
inline void msg_AgentRelationInfo::_internal_set_updatetimestamp(const std::string& value) {
  
  _impl_.updatetimestamp_.Set(value, GetArenaForAllocation());
}
inline std::string* msg_AgentRelationInfo::_internal_mutable_updatetimestamp() {
  
  return _impl_.updatetimestamp_.Mutable(GetArenaForAllocation());
}
inline std::string* msg_AgentRelationInfo::release_updatetimestamp() {
  // @@protoc_insertion_point(field_release:msg.AgentRelationInfo.msg_AgentRelationInfo.updatetimestamp)
  return _impl_.updatetimestamp_.Release();
}
inline void msg_AgentRelationInfo::set_allocated_updatetimestamp(std::string* updatetimestamp) {
  if (updatetimestamp != nullptr) {
    
  } else {
    
  }
  _impl_.updatetimestamp_.SetAllocated(updatetimestamp, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.updatetimestamp_.IsDefault()) {
    _impl_.updatetimestamp_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg.AgentRelationInfo.msg_AgentRelationInfo.updatetimestamp)
}

// double distance = 6;
inline void msg_AgentRelationInfo::clear_distance() {
  _impl_.distance_ = 0;
}
inline double msg_AgentRelationInfo::_internal_distance() const {
  return _impl_.distance_;
}
inline double msg_AgentRelationInfo::distance() const {
  // @@protoc_insertion_point(field_get:msg.AgentRelationInfo.msg_AgentRelationInfo.distance)
  return _internal_distance();
}
inline void msg_AgentRelationInfo::_internal_set_distance(double value) {
  
  _impl_.distance_ = value;
}
inline void msg_AgentRelationInfo::set_distance(double value) {
  _internal_set_distance(value);
  // @@protoc_insertion_point(field_set:msg.AgentRelationInfo.msg_AgentRelationInfo.distance)
}

// int32 usage = 7;
inline void msg_AgentRelationInfo::clear_usage() {
  _impl_.usage_ = 0;
}
inline int32_t msg_AgentRelationInfo::_internal_usage() const {
  return _impl_.usage_;
}
inline int32_t msg_AgentRelationInfo::usage() const {
  // @@protoc_insertion_point(field_get:msg.AgentRelationInfo.msg_AgentRelationInfo.usage)
  return _internal_usage();
}
inline void msg_AgentRelationInfo::_internal_set_usage(int32_t value) {
  
  _impl_.usage_ = value;
}
inline void msg_AgentRelationInfo::set_usage(int32_t value) {
  _internal_set_usage(value);
  // @@protoc_insertion_point(field_set:msg.AgentRelationInfo.msg_AgentRelationInfo.usage)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace AgentRelationInfo
}  // namespace msg

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::msg::AgentRelationInfo::E_RELATIONTYPE> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::msg::AgentRelationInfo::E_RELATIONTYPE>() {
  return ::msg::AgentRelationInfo::E_RELATIONTYPE_descriptor();
}
template <> struct is_proto_enum< ::msg::AgentRelationInfo::E_REFRESHTYPE> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::msg::AgentRelationInfo::E_REFRESHTYPE>() {
  return ::msg::AgentRelationInfo::E_REFRESHTYPE_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_AgentRelationInfo_2eproto
