// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommStackFrameResultElement.proto

#include "CommStackFrameResultElement.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace msg {
namespace CommStackFrameResultElement {
PROTOBUF_CONSTEXPR msg_CommStackFrameResultElement::msg_CommStackFrameResultElement(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.src_agent_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.dst_agent_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.engine_keyed_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.framehextext_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.ber_)*/0
  , /*decltype(_impl_.fer_)*/0
  , /*decltype(_impl_.packindex_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct msg_CommStackFrameResultElementDefaultTypeInternal {
  PROTOBUF_CONSTEXPR msg_CommStackFrameResultElementDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~msg_CommStackFrameResultElementDefaultTypeInternal() {}
  union {
    msg_CommStackFrameResultElement _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 msg_CommStackFrameResultElementDefaultTypeInternal _msg_CommStackFrameResultElement_default_instance_;
}  // namespace CommStackFrameResultElement
}  // namespace msg
static ::_pb::Metadata file_level_metadata_CommStackFrameResultElement_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_CommStackFrameResultElement_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_CommStackFrameResultElement_2eproto = nullptr;

const uint32_t TableStruct_CommStackFrameResultElement_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::msg::CommStackFrameResultElement::msg_CommStackFrameResultElement, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::msg::CommStackFrameResultElement::msg_CommStackFrameResultElement, _impl_.src_agent_),
  PROTOBUF_FIELD_OFFSET(::msg::CommStackFrameResultElement::msg_CommStackFrameResultElement, _impl_.dst_agent_),
  PROTOBUF_FIELD_OFFSET(::msg::CommStackFrameResultElement::msg_CommStackFrameResultElement, _impl_.engine_keyed_name_),
  PROTOBUF_FIELD_OFFSET(::msg::CommStackFrameResultElement::msg_CommStackFrameResultElement, _impl_.ber_),
  PROTOBUF_FIELD_OFFSET(::msg::CommStackFrameResultElement::msg_CommStackFrameResultElement, _impl_.fer_),
  PROTOBUF_FIELD_OFFSET(::msg::CommStackFrameResultElement::msg_CommStackFrameResultElement, _impl_.framehextext_),
  PROTOBUF_FIELD_OFFSET(::msg::CommStackFrameResultElement::msg_CommStackFrameResultElement, _impl_.packindex_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::msg::CommStackFrameResultElement::msg_CommStackFrameResultElement)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::msg::CommStackFrameResultElement::_msg_CommStackFrameResultElement_default_instance_._instance,
};

const char descriptor_table_protodef_CommStackFrameResultElement_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n!CommStackFrameResultElement.proto\022\037msg"
  ".CommStackFrameResultElement\"\245\001\n\037msg_Com"
  "mStackFrameResultElement\022\021\n\tsrc_agent\030\001 "
  "\001(\t\022\021\n\tdst_agent\030\002 \001(\t\022\031\n\021engine_keyed_n"
  "ame\030\003 \001(\t\022\013\n\003ber\030\004 \001(\002\022\013\n\003fer\030\005 \001(\002\022\024\n\014f"
  "ramehextext\030\006 \001(\t\022\021\n\tpackindex\030\007 \001(\rb\006pr"
  "oto3"
  ;
static ::_pbi::once_flag descriptor_table_CommStackFrameResultElement_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_CommStackFrameResultElement_2eproto = {
    false, false, 244, descriptor_table_protodef_CommStackFrameResultElement_2eproto,
    "CommStackFrameResultElement.proto",
    &descriptor_table_CommStackFrameResultElement_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_CommStackFrameResultElement_2eproto::offsets,
    file_level_metadata_CommStackFrameResultElement_2eproto, file_level_enum_descriptors_CommStackFrameResultElement_2eproto,
    file_level_service_descriptors_CommStackFrameResultElement_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_CommStackFrameResultElement_2eproto_getter() {
  return &descriptor_table_CommStackFrameResultElement_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_CommStackFrameResultElement_2eproto(&descriptor_table_CommStackFrameResultElement_2eproto);
namespace msg {
namespace CommStackFrameResultElement {

// ===================================================================

class msg_CommStackFrameResultElement::_Internal {
 public:
};

msg_CommStackFrameResultElement::msg_CommStackFrameResultElement(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement)
}
msg_CommStackFrameResultElement::msg_CommStackFrameResultElement(const msg_CommStackFrameResultElement& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  msg_CommStackFrameResultElement* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.src_agent_){}
    , decltype(_impl_.dst_agent_){}
    , decltype(_impl_.engine_keyed_name_){}
    , decltype(_impl_.framehextext_){}
    , decltype(_impl_.ber_){}
    , decltype(_impl_.fer_){}
    , decltype(_impl_.packindex_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.src_agent_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.src_agent_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_src_agent().empty()) {
    _this->_impl_.src_agent_.Set(from._internal_src_agent(), 
      _this->GetArenaForAllocation());
  }
  _impl_.dst_agent_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.dst_agent_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_dst_agent().empty()) {
    _this->_impl_.dst_agent_.Set(from._internal_dst_agent(), 
      _this->GetArenaForAllocation());
  }
  _impl_.engine_keyed_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.engine_keyed_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_engine_keyed_name().empty()) {
    _this->_impl_.engine_keyed_name_.Set(from._internal_engine_keyed_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.framehextext_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.framehextext_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_framehextext().empty()) {
    _this->_impl_.framehextext_.Set(from._internal_framehextext(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.ber_, &from._impl_.ber_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.packindex_) -
    reinterpret_cast<char*>(&_impl_.ber_)) + sizeof(_impl_.packindex_));
  // @@protoc_insertion_point(copy_constructor:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement)
}

inline void msg_CommStackFrameResultElement::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.src_agent_){}
    , decltype(_impl_.dst_agent_){}
    , decltype(_impl_.engine_keyed_name_){}
    , decltype(_impl_.framehextext_){}
    , decltype(_impl_.ber_){0}
    , decltype(_impl_.fer_){0}
    , decltype(_impl_.packindex_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.src_agent_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.src_agent_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.dst_agent_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.dst_agent_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.engine_keyed_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.engine_keyed_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.framehextext_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.framehextext_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

msg_CommStackFrameResultElement::~msg_CommStackFrameResultElement() {
  // @@protoc_insertion_point(destructor:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void msg_CommStackFrameResultElement::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.src_agent_.Destroy();
  _impl_.dst_agent_.Destroy();
  _impl_.engine_keyed_name_.Destroy();
  _impl_.framehextext_.Destroy();
}

void msg_CommStackFrameResultElement::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void msg_CommStackFrameResultElement::Clear() {
// @@protoc_insertion_point(message_clear_start:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.src_agent_.ClearToEmpty();
  _impl_.dst_agent_.ClearToEmpty();
  _impl_.engine_keyed_name_.ClearToEmpty();
  _impl_.framehextext_.ClearToEmpty();
  ::memset(&_impl_.ber_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.packindex_) -
      reinterpret_cast<char*>(&_impl_.ber_)) + sizeof(_impl_.packindex_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* msg_CommStackFrameResultElement::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string src_agent = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_src_agent();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.src_agent"));
        } else
          goto handle_unusual;
        continue;
      // string dst_agent = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_dst_agent();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.dst_agent"));
        } else
          goto handle_unusual;
        continue;
      // string engine_keyed_name = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_engine_keyed_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.engine_keyed_name"));
        } else
          goto handle_unusual;
        continue;
      // float ber = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 37)) {
          _impl_.ber_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float fer = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 45)) {
          _impl_.fer_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // string framehextext = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_framehextext();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.framehextext"));
        } else
          goto handle_unusual;
        continue;
      // uint32 packindex = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.packindex_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* msg_CommStackFrameResultElement::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string src_agent = 1;
  if (!this->_internal_src_agent().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_src_agent().data(), static_cast<int>(this->_internal_src_agent().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.src_agent");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_src_agent(), target);
  }

  // string dst_agent = 2;
  if (!this->_internal_dst_agent().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_dst_agent().data(), static_cast<int>(this->_internal_dst_agent().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.dst_agent");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_dst_agent(), target);
  }

  // string engine_keyed_name = 3;
  if (!this->_internal_engine_keyed_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_engine_keyed_name().data(), static_cast<int>(this->_internal_engine_keyed_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.engine_keyed_name");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_engine_keyed_name(), target);
  }

  // float ber = 4;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_ber = this->_internal_ber();
  uint32_t raw_ber;
  memcpy(&raw_ber, &tmp_ber, sizeof(tmp_ber));
  if (raw_ber != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(4, this->_internal_ber(), target);
  }

  // float fer = 5;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_fer = this->_internal_fer();
  uint32_t raw_fer;
  memcpy(&raw_fer, &tmp_fer, sizeof(tmp_fer));
  if (raw_fer != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(5, this->_internal_fer(), target);
  }

  // string framehextext = 6;
  if (!this->_internal_framehextext().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_framehextext().data(), static_cast<int>(this->_internal_framehextext().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.framehextext");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_framehextext(), target);
  }

  // uint32 packindex = 7;
  if (this->_internal_packindex() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(7, this->_internal_packindex(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement)
  return target;
}

size_t msg_CommStackFrameResultElement::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string src_agent = 1;
  if (!this->_internal_src_agent().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_src_agent());
  }

  // string dst_agent = 2;
  if (!this->_internal_dst_agent().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_dst_agent());
  }

  // string engine_keyed_name = 3;
  if (!this->_internal_engine_keyed_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_engine_keyed_name());
  }

  // string framehextext = 6;
  if (!this->_internal_framehextext().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_framehextext());
  }

  // float ber = 4;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_ber = this->_internal_ber();
  uint32_t raw_ber;
  memcpy(&raw_ber, &tmp_ber, sizeof(tmp_ber));
  if (raw_ber != 0) {
    total_size += 1 + 4;
  }

  // float fer = 5;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_fer = this->_internal_fer();
  uint32_t raw_fer;
  memcpy(&raw_fer, &tmp_fer, sizeof(tmp_fer));
  if (raw_fer != 0) {
    total_size += 1 + 4;
  }

  // uint32 packindex = 7;
  if (this->_internal_packindex() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_packindex());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData msg_CommStackFrameResultElement::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    msg_CommStackFrameResultElement::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*msg_CommStackFrameResultElement::GetClassData() const { return &_class_data_; }


void msg_CommStackFrameResultElement::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<msg_CommStackFrameResultElement*>(&to_msg);
  auto& from = static_cast<const msg_CommStackFrameResultElement&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_src_agent().empty()) {
    _this->_internal_set_src_agent(from._internal_src_agent());
  }
  if (!from._internal_dst_agent().empty()) {
    _this->_internal_set_dst_agent(from._internal_dst_agent());
  }
  if (!from._internal_engine_keyed_name().empty()) {
    _this->_internal_set_engine_keyed_name(from._internal_engine_keyed_name());
  }
  if (!from._internal_framehextext().empty()) {
    _this->_internal_set_framehextext(from._internal_framehextext());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_ber = from._internal_ber();
  uint32_t raw_ber;
  memcpy(&raw_ber, &tmp_ber, sizeof(tmp_ber));
  if (raw_ber != 0) {
    _this->_internal_set_ber(from._internal_ber());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_fer = from._internal_fer();
  uint32_t raw_fer;
  memcpy(&raw_fer, &tmp_fer, sizeof(tmp_fer));
  if (raw_fer != 0) {
    _this->_internal_set_fer(from._internal_fer());
  }
  if (from._internal_packindex() != 0) {
    _this->_internal_set_packindex(from._internal_packindex());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void msg_CommStackFrameResultElement::CopyFrom(const msg_CommStackFrameResultElement& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool msg_CommStackFrameResultElement::IsInitialized() const {
  return true;
}

void msg_CommStackFrameResultElement::InternalSwap(msg_CommStackFrameResultElement* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.src_agent_, lhs_arena,
      &other->_impl_.src_agent_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.dst_agent_, lhs_arena,
      &other->_impl_.dst_agent_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.engine_keyed_name_, lhs_arena,
      &other->_impl_.engine_keyed_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.framehextext_, lhs_arena,
      &other->_impl_.framehextext_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(msg_CommStackFrameResultElement, _impl_.packindex_)
      + sizeof(msg_CommStackFrameResultElement::_impl_.packindex_)
      - PROTOBUF_FIELD_OFFSET(msg_CommStackFrameResultElement, _impl_.ber_)>(
          reinterpret_cast<char*>(&_impl_.ber_),
          reinterpret_cast<char*>(&other->_impl_.ber_));
}

::PROTOBUF_NAMESPACE_ID::Metadata msg_CommStackFrameResultElement::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_CommStackFrameResultElement_2eproto_getter, &descriptor_table_CommStackFrameResultElement_2eproto_once,
      file_level_metadata_CommStackFrameResultElement_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace CommStackFrameResultElement
}  // namespace msg
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::msg::CommStackFrameResultElement::msg_CommStackFrameResultElement*
Arena::CreateMaybeMessage< ::msg::CommStackFrameResultElement::msg_CommStackFrameResultElement >(Arena* arena) {
  return Arena::CreateMessageInternal< ::msg::CommStackFrameResultElement::msg_CommStackFrameResultElement >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
