// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommStackFrameResultElement.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_CommStackFrameResultElement_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_CommStackFrameResultElement_2eproto

#include "gaeactor_comm_global.h"

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_CommStackFrameResultElement_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_CommStackFrameResultElement_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_CommStackFrameResultElement_2eproto;
namespace msg {
namespace CommStackFrameResultElement {
class msg_CommStackFrameResultElement;
struct msg_CommStackFrameResultElementDefaultTypeInternal;
extern msg_CommStackFrameResultElementDefaultTypeInternal _msg_CommStackFrameResultElement_default_instance_;
}  // namespace CommStackFrameResultElement
}  // namespace msg
PROTOBUF_NAMESPACE_OPEN
template<> ::msg::CommStackFrameResultElement::msg_CommStackFrameResultElement* Arena::CreateMaybeMessage<::msg::CommStackFrameResultElement::msg_CommStackFrameResultElement>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace msg {
namespace CommStackFrameResultElement {

// ===================================================================

class GAEACTOR_COMM_EXPORT msg_CommStackFrameResultElement final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement) */ {
 public:
  inline msg_CommStackFrameResultElement() : msg_CommStackFrameResultElement(nullptr) {}
  ~msg_CommStackFrameResultElement() override;
  explicit PROTOBUF_CONSTEXPR msg_CommStackFrameResultElement(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  msg_CommStackFrameResultElement(const msg_CommStackFrameResultElement& from);
  msg_CommStackFrameResultElement(msg_CommStackFrameResultElement&& from) noexcept
    : msg_CommStackFrameResultElement() {
    *this = ::std::move(from);
  }

  inline msg_CommStackFrameResultElement& operator=(const msg_CommStackFrameResultElement& from) {
    CopyFrom(from);
    return *this;
  }
  inline msg_CommStackFrameResultElement& operator=(msg_CommStackFrameResultElement&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const msg_CommStackFrameResultElement& default_instance() {
    return *internal_default_instance();
  }
  static inline const msg_CommStackFrameResultElement* internal_default_instance() {
    return reinterpret_cast<const msg_CommStackFrameResultElement*>(
               &_msg_CommStackFrameResultElement_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(msg_CommStackFrameResultElement& a, msg_CommStackFrameResultElement& b) {
    a.Swap(&b);
  }
  inline void Swap(msg_CommStackFrameResultElement* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(msg_CommStackFrameResultElement* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  msg_CommStackFrameResultElement* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<msg_CommStackFrameResultElement>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const msg_CommStackFrameResultElement& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const msg_CommStackFrameResultElement& from) {
    msg_CommStackFrameResultElement::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(msg_CommStackFrameResultElement* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg.CommStackFrameResultElement.msg_CommStackFrameResultElement";
  }
  protected:
  explicit msg_CommStackFrameResultElement(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSrcAgentFieldNumber = 1,
    kDstAgentFieldNumber = 2,
    kEngineKeyedNameFieldNumber = 3,
    kFramehextextFieldNumber = 6,
    kBerFieldNumber = 4,
    kFerFieldNumber = 5,
    kPackindexFieldNumber = 7,
  };
  // string src_agent = 1;
  void clear_src_agent();
  const std::string& src_agent() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_src_agent(ArgT0&& arg0, ArgT... args);
  std::string* mutable_src_agent();
  PROTOBUF_NODISCARD std::string* release_src_agent();
  void set_allocated_src_agent(std::string* src_agent);
  private:
  const std::string& _internal_src_agent() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_src_agent(const std::string& value);
  std::string* _internal_mutable_src_agent();
  public:

  // string dst_agent = 2;
  void clear_dst_agent();
  const std::string& dst_agent() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_dst_agent(ArgT0&& arg0, ArgT... args);
  std::string* mutable_dst_agent();
  PROTOBUF_NODISCARD std::string* release_dst_agent();
  void set_allocated_dst_agent(std::string* dst_agent);
  private:
  const std::string& _internal_dst_agent() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_dst_agent(const std::string& value);
  std::string* _internal_mutable_dst_agent();
  public:

  // string engine_keyed_name = 3;
  void clear_engine_keyed_name();
  const std::string& engine_keyed_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_engine_keyed_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_engine_keyed_name();
  PROTOBUF_NODISCARD std::string* release_engine_keyed_name();
  void set_allocated_engine_keyed_name(std::string* engine_keyed_name);
  private:
  const std::string& _internal_engine_keyed_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_engine_keyed_name(const std::string& value);
  std::string* _internal_mutable_engine_keyed_name();
  public:

  // string framehextext = 6;
  void clear_framehextext();
  const std::string& framehextext() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_framehextext(ArgT0&& arg0, ArgT... args);
  std::string* mutable_framehextext();
  PROTOBUF_NODISCARD std::string* release_framehextext();
  void set_allocated_framehextext(std::string* framehextext);
  private:
  const std::string& _internal_framehextext() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_framehextext(const std::string& value);
  std::string* _internal_mutable_framehextext();
  public:

  // float ber = 4;
  void clear_ber();
  float ber() const;
  void set_ber(float value);
  private:
  float _internal_ber() const;
  void _internal_set_ber(float value);
  public:

  // float fer = 5;
  void clear_fer();
  float fer() const;
  void set_fer(float value);
  private:
  float _internal_fer() const;
  void _internal_set_fer(float value);
  public:

  // uint32 packindex = 7;
  void clear_packindex();
  uint32_t packindex() const;
  void set_packindex(uint32_t value);
  private:
  uint32_t _internal_packindex() const;
  void _internal_set_packindex(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr src_agent_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr dst_agent_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr engine_keyed_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr framehextext_;
    float ber_;
    float fer_;
    uint32_t packindex_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_CommStackFrameResultElement_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// msg_CommStackFrameResultElement

// string src_agent = 1;
inline void msg_CommStackFrameResultElement::clear_src_agent() {
  _impl_.src_agent_.ClearToEmpty();
}
inline const std::string& msg_CommStackFrameResultElement::src_agent() const {
  // @@protoc_insertion_point(field_get:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.src_agent)
  return _internal_src_agent();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void msg_CommStackFrameResultElement::set_src_agent(ArgT0&& arg0, ArgT... args) {
 
 _impl_.src_agent_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.src_agent)
}
inline std::string* msg_CommStackFrameResultElement::mutable_src_agent() {
  std::string* _s = _internal_mutable_src_agent();
  // @@protoc_insertion_point(field_mutable:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.src_agent)
  return _s;
}
inline const std::string& msg_CommStackFrameResultElement::_internal_src_agent() const {
  return _impl_.src_agent_.Get();
}
inline void msg_CommStackFrameResultElement::_internal_set_src_agent(const std::string& value) {
  
  _impl_.src_agent_.Set(value, GetArenaForAllocation());
}
inline std::string* msg_CommStackFrameResultElement::_internal_mutable_src_agent() {
  
  return _impl_.src_agent_.Mutable(GetArenaForAllocation());
}
inline std::string* msg_CommStackFrameResultElement::release_src_agent() {
  // @@protoc_insertion_point(field_release:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.src_agent)
  return _impl_.src_agent_.Release();
}
inline void msg_CommStackFrameResultElement::set_allocated_src_agent(std::string* src_agent) {
  if (src_agent != nullptr) {
    
  } else {
    
  }
  _impl_.src_agent_.SetAllocated(src_agent, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.src_agent_.IsDefault()) {
    _impl_.src_agent_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.src_agent)
}

// string dst_agent = 2;
inline void msg_CommStackFrameResultElement::clear_dst_agent() {
  _impl_.dst_agent_.ClearToEmpty();
}
inline const std::string& msg_CommStackFrameResultElement::dst_agent() const {
  // @@protoc_insertion_point(field_get:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.dst_agent)
  return _internal_dst_agent();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void msg_CommStackFrameResultElement::set_dst_agent(ArgT0&& arg0, ArgT... args) {
 
 _impl_.dst_agent_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.dst_agent)
}
inline std::string* msg_CommStackFrameResultElement::mutable_dst_agent() {
  std::string* _s = _internal_mutable_dst_agent();
  // @@protoc_insertion_point(field_mutable:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.dst_agent)
  return _s;
}
inline const std::string& msg_CommStackFrameResultElement::_internal_dst_agent() const {
  return _impl_.dst_agent_.Get();
}
inline void msg_CommStackFrameResultElement::_internal_set_dst_agent(const std::string& value) {
  
  _impl_.dst_agent_.Set(value, GetArenaForAllocation());
}
inline std::string* msg_CommStackFrameResultElement::_internal_mutable_dst_agent() {
  
  return _impl_.dst_agent_.Mutable(GetArenaForAllocation());
}
inline std::string* msg_CommStackFrameResultElement::release_dst_agent() {
  // @@protoc_insertion_point(field_release:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.dst_agent)
  return _impl_.dst_agent_.Release();
}
inline void msg_CommStackFrameResultElement::set_allocated_dst_agent(std::string* dst_agent) {
  if (dst_agent != nullptr) {
    
  } else {
    
  }
  _impl_.dst_agent_.SetAllocated(dst_agent, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.dst_agent_.IsDefault()) {
    _impl_.dst_agent_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.dst_agent)
}

// string engine_keyed_name = 3;
inline void msg_CommStackFrameResultElement::clear_engine_keyed_name() {
  _impl_.engine_keyed_name_.ClearToEmpty();
}
inline const std::string& msg_CommStackFrameResultElement::engine_keyed_name() const {
  // @@protoc_insertion_point(field_get:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.engine_keyed_name)
  return _internal_engine_keyed_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void msg_CommStackFrameResultElement::set_engine_keyed_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.engine_keyed_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.engine_keyed_name)
}
inline std::string* msg_CommStackFrameResultElement::mutable_engine_keyed_name() {
  std::string* _s = _internal_mutable_engine_keyed_name();
  // @@protoc_insertion_point(field_mutable:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.engine_keyed_name)
  return _s;
}
inline const std::string& msg_CommStackFrameResultElement::_internal_engine_keyed_name() const {
  return _impl_.engine_keyed_name_.Get();
}
inline void msg_CommStackFrameResultElement::_internal_set_engine_keyed_name(const std::string& value) {
  
  _impl_.engine_keyed_name_.Set(value, GetArenaForAllocation());
}
inline std::string* msg_CommStackFrameResultElement::_internal_mutable_engine_keyed_name() {
  
  return _impl_.engine_keyed_name_.Mutable(GetArenaForAllocation());
}
inline std::string* msg_CommStackFrameResultElement::release_engine_keyed_name() {
  // @@protoc_insertion_point(field_release:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.engine_keyed_name)
  return _impl_.engine_keyed_name_.Release();
}
inline void msg_CommStackFrameResultElement::set_allocated_engine_keyed_name(std::string* engine_keyed_name) {
  if (engine_keyed_name != nullptr) {
    
  } else {
    
  }
  _impl_.engine_keyed_name_.SetAllocated(engine_keyed_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.engine_keyed_name_.IsDefault()) {
    _impl_.engine_keyed_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.engine_keyed_name)
}

// float ber = 4;
inline void msg_CommStackFrameResultElement::clear_ber() {
  _impl_.ber_ = 0;
}
inline float msg_CommStackFrameResultElement::_internal_ber() const {
  return _impl_.ber_;
}
inline float msg_CommStackFrameResultElement::ber() const {
  // @@protoc_insertion_point(field_get:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.ber)
  return _internal_ber();
}
inline void msg_CommStackFrameResultElement::_internal_set_ber(float value) {
  
  _impl_.ber_ = value;
}
inline void msg_CommStackFrameResultElement::set_ber(float value) {
  _internal_set_ber(value);
  // @@protoc_insertion_point(field_set:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.ber)
}

// float fer = 5;
inline void msg_CommStackFrameResultElement::clear_fer() {
  _impl_.fer_ = 0;
}
inline float msg_CommStackFrameResultElement::_internal_fer() const {
  return _impl_.fer_;
}
inline float msg_CommStackFrameResultElement::fer() const {
  // @@protoc_insertion_point(field_get:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.fer)
  return _internal_fer();
}
inline void msg_CommStackFrameResultElement::_internal_set_fer(float value) {
  
  _impl_.fer_ = value;
}
inline void msg_CommStackFrameResultElement::set_fer(float value) {
  _internal_set_fer(value);
  // @@protoc_insertion_point(field_set:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.fer)
}

// string framehextext = 6;
inline void msg_CommStackFrameResultElement::clear_framehextext() {
  _impl_.framehextext_.ClearToEmpty();
}
inline const std::string& msg_CommStackFrameResultElement::framehextext() const {
  // @@protoc_insertion_point(field_get:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.framehextext)
  return _internal_framehextext();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void msg_CommStackFrameResultElement::set_framehextext(ArgT0&& arg0, ArgT... args) {
 
 _impl_.framehextext_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.framehextext)
}
inline std::string* msg_CommStackFrameResultElement::mutable_framehextext() {
  std::string* _s = _internal_mutable_framehextext();
  // @@protoc_insertion_point(field_mutable:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.framehextext)
  return _s;
}
inline const std::string& msg_CommStackFrameResultElement::_internal_framehextext() const {
  return _impl_.framehextext_.Get();
}
inline void msg_CommStackFrameResultElement::_internal_set_framehextext(const std::string& value) {
  
  _impl_.framehextext_.Set(value, GetArenaForAllocation());
}
inline std::string* msg_CommStackFrameResultElement::_internal_mutable_framehextext() {
  
  return _impl_.framehextext_.Mutable(GetArenaForAllocation());
}
inline std::string* msg_CommStackFrameResultElement::release_framehextext() {
  // @@protoc_insertion_point(field_release:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.framehextext)
  return _impl_.framehextext_.Release();
}
inline void msg_CommStackFrameResultElement::set_allocated_framehextext(std::string* framehextext) {
  if (framehextext != nullptr) {
    
  } else {
    
  }
  _impl_.framehextext_.SetAllocated(framehextext, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.framehextext_.IsDefault()) {
    _impl_.framehextext_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.framehextext)
}

// uint32 packindex = 7;
inline void msg_CommStackFrameResultElement::clear_packindex() {
  _impl_.packindex_ = 0u;
}
inline uint32_t msg_CommStackFrameResultElement::_internal_packindex() const {
  return _impl_.packindex_;
}
inline uint32_t msg_CommStackFrameResultElement::packindex() const {
  // @@protoc_insertion_point(field_get:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.packindex)
  return _internal_packindex();
}
inline void msg_CommStackFrameResultElement::_internal_set_packindex(uint32_t value) {
  
  _impl_.packindex_ = value;
}
inline void msg_CommStackFrameResultElement::set_packindex(uint32_t value) {
  _internal_set_packindex(value);
  // @@protoc_insertion_point(field_set:msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.packindex)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace CommStackFrameResultElement
}  // namespace msg

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_CommStackFrameResultElement_2eproto
