// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommStackFrameElement.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_CommStackFrameElement_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_CommStackFrameElement_2eproto

#include "gaeactor_comm_global.h"

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_CommStackFrameElement_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_CommStackFrameElement_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_CommStackFrameElement_2eproto;
namespace msg {
namespace CommStackFrameElement {
class msg_CommStackFrameElement;
struct msg_CommStackFrameElementDefaultTypeInternal;
extern msg_CommStackFrameElementDefaultTypeInternal _msg_CommStackFrameElement_default_instance_;
class msg_CommStackFrameElement_Array;
struct msg_CommStackFrameElement_ArrayDefaultTypeInternal;
extern msg_CommStackFrameElement_ArrayDefaultTypeInternal _msg_CommStackFrameElement_Array_default_instance_;
class msg_toAgentId_toUsages;
struct msg_toAgentId_toUsagesDefaultTypeInternal;
extern msg_toAgentId_toUsagesDefaultTypeInternal _msg_toAgentId_toUsages_default_instance_;
}  // namespace CommStackFrameElement
}  // namespace msg
PROTOBUF_NAMESPACE_OPEN
template<> ::msg::CommStackFrameElement::msg_CommStackFrameElement* Arena::CreateMaybeMessage<::msg::CommStackFrameElement::msg_CommStackFrameElement>(Arena*);
template<> ::msg::CommStackFrameElement::msg_CommStackFrameElement_Array* Arena::CreateMaybeMessage<::msg::CommStackFrameElement::msg_CommStackFrameElement_Array>(Arena*);
template<> ::msg::CommStackFrameElement::msg_toAgentId_toUsages* Arena::CreateMaybeMessage<::msg::CommStackFrameElement::msg_toAgentId_toUsages>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace msg {
namespace CommStackFrameElement {

// ===================================================================

class GAEACTOR_COMM_EXPORT msg_toAgentId_toUsages final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg.CommStackFrameElement.msg_toAgentId_toUsages) */ {
 public:
  inline msg_toAgentId_toUsages() : msg_toAgentId_toUsages(nullptr) {}
  ~msg_toAgentId_toUsages() override;
  explicit PROTOBUF_CONSTEXPR msg_toAgentId_toUsages(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  msg_toAgentId_toUsages(const msg_toAgentId_toUsages& from);
  msg_toAgentId_toUsages(msg_toAgentId_toUsages&& from) noexcept
    : msg_toAgentId_toUsages() {
    *this = ::std::move(from);
  }

  inline msg_toAgentId_toUsages& operator=(const msg_toAgentId_toUsages& from) {
    CopyFrom(from);
    return *this;
  }
  inline msg_toAgentId_toUsages& operator=(msg_toAgentId_toUsages&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const msg_toAgentId_toUsages& default_instance() {
    return *internal_default_instance();
  }
  static inline const msg_toAgentId_toUsages* internal_default_instance() {
    return reinterpret_cast<const msg_toAgentId_toUsages*>(
               &_msg_toAgentId_toUsages_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(msg_toAgentId_toUsages& a, msg_toAgentId_toUsages& b) {
    a.Swap(&b);
  }
  inline void Swap(msg_toAgentId_toUsages* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(msg_toAgentId_toUsages* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  msg_toAgentId_toUsages* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<msg_toAgentId_toUsages>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const msg_toAgentId_toUsages& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const msg_toAgentId_toUsages& from) {
    msg_toAgentId_toUsages::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(msg_toAgentId_toUsages* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg.CommStackFrameElement.msg_toAgentId_toUsages";
  }
  protected:
  explicit msg_toAgentId_toUsages(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kToUsagesFieldNumber = 2,
    kToAgentIdFieldNumber = 1,
  };
  // string toUsages = 2;
  void clear_tousages();
  const std::string& tousages() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_tousages(ArgT0&& arg0, ArgT... args);
  std::string* mutable_tousages();
  PROTOBUF_NODISCARD std::string* release_tousages();
  void set_allocated_tousages(std::string* tousages);
  private:
  const std::string& _internal_tousages() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_tousages(const std::string& value);
  std::string* _internal_mutable_tousages();
  public:

  // uint64 toAgentId = 1;
  void clear_toagentid();
  uint64_t toagentid() const;
  void set_toagentid(uint64_t value);
  private:
  uint64_t _internal_toagentid() const;
  void _internal_set_toagentid(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:msg.CommStackFrameElement.msg_toAgentId_toUsages)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr tousages_;
    uint64_t toagentid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_CommStackFrameElement_2eproto;
};
// -------------------------------------------------------------------

class GAEACTOR_COMM_EXPORT msg_CommStackFrameElement final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg.CommStackFrameElement.msg_CommStackFrameElement) */ {
 public:
  inline msg_CommStackFrameElement() : msg_CommStackFrameElement(nullptr) {}
  ~msg_CommStackFrameElement() override;
  explicit PROTOBUF_CONSTEXPR msg_CommStackFrameElement(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  msg_CommStackFrameElement(const msg_CommStackFrameElement& from);
  msg_CommStackFrameElement(msg_CommStackFrameElement&& from) noexcept
    : msg_CommStackFrameElement() {
    *this = ::std::move(from);
  }

  inline msg_CommStackFrameElement& operator=(const msg_CommStackFrameElement& from) {
    CopyFrom(from);
    return *this;
  }
  inline msg_CommStackFrameElement& operator=(msg_CommStackFrameElement&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const msg_CommStackFrameElement& default_instance() {
    return *internal_default_instance();
  }
  static inline const msg_CommStackFrameElement* internal_default_instance() {
    return reinterpret_cast<const msg_CommStackFrameElement*>(
               &_msg_CommStackFrameElement_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(msg_CommStackFrameElement& a, msg_CommStackFrameElement& b) {
    a.Swap(&b);
  }
  inline void Swap(msg_CommStackFrameElement* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(msg_CommStackFrameElement* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  msg_CommStackFrameElement* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<msg_CommStackFrameElement>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const msg_CommStackFrameElement& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const msg_CommStackFrameElement& from) {
    msg_CommStackFrameElement::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(msg_CommStackFrameElement* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg.CommStackFrameElement.msg_CommStackFrameElement";
  }
  protected:
  explicit msg_CommStackFrameElement(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRefBitsFieldNumber = 4,
    kRefSymbolsFieldNumber = 5,
    kToAgentIdToUsagesFieldNumber = 10,
    kEngineKeyedNameFieldNumber = 1,
    kFromUsageFieldNumber = 9,
    kFrameHexTxtFieldNumber = 11,
    kSnrFieldNumber = 2,
    kSinrFieldNumber = 3,
    kBerFieldNumber = 6,
    kFerFieldNumber = 7,
    kFromAgentIdFieldNumber = 8,
    kFramePackIndexFieldNumber = 12,
    kFrameTimestampFieldNumber = 13,
  };
  // repeated int32 ref_bits = 4;
  int ref_bits_size() const;
  private:
  int _internal_ref_bits_size() const;
  public:
  void clear_ref_bits();
  private:
  int32_t _internal_ref_bits(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_ref_bits() const;
  void _internal_add_ref_bits(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_ref_bits();
  public:
  int32_t ref_bits(int index) const;
  void set_ref_bits(int index, int32_t value);
  void add_ref_bits(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      ref_bits() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_ref_bits();

  // repeated float ref_symbols = 5;
  int ref_symbols_size() const;
  private:
  int _internal_ref_symbols_size() const;
  public:
  void clear_ref_symbols();
  private:
  float _internal_ref_symbols(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_ref_symbols() const;
  void _internal_add_ref_symbols(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_ref_symbols();
  public:
  float ref_symbols(int index) const;
  void set_ref_symbols(int index, float value);
  void add_ref_symbols(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      ref_symbols() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_ref_symbols();

  // repeated .msg.CommStackFrameElement.msg_toAgentId_toUsages toAgentId_toUsages = 10;
  int toagentid_tousages_size() const;
  private:
  int _internal_toagentid_tousages_size() const;
  public:
  void clear_toagentid_tousages();
  ::msg::CommStackFrameElement::msg_toAgentId_toUsages* mutable_toagentid_tousages(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::msg::CommStackFrameElement::msg_toAgentId_toUsages >*
      mutable_toagentid_tousages();
  private:
  const ::msg::CommStackFrameElement::msg_toAgentId_toUsages& _internal_toagentid_tousages(int index) const;
  ::msg::CommStackFrameElement::msg_toAgentId_toUsages* _internal_add_toagentid_tousages();
  public:
  const ::msg::CommStackFrameElement::msg_toAgentId_toUsages& toagentid_tousages(int index) const;
  ::msg::CommStackFrameElement::msg_toAgentId_toUsages* add_toagentid_tousages();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::msg::CommStackFrameElement::msg_toAgentId_toUsages >&
      toagentid_tousages() const;

  // string engine_keyed_name = 1;
  void clear_engine_keyed_name();
  const std::string& engine_keyed_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_engine_keyed_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_engine_keyed_name();
  PROTOBUF_NODISCARD std::string* release_engine_keyed_name();
  void set_allocated_engine_keyed_name(std::string* engine_keyed_name);
  private:
  const std::string& _internal_engine_keyed_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_engine_keyed_name(const std::string& value);
  std::string* _internal_mutable_engine_keyed_name();
  public:

  // string fromUsage = 9;
  void clear_fromusage();
  const std::string& fromusage() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_fromusage(ArgT0&& arg0, ArgT... args);
  std::string* mutable_fromusage();
  PROTOBUF_NODISCARD std::string* release_fromusage();
  void set_allocated_fromusage(std::string* fromusage);
  private:
  const std::string& _internal_fromusage() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_fromusage(const std::string& value);
  std::string* _internal_mutable_fromusage();
  public:

  // string frameHexTxt = 11;
  void clear_framehextxt();
  const std::string& framehextxt() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_framehextxt(ArgT0&& arg0, ArgT... args);
  std::string* mutable_framehextxt();
  PROTOBUF_NODISCARD std::string* release_framehextxt();
  void set_allocated_framehextxt(std::string* framehextxt);
  private:
  const std::string& _internal_framehextxt() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_framehextxt(const std::string& value);
  std::string* _internal_mutable_framehextxt();
  public:

  // float snr = 2;
  void clear_snr();
  float snr() const;
  void set_snr(float value);
  private:
  float _internal_snr() const;
  void _internal_set_snr(float value);
  public:

  // float sinr = 3;
  void clear_sinr();
  float sinr() const;
  void set_sinr(float value);
  private:
  float _internal_sinr() const;
  void _internal_set_sinr(float value);
  public:

  // float ber = 6;
  void clear_ber();
  float ber() const;
  void set_ber(float value);
  private:
  float _internal_ber() const;
  void _internal_set_ber(float value);
  public:

  // float fer = 7;
  void clear_fer();
  float fer() const;
  void set_fer(float value);
  private:
  float _internal_fer() const;
  void _internal_set_fer(float value);
  public:

  // uint64 fromAgentId = 8;
  void clear_fromagentid();
  uint64_t fromagentid() const;
  void set_fromagentid(uint64_t value);
  private:
  uint64_t _internal_fromagentid() const;
  void _internal_set_fromagentid(uint64_t value);
  public:

  // uint64 frame_pack_index = 12;
  void clear_frame_pack_index();
  uint64_t frame_pack_index() const;
  void set_frame_pack_index(uint64_t value);
  private:
  uint64_t _internal_frame_pack_index() const;
  void _internal_set_frame_pack_index(uint64_t value);
  public:

  // uint64 frame_timestamp = 13;
  void clear_frame_timestamp();
  uint64_t frame_timestamp() const;
  void set_frame_timestamp(uint64_t value);
  private:
  uint64_t _internal_frame_timestamp() const;
  void _internal_set_frame_timestamp(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:msg.CommStackFrameElement.msg_CommStackFrameElement)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > ref_bits_;
    mutable std::atomic<int> _ref_bits_cached_byte_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > ref_symbols_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::msg::CommStackFrameElement::msg_toAgentId_toUsages > toagentid_tousages_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr engine_keyed_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr fromusage_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr framehextxt_;
    float snr_;
    float sinr_;
    float ber_;
    float fer_;
    uint64_t fromagentid_;
    uint64_t frame_pack_index_;
    uint64_t frame_timestamp_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_CommStackFrameElement_2eproto;
};
// -------------------------------------------------------------------

class GAEACTOR_COMM_EXPORT msg_CommStackFrameElement_Array final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg.CommStackFrameElement.msg_CommStackFrameElement_Array) */ {
 public:
  inline msg_CommStackFrameElement_Array() : msg_CommStackFrameElement_Array(nullptr) {}
  ~msg_CommStackFrameElement_Array() override;
  explicit PROTOBUF_CONSTEXPR msg_CommStackFrameElement_Array(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  msg_CommStackFrameElement_Array(const msg_CommStackFrameElement_Array& from);
  msg_CommStackFrameElement_Array(msg_CommStackFrameElement_Array&& from) noexcept
    : msg_CommStackFrameElement_Array() {
    *this = ::std::move(from);
  }

  inline msg_CommStackFrameElement_Array& operator=(const msg_CommStackFrameElement_Array& from) {
    CopyFrom(from);
    return *this;
  }
  inline msg_CommStackFrameElement_Array& operator=(msg_CommStackFrameElement_Array&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const msg_CommStackFrameElement_Array& default_instance() {
    return *internal_default_instance();
  }
  static inline const msg_CommStackFrameElement_Array* internal_default_instance() {
    return reinterpret_cast<const msg_CommStackFrameElement_Array*>(
               &_msg_CommStackFrameElement_Array_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(msg_CommStackFrameElement_Array& a, msg_CommStackFrameElement_Array& b) {
    a.Swap(&b);
  }
  inline void Swap(msg_CommStackFrameElement_Array* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(msg_CommStackFrameElement_Array* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  msg_CommStackFrameElement_Array* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<msg_CommStackFrameElement_Array>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const msg_CommStackFrameElement_Array& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const msg_CommStackFrameElement_Array& from) {
    msg_CommStackFrameElement_Array::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(msg_CommStackFrameElement_Array* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg.CommStackFrameElement.msg_CommStackFrameElement_Array";
  }
  protected:
  explicit msg_CommStackFrameElement_Array(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCommStackFrameElementsFieldNumber = 1,
  };
  // repeated .msg.CommStackFrameElement.msg_CommStackFrameElement commStackFrameElements = 1;
  int commstackframeelements_size() const;
  private:
  int _internal_commstackframeelements_size() const;
  public:
  void clear_commstackframeelements();
  ::msg::CommStackFrameElement::msg_CommStackFrameElement* mutable_commstackframeelements(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::msg::CommStackFrameElement::msg_CommStackFrameElement >*
      mutable_commstackframeelements();
  private:
  const ::msg::CommStackFrameElement::msg_CommStackFrameElement& _internal_commstackframeelements(int index) const;
  ::msg::CommStackFrameElement::msg_CommStackFrameElement* _internal_add_commstackframeelements();
  public:
  const ::msg::CommStackFrameElement::msg_CommStackFrameElement& commstackframeelements(int index) const;
  ::msg::CommStackFrameElement::msg_CommStackFrameElement* add_commstackframeelements();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::msg::CommStackFrameElement::msg_CommStackFrameElement >&
      commstackframeelements() const;

  // @@protoc_insertion_point(class_scope:msg.CommStackFrameElement.msg_CommStackFrameElement_Array)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::msg::CommStackFrameElement::msg_CommStackFrameElement > commstackframeelements_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_CommStackFrameElement_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// msg_toAgentId_toUsages

// uint64 toAgentId = 1;
inline void msg_toAgentId_toUsages::clear_toagentid() {
  _impl_.toagentid_ = uint64_t{0u};
}
inline uint64_t msg_toAgentId_toUsages::_internal_toagentid() const {
  return _impl_.toagentid_;
}
inline uint64_t msg_toAgentId_toUsages::toagentid() const {
  // @@protoc_insertion_point(field_get:msg.CommStackFrameElement.msg_toAgentId_toUsages.toAgentId)
  return _internal_toagentid();
}
inline void msg_toAgentId_toUsages::_internal_set_toagentid(uint64_t value) {
  
  _impl_.toagentid_ = value;
}
inline void msg_toAgentId_toUsages::set_toagentid(uint64_t value) {
  _internal_set_toagentid(value);
  // @@protoc_insertion_point(field_set:msg.CommStackFrameElement.msg_toAgentId_toUsages.toAgentId)
}

// string toUsages = 2;
inline void msg_toAgentId_toUsages::clear_tousages() {
  _impl_.tousages_.ClearToEmpty();
}
inline const std::string& msg_toAgentId_toUsages::tousages() const {
  // @@protoc_insertion_point(field_get:msg.CommStackFrameElement.msg_toAgentId_toUsages.toUsages)
  return _internal_tousages();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void msg_toAgentId_toUsages::set_tousages(ArgT0&& arg0, ArgT... args) {
 
 _impl_.tousages_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg.CommStackFrameElement.msg_toAgentId_toUsages.toUsages)
}
inline std::string* msg_toAgentId_toUsages::mutable_tousages() {
  std::string* _s = _internal_mutable_tousages();
  // @@protoc_insertion_point(field_mutable:msg.CommStackFrameElement.msg_toAgentId_toUsages.toUsages)
  return _s;
}
inline const std::string& msg_toAgentId_toUsages::_internal_tousages() const {
  return _impl_.tousages_.Get();
}
inline void msg_toAgentId_toUsages::_internal_set_tousages(const std::string& value) {
  
  _impl_.tousages_.Set(value, GetArenaForAllocation());
}
inline std::string* msg_toAgentId_toUsages::_internal_mutable_tousages() {
  
  return _impl_.tousages_.Mutable(GetArenaForAllocation());
}
inline std::string* msg_toAgentId_toUsages::release_tousages() {
  // @@protoc_insertion_point(field_release:msg.CommStackFrameElement.msg_toAgentId_toUsages.toUsages)
  return _impl_.tousages_.Release();
}
inline void msg_toAgentId_toUsages::set_allocated_tousages(std::string* tousages) {
  if (tousages != nullptr) {
    
  } else {
    
  }
  _impl_.tousages_.SetAllocated(tousages, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.tousages_.IsDefault()) {
    _impl_.tousages_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg.CommStackFrameElement.msg_toAgentId_toUsages.toUsages)
}

// -------------------------------------------------------------------

// msg_CommStackFrameElement

// string engine_keyed_name = 1;
inline void msg_CommStackFrameElement::clear_engine_keyed_name() {
  _impl_.engine_keyed_name_.ClearToEmpty();
}
inline const std::string& msg_CommStackFrameElement::engine_keyed_name() const {
  // @@protoc_insertion_point(field_get:msg.CommStackFrameElement.msg_CommStackFrameElement.engine_keyed_name)
  return _internal_engine_keyed_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void msg_CommStackFrameElement::set_engine_keyed_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.engine_keyed_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg.CommStackFrameElement.msg_CommStackFrameElement.engine_keyed_name)
}
inline std::string* msg_CommStackFrameElement::mutable_engine_keyed_name() {
  std::string* _s = _internal_mutable_engine_keyed_name();
  // @@protoc_insertion_point(field_mutable:msg.CommStackFrameElement.msg_CommStackFrameElement.engine_keyed_name)
  return _s;
}
inline const std::string& msg_CommStackFrameElement::_internal_engine_keyed_name() const {
  return _impl_.engine_keyed_name_.Get();
}
inline void msg_CommStackFrameElement::_internal_set_engine_keyed_name(const std::string& value) {
  
  _impl_.engine_keyed_name_.Set(value, GetArenaForAllocation());
}
inline std::string* msg_CommStackFrameElement::_internal_mutable_engine_keyed_name() {
  
  return _impl_.engine_keyed_name_.Mutable(GetArenaForAllocation());
}
inline std::string* msg_CommStackFrameElement::release_engine_keyed_name() {
  // @@protoc_insertion_point(field_release:msg.CommStackFrameElement.msg_CommStackFrameElement.engine_keyed_name)
  return _impl_.engine_keyed_name_.Release();
}
inline void msg_CommStackFrameElement::set_allocated_engine_keyed_name(std::string* engine_keyed_name) {
  if (engine_keyed_name != nullptr) {
    
  } else {
    
  }
  _impl_.engine_keyed_name_.SetAllocated(engine_keyed_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.engine_keyed_name_.IsDefault()) {
    _impl_.engine_keyed_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg.CommStackFrameElement.msg_CommStackFrameElement.engine_keyed_name)
}

// float snr = 2;
inline void msg_CommStackFrameElement::clear_snr() {
  _impl_.snr_ = 0;
}
inline float msg_CommStackFrameElement::_internal_snr() const {
  return _impl_.snr_;
}
inline float msg_CommStackFrameElement::snr() const {
  // @@protoc_insertion_point(field_get:msg.CommStackFrameElement.msg_CommStackFrameElement.snr)
  return _internal_snr();
}
inline void msg_CommStackFrameElement::_internal_set_snr(float value) {
  
  _impl_.snr_ = value;
}
inline void msg_CommStackFrameElement::set_snr(float value) {
  _internal_set_snr(value);
  // @@protoc_insertion_point(field_set:msg.CommStackFrameElement.msg_CommStackFrameElement.snr)
}

// float sinr = 3;
inline void msg_CommStackFrameElement::clear_sinr() {
  _impl_.sinr_ = 0;
}
inline float msg_CommStackFrameElement::_internal_sinr() const {
  return _impl_.sinr_;
}
inline float msg_CommStackFrameElement::sinr() const {
  // @@protoc_insertion_point(field_get:msg.CommStackFrameElement.msg_CommStackFrameElement.sinr)
  return _internal_sinr();
}
inline void msg_CommStackFrameElement::_internal_set_sinr(float value) {
  
  _impl_.sinr_ = value;
}
inline void msg_CommStackFrameElement::set_sinr(float value) {
  _internal_set_sinr(value);
  // @@protoc_insertion_point(field_set:msg.CommStackFrameElement.msg_CommStackFrameElement.sinr)
}

// repeated int32 ref_bits = 4;
inline int msg_CommStackFrameElement::_internal_ref_bits_size() const {
  return _impl_.ref_bits_.size();
}
inline int msg_CommStackFrameElement::ref_bits_size() const {
  return _internal_ref_bits_size();
}
inline void msg_CommStackFrameElement::clear_ref_bits() {
  _impl_.ref_bits_.Clear();
}
inline int32_t msg_CommStackFrameElement::_internal_ref_bits(int index) const {
  return _impl_.ref_bits_.Get(index);
}
inline int32_t msg_CommStackFrameElement::ref_bits(int index) const {
  // @@protoc_insertion_point(field_get:msg.CommStackFrameElement.msg_CommStackFrameElement.ref_bits)
  return _internal_ref_bits(index);
}
inline void msg_CommStackFrameElement::set_ref_bits(int index, int32_t value) {
  _impl_.ref_bits_.Set(index, value);
  // @@protoc_insertion_point(field_set:msg.CommStackFrameElement.msg_CommStackFrameElement.ref_bits)
}
inline void msg_CommStackFrameElement::_internal_add_ref_bits(int32_t value) {
  _impl_.ref_bits_.Add(value);
}
inline void msg_CommStackFrameElement::add_ref_bits(int32_t value) {
  _internal_add_ref_bits(value);
  // @@protoc_insertion_point(field_add:msg.CommStackFrameElement.msg_CommStackFrameElement.ref_bits)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
msg_CommStackFrameElement::_internal_ref_bits() const {
  return _impl_.ref_bits_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
msg_CommStackFrameElement::ref_bits() const {
  // @@protoc_insertion_point(field_list:msg.CommStackFrameElement.msg_CommStackFrameElement.ref_bits)
  return _internal_ref_bits();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
msg_CommStackFrameElement::_internal_mutable_ref_bits() {
  return &_impl_.ref_bits_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
msg_CommStackFrameElement::mutable_ref_bits() {
  // @@protoc_insertion_point(field_mutable_list:msg.CommStackFrameElement.msg_CommStackFrameElement.ref_bits)
  return _internal_mutable_ref_bits();
}

// repeated float ref_symbols = 5;
inline int msg_CommStackFrameElement::_internal_ref_symbols_size() const {
  return _impl_.ref_symbols_.size();
}
inline int msg_CommStackFrameElement::ref_symbols_size() const {
  return _internal_ref_symbols_size();
}
inline void msg_CommStackFrameElement::clear_ref_symbols() {
  _impl_.ref_symbols_.Clear();
}
inline float msg_CommStackFrameElement::_internal_ref_symbols(int index) const {
  return _impl_.ref_symbols_.Get(index);
}
inline float msg_CommStackFrameElement::ref_symbols(int index) const {
  // @@protoc_insertion_point(field_get:msg.CommStackFrameElement.msg_CommStackFrameElement.ref_symbols)
  return _internal_ref_symbols(index);
}
inline void msg_CommStackFrameElement::set_ref_symbols(int index, float value) {
  _impl_.ref_symbols_.Set(index, value);
  // @@protoc_insertion_point(field_set:msg.CommStackFrameElement.msg_CommStackFrameElement.ref_symbols)
}
inline void msg_CommStackFrameElement::_internal_add_ref_symbols(float value) {
  _impl_.ref_symbols_.Add(value);
}
inline void msg_CommStackFrameElement::add_ref_symbols(float value) {
  _internal_add_ref_symbols(value);
  // @@protoc_insertion_point(field_add:msg.CommStackFrameElement.msg_CommStackFrameElement.ref_symbols)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
msg_CommStackFrameElement::_internal_ref_symbols() const {
  return _impl_.ref_symbols_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
msg_CommStackFrameElement::ref_symbols() const {
  // @@protoc_insertion_point(field_list:msg.CommStackFrameElement.msg_CommStackFrameElement.ref_symbols)
  return _internal_ref_symbols();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
msg_CommStackFrameElement::_internal_mutable_ref_symbols() {
  return &_impl_.ref_symbols_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
msg_CommStackFrameElement::mutable_ref_symbols() {
  // @@protoc_insertion_point(field_mutable_list:msg.CommStackFrameElement.msg_CommStackFrameElement.ref_symbols)
  return _internal_mutable_ref_symbols();
}

// float ber = 6;
inline void msg_CommStackFrameElement::clear_ber() {
  _impl_.ber_ = 0;
}
inline float msg_CommStackFrameElement::_internal_ber() const {
  return _impl_.ber_;
}
inline float msg_CommStackFrameElement::ber() const {
  // @@protoc_insertion_point(field_get:msg.CommStackFrameElement.msg_CommStackFrameElement.ber)
  return _internal_ber();
}
inline void msg_CommStackFrameElement::_internal_set_ber(float value) {
  
  _impl_.ber_ = value;
}
inline void msg_CommStackFrameElement::set_ber(float value) {
  _internal_set_ber(value);
  // @@protoc_insertion_point(field_set:msg.CommStackFrameElement.msg_CommStackFrameElement.ber)
}

// float fer = 7;
inline void msg_CommStackFrameElement::clear_fer() {
  _impl_.fer_ = 0;
}
inline float msg_CommStackFrameElement::_internal_fer() const {
  return _impl_.fer_;
}
inline float msg_CommStackFrameElement::fer() const {
  // @@protoc_insertion_point(field_get:msg.CommStackFrameElement.msg_CommStackFrameElement.fer)
  return _internal_fer();
}
inline void msg_CommStackFrameElement::_internal_set_fer(float value) {
  
  _impl_.fer_ = value;
}
inline void msg_CommStackFrameElement::set_fer(float value) {
  _internal_set_fer(value);
  // @@protoc_insertion_point(field_set:msg.CommStackFrameElement.msg_CommStackFrameElement.fer)
}

// uint64 fromAgentId = 8;
inline void msg_CommStackFrameElement::clear_fromagentid() {
  _impl_.fromagentid_ = uint64_t{0u};
}
inline uint64_t msg_CommStackFrameElement::_internal_fromagentid() const {
  return _impl_.fromagentid_;
}
inline uint64_t msg_CommStackFrameElement::fromagentid() const {
  // @@protoc_insertion_point(field_get:msg.CommStackFrameElement.msg_CommStackFrameElement.fromAgentId)
  return _internal_fromagentid();
}
inline void msg_CommStackFrameElement::_internal_set_fromagentid(uint64_t value) {
  
  _impl_.fromagentid_ = value;
}
inline void msg_CommStackFrameElement::set_fromagentid(uint64_t value) {
  _internal_set_fromagentid(value);
  // @@protoc_insertion_point(field_set:msg.CommStackFrameElement.msg_CommStackFrameElement.fromAgentId)
}

// string fromUsage = 9;
inline void msg_CommStackFrameElement::clear_fromusage() {
  _impl_.fromusage_.ClearToEmpty();
}
inline const std::string& msg_CommStackFrameElement::fromusage() const {
  // @@protoc_insertion_point(field_get:msg.CommStackFrameElement.msg_CommStackFrameElement.fromUsage)
  return _internal_fromusage();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void msg_CommStackFrameElement::set_fromusage(ArgT0&& arg0, ArgT... args) {
 
 _impl_.fromusage_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg.CommStackFrameElement.msg_CommStackFrameElement.fromUsage)
}
inline std::string* msg_CommStackFrameElement::mutable_fromusage() {
  std::string* _s = _internal_mutable_fromusage();
  // @@protoc_insertion_point(field_mutable:msg.CommStackFrameElement.msg_CommStackFrameElement.fromUsage)
  return _s;
}
inline const std::string& msg_CommStackFrameElement::_internal_fromusage() const {
  return _impl_.fromusage_.Get();
}
inline void msg_CommStackFrameElement::_internal_set_fromusage(const std::string& value) {
  
  _impl_.fromusage_.Set(value, GetArenaForAllocation());
}
inline std::string* msg_CommStackFrameElement::_internal_mutable_fromusage() {
  
  return _impl_.fromusage_.Mutable(GetArenaForAllocation());
}
inline std::string* msg_CommStackFrameElement::release_fromusage() {
  // @@protoc_insertion_point(field_release:msg.CommStackFrameElement.msg_CommStackFrameElement.fromUsage)
  return _impl_.fromusage_.Release();
}
inline void msg_CommStackFrameElement::set_allocated_fromusage(std::string* fromusage) {
  if (fromusage != nullptr) {
    
  } else {
    
  }
  _impl_.fromusage_.SetAllocated(fromusage, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.fromusage_.IsDefault()) {
    _impl_.fromusage_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg.CommStackFrameElement.msg_CommStackFrameElement.fromUsage)
}

// repeated .msg.CommStackFrameElement.msg_toAgentId_toUsages toAgentId_toUsages = 10;
inline int msg_CommStackFrameElement::_internal_toagentid_tousages_size() const {
  return _impl_.toagentid_tousages_.size();
}
inline int msg_CommStackFrameElement::toagentid_tousages_size() const {
  return _internal_toagentid_tousages_size();
}
inline void msg_CommStackFrameElement::clear_toagentid_tousages() {
  _impl_.toagentid_tousages_.Clear();
}
inline ::msg::CommStackFrameElement::msg_toAgentId_toUsages* msg_CommStackFrameElement::mutable_toagentid_tousages(int index) {
  // @@protoc_insertion_point(field_mutable:msg.CommStackFrameElement.msg_CommStackFrameElement.toAgentId_toUsages)
  return _impl_.toagentid_tousages_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::msg::CommStackFrameElement::msg_toAgentId_toUsages >*
msg_CommStackFrameElement::mutable_toagentid_tousages() {
  // @@protoc_insertion_point(field_mutable_list:msg.CommStackFrameElement.msg_CommStackFrameElement.toAgentId_toUsages)
  return &_impl_.toagentid_tousages_;
}
inline const ::msg::CommStackFrameElement::msg_toAgentId_toUsages& msg_CommStackFrameElement::_internal_toagentid_tousages(int index) const {
  return _impl_.toagentid_tousages_.Get(index);
}
inline const ::msg::CommStackFrameElement::msg_toAgentId_toUsages& msg_CommStackFrameElement::toagentid_tousages(int index) const {
  // @@protoc_insertion_point(field_get:msg.CommStackFrameElement.msg_CommStackFrameElement.toAgentId_toUsages)
  return _internal_toagentid_tousages(index);
}
inline ::msg::CommStackFrameElement::msg_toAgentId_toUsages* msg_CommStackFrameElement::_internal_add_toagentid_tousages() {
  return _impl_.toagentid_tousages_.Add();
}
inline ::msg::CommStackFrameElement::msg_toAgentId_toUsages* msg_CommStackFrameElement::add_toagentid_tousages() {
  ::msg::CommStackFrameElement::msg_toAgentId_toUsages* _add = _internal_add_toagentid_tousages();
  // @@protoc_insertion_point(field_add:msg.CommStackFrameElement.msg_CommStackFrameElement.toAgentId_toUsages)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::msg::CommStackFrameElement::msg_toAgentId_toUsages >&
msg_CommStackFrameElement::toagentid_tousages() const {
  // @@protoc_insertion_point(field_list:msg.CommStackFrameElement.msg_CommStackFrameElement.toAgentId_toUsages)
  return _impl_.toagentid_tousages_;
}

// string frameHexTxt = 11;
inline void msg_CommStackFrameElement::clear_framehextxt() {
  _impl_.framehextxt_.ClearToEmpty();
}
inline const std::string& msg_CommStackFrameElement::framehextxt() const {
  // @@protoc_insertion_point(field_get:msg.CommStackFrameElement.msg_CommStackFrameElement.frameHexTxt)
  return _internal_framehextxt();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void msg_CommStackFrameElement::set_framehextxt(ArgT0&& arg0, ArgT... args) {
 
 _impl_.framehextxt_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg.CommStackFrameElement.msg_CommStackFrameElement.frameHexTxt)
}
inline std::string* msg_CommStackFrameElement::mutable_framehextxt() {
  std::string* _s = _internal_mutable_framehextxt();
  // @@protoc_insertion_point(field_mutable:msg.CommStackFrameElement.msg_CommStackFrameElement.frameHexTxt)
  return _s;
}
inline const std::string& msg_CommStackFrameElement::_internal_framehextxt() const {
  return _impl_.framehextxt_.Get();
}
inline void msg_CommStackFrameElement::_internal_set_framehextxt(const std::string& value) {
  
  _impl_.framehextxt_.Set(value, GetArenaForAllocation());
}
inline std::string* msg_CommStackFrameElement::_internal_mutable_framehextxt() {
  
  return _impl_.framehextxt_.Mutable(GetArenaForAllocation());
}
inline std::string* msg_CommStackFrameElement::release_framehextxt() {
  // @@protoc_insertion_point(field_release:msg.CommStackFrameElement.msg_CommStackFrameElement.frameHexTxt)
  return _impl_.framehextxt_.Release();
}
inline void msg_CommStackFrameElement::set_allocated_framehextxt(std::string* framehextxt) {
  if (framehextxt != nullptr) {
    
  } else {
    
  }
  _impl_.framehextxt_.SetAllocated(framehextxt, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.framehextxt_.IsDefault()) {
    _impl_.framehextxt_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg.CommStackFrameElement.msg_CommStackFrameElement.frameHexTxt)
}

// uint64 frame_pack_index = 12;
inline void msg_CommStackFrameElement::clear_frame_pack_index() {
  _impl_.frame_pack_index_ = uint64_t{0u};
}
inline uint64_t msg_CommStackFrameElement::_internal_frame_pack_index() const {
  return _impl_.frame_pack_index_;
}
inline uint64_t msg_CommStackFrameElement::frame_pack_index() const {
  // @@protoc_insertion_point(field_get:msg.CommStackFrameElement.msg_CommStackFrameElement.frame_pack_index)
  return _internal_frame_pack_index();
}
inline void msg_CommStackFrameElement::_internal_set_frame_pack_index(uint64_t value) {
  
  _impl_.frame_pack_index_ = value;
}
inline void msg_CommStackFrameElement::set_frame_pack_index(uint64_t value) {
  _internal_set_frame_pack_index(value);
  // @@protoc_insertion_point(field_set:msg.CommStackFrameElement.msg_CommStackFrameElement.frame_pack_index)
}

// uint64 frame_timestamp = 13;
inline void msg_CommStackFrameElement::clear_frame_timestamp() {
  _impl_.frame_timestamp_ = uint64_t{0u};
}
inline uint64_t msg_CommStackFrameElement::_internal_frame_timestamp() const {
  return _impl_.frame_timestamp_;
}
inline uint64_t msg_CommStackFrameElement::frame_timestamp() const {
  // @@protoc_insertion_point(field_get:msg.CommStackFrameElement.msg_CommStackFrameElement.frame_timestamp)
  return _internal_frame_timestamp();
}
inline void msg_CommStackFrameElement::_internal_set_frame_timestamp(uint64_t value) {
  
  _impl_.frame_timestamp_ = value;
}
inline void msg_CommStackFrameElement::set_frame_timestamp(uint64_t value) {
  _internal_set_frame_timestamp(value);
  // @@protoc_insertion_point(field_set:msg.CommStackFrameElement.msg_CommStackFrameElement.frame_timestamp)
}

// -------------------------------------------------------------------

// msg_CommStackFrameElement_Array

// repeated .msg.CommStackFrameElement.msg_CommStackFrameElement commStackFrameElements = 1;
inline int msg_CommStackFrameElement_Array::_internal_commstackframeelements_size() const {
  return _impl_.commstackframeelements_.size();
}
inline int msg_CommStackFrameElement_Array::commstackframeelements_size() const {
  return _internal_commstackframeelements_size();
}
inline void msg_CommStackFrameElement_Array::clear_commstackframeelements() {
  _impl_.commstackframeelements_.Clear();
}
inline ::msg::CommStackFrameElement::msg_CommStackFrameElement* msg_CommStackFrameElement_Array::mutable_commstackframeelements(int index) {
  // @@protoc_insertion_point(field_mutable:msg.CommStackFrameElement.msg_CommStackFrameElement_Array.commStackFrameElements)
  return _impl_.commstackframeelements_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::msg::CommStackFrameElement::msg_CommStackFrameElement >*
msg_CommStackFrameElement_Array::mutable_commstackframeelements() {
  // @@protoc_insertion_point(field_mutable_list:msg.CommStackFrameElement.msg_CommStackFrameElement_Array.commStackFrameElements)
  return &_impl_.commstackframeelements_;
}
inline const ::msg::CommStackFrameElement::msg_CommStackFrameElement& msg_CommStackFrameElement_Array::_internal_commstackframeelements(int index) const {
  return _impl_.commstackframeelements_.Get(index);
}
inline const ::msg::CommStackFrameElement::msg_CommStackFrameElement& msg_CommStackFrameElement_Array::commstackframeelements(int index) const {
  // @@protoc_insertion_point(field_get:msg.CommStackFrameElement.msg_CommStackFrameElement_Array.commStackFrameElements)
  return _internal_commstackframeelements(index);
}
inline ::msg::CommStackFrameElement::msg_CommStackFrameElement* msg_CommStackFrameElement_Array::_internal_add_commstackframeelements() {
  return _impl_.commstackframeelements_.Add();
}
inline ::msg::CommStackFrameElement::msg_CommStackFrameElement* msg_CommStackFrameElement_Array::add_commstackframeelements() {
  ::msg::CommStackFrameElement::msg_CommStackFrameElement* _add = _internal_add_commstackframeelements();
  // @@protoc_insertion_point(field_add:msg.CommStackFrameElement.msg_CommStackFrameElement_Array.commStackFrameElements)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::msg::CommStackFrameElement::msg_CommStackFrameElement >&
msg_CommStackFrameElement_Array::commstackframeelements() const {
  // @@protoc_insertion_point(field_list:msg.CommStackFrameElement.msg_CommStackFrameElement_Array.commStackFrameElements)
  return _impl_.commstackframeelements_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace CommStackFrameElement
}  // namespace msg

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_CommStackFrameElement_2eproto
