// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MPARMotionInfo.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_MPARMotionInfo_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_MPARMotionInfo_2eproto

#include "gaeactor_comm_global.h"

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_MPARMotionInfo_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_MPARMotionInfo_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_MPARMotionInfo_2eproto;
namespace msg {
namespace MPARMotionInfo {
class msg_MPARMotionInfo;
struct msg_MPARMotionInfoDefaultTypeInternal;
extern msg_MPARMotionInfoDefaultTypeInternal _msg_MPARMotionInfo_default_instance_;
class msg_MPARMotionInfo_Array;
struct msg_MPARMotionInfo_ArrayDefaultTypeInternal;
extern msg_MPARMotionInfo_ArrayDefaultTypeInternal _msg_MPARMotionInfo_Array_default_instance_;
}  // namespace MPARMotionInfo
}  // namespace msg
PROTOBUF_NAMESPACE_OPEN
template<> ::msg::MPARMotionInfo::msg_MPARMotionInfo* Arena::CreateMaybeMessage<::msg::MPARMotionInfo::msg_MPARMotionInfo>(Arena*);
template<> ::msg::MPARMotionInfo::msg_MPARMotionInfo_Array* Arena::CreateMaybeMessage<::msg::MPARMotionInfo::msg_MPARMotionInfo_Array>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace msg {
namespace MPARMotionInfo {

// ===================================================================

class GAEACTOR_COMM_EXPORT msg_MPARMotionInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg.MPARMotionInfo.msg_MPARMotionInfo) */ {
 public:
  inline msg_MPARMotionInfo() : msg_MPARMotionInfo(nullptr) {}
  ~msg_MPARMotionInfo() override;
  explicit PROTOBUF_CONSTEXPR msg_MPARMotionInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  msg_MPARMotionInfo(const msg_MPARMotionInfo& from);
  msg_MPARMotionInfo(msg_MPARMotionInfo&& from) noexcept
    : msg_MPARMotionInfo() {
    *this = ::std::move(from);
  }

  inline msg_MPARMotionInfo& operator=(const msg_MPARMotionInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline msg_MPARMotionInfo& operator=(msg_MPARMotionInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const msg_MPARMotionInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const msg_MPARMotionInfo* internal_default_instance() {
    return reinterpret_cast<const msg_MPARMotionInfo*>(
               &_msg_MPARMotionInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(msg_MPARMotionInfo& a, msg_MPARMotionInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(msg_MPARMotionInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(msg_MPARMotionInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  msg_MPARMotionInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<msg_MPARMotionInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const msg_MPARMotionInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const msg_MPARMotionInfo& from) {
    msg_MPARMotionInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(msg_MPARMotionInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg.MPARMotionInfo.msg_MPARMotionInfo";
  }
  protected:
  explicit msg_MPARMotionInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTargetIDFieldNumber = 8,
    kTargetPosXFieldNumber = 1,
    kTargetPosYFieldNumber = 2,
    kTargetPosZFieldNumber = 3,
    kTargetVelXFieldNumber = 4,
    kTargetVelYFieldNumber = 5,
    kTargetVelZFieldNumber = 6,
    kTargetRCSFieldNumber = 7,
  };
  // string TargetID = 8;
  void clear_targetid();
  const std::string& targetid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_targetid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_targetid();
  PROTOBUF_NODISCARD std::string* release_targetid();
  void set_allocated_targetid(std::string* targetid);
  private:
  const std::string& _internal_targetid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_targetid(const std::string& value);
  std::string* _internal_mutable_targetid();
  public:

  // double TargetPosX = 1;
  void clear_targetposx();
  double targetposx() const;
  void set_targetposx(double value);
  private:
  double _internal_targetposx() const;
  void _internal_set_targetposx(double value);
  public:

  // double TargetPosY = 2;
  void clear_targetposy();
  double targetposy() const;
  void set_targetposy(double value);
  private:
  double _internal_targetposy() const;
  void _internal_set_targetposy(double value);
  public:

  // double TargetPosZ = 3;
  void clear_targetposz();
  double targetposz() const;
  void set_targetposz(double value);
  private:
  double _internal_targetposz() const;
  void _internal_set_targetposz(double value);
  public:

  // double TargetVelX = 4;
  void clear_targetvelx();
  double targetvelx() const;
  void set_targetvelx(double value);
  private:
  double _internal_targetvelx() const;
  void _internal_set_targetvelx(double value);
  public:

  // double TargetVelY = 5;
  void clear_targetvely();
  double targetvely() const;
  void set_targetvely(double value);
  private:
  double _internal_targetvely() const;
  void _internal_set_targetvely(double value);
  public:

  // double TargetVelZ = 6;
  void clear_targetvelz();
  double targetvelz() const;
  void set_targetvelz(double value);
  private:
  double _internal_targetvelz() const;
  void _internal_set_targetvelz(double value);
  public:

  // int32 TargetRCS = 7;
  void clear_targetrcs();
  int32_t targetrcs() const;
  void set_targetrcs(int32_t value);
  private:
  int32_t _internal_targetrcs() const;
  void _internal_set_targetrcs(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:msg.MPARMotionInfo.msg_MPARMotionInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr targetid_;
    double targetposx_;
    double targetposy_;
    double targetposz_;
    double targetvelx_;
    double targetvely_;
    double targetvelz_;
    int32_t targetrcs_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_MPARMotionInfo_2eproto;
};
// -------------------------------------------------------------------

class GAEACTOR_COMM_EXPORT msg_MPARMotionInfo_Array final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg.MPARMotionInfo.msg_MPARMotionInfo_Array) */ {
 public:
  inline msg_MPARMotionInfo_Array() : msg_MPARMotionInfo_Array(nullptr) {}
  ~msg_MPARMotionInfo_Array() override;
  explicit PROTOBUF_CONSTEXPR msg_MPARMotionInfo_Array(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  msg_MPARMotionInfo_Array(const msg_MPARMotionInfo_Array& from);
  msg_MPARMotionInfo_Array(msg_MPARMotionInfo_Array&& from) noexcept
    : msg_MPARMotionInfo_Array() {
    *this = ::std::move(from);
  }

  inline msg_MPARMotionInfo_Array& operator=(const msg_MPARMotionInfo_Array& from) {
    CopyFrom(from);
    return *this;
  }
  inline msg_MPARMotionInfo_Array& operator=(msg_MPARMotionInfo_Array&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const msg_MPARMotionInfo_Array& default_instance() {
    return *internal_default_instance();
  }
  static inline const msg_MPARMotionInfo_Array* internal_default_instance() {
    return reinterpret_cast<const msg_MPARMotionInfo_Array*>(
               &_msg_MPARMotionInfo_Array_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(msg_MPARMotionInfo_Array& a, msg_MPARMotionInfo_Array& b) {
    a.Swap(&b);
  }
  inline void Swap(msg_MPARMotionInfo_Array* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(msg_MPARMotionInfo_Array* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  msg_MPARMotionInfo_Array* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<msg_MPARMotionInfo_Array>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const msg_MPARMotionInfo_Array& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const msg_MPARMotionInfo_Array& from) {
    msg_MPARMotionInfo_Array::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(msg_MPARMotionInfo_Array* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg.MPARMotionInfo.msg_MPARMotionInfo_Array";
  }
  protected:
  explicit msg_MPARMotionInfo_Array(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMPARMotionInfosFieldNumber = 1,
    kPackageNumFieldNumber = 2,
    kSelectedRouteIDFieldNumber = 3,
  };
  // repeated .msg.MPARMotionInfo.msg_MPARMotionInfo MPARMotionInfos = 1;
  int mparmotioninfos_size() const;
  private:
  int _internal_mparmotioninfos_size() const;
  public:
  void clear_mparmotioninfos();
  ::msg::MPARMotionInfo::msg_MPARMotionInfo* mutable_mparmotioninfos(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::msg::MPARMotionInfo::msg_MPARMotionInfo >*
      mutable_mparmotioninfos();
  private:
  const ::msg::MPARMotionInfo::msg_MPARMotionInfo& _internal_mparmotioninfos(int index) const;
  ::msg::MPARMotionInfo::msg_MPARMotionInfo* _internal_add_mparmotioninfos();
  public:
  const ::msg::MPARMotionInfo::msg_MPARMotionInfo& mparmotioninfos(int index) const;
  ::msg::MPARMotionInfo::msg_MPARMotionInfo* add_mparmotioninfos();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::msg::MPARMotionInfo::msg_MPARMotionInfo >&
      mparmotioninfos() const;

  // int32 packageNum = 2;
  void clear_packagenum();
  int32_t packagenum() const;
  void set_packagenum(int32_t value);
  private:
  int32_t _internal_packagenum() const;
  void _internal_set_packagenum(int32_t value);
  public:

  // int32 selectedRouteID = 3;
  void clear_selectedrouteid();
  int32_t selectedrouteid() const;
  void set_selectedrouteid(int32_t value);
  private:
  int32_t _internal_selectedrouteid() const;
  void _internal_set_selectedrouteid(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:msg.MPARMotionInfo.msg_MPARMotionInfo_Array)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::msg::MPARMotionInfo::msg_MPARMotionInfo > mparmotioninfos_;
    int32_t packagenum_;
    int32_t selectedrouteid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_MPARMotionInfo_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// msg_MPARMotionInfo

// double TargetPosX = 1;
inline void msg_MPARMotionInfo::clear_targetposx() {
  _impl_.targetposx_ = 0;
}
inline double msg_MPARMotionInfo::_internal_targetposx() const {
  return _impl_.targetposx_;
}
inline double msg_MPARMotionInfo::targetposx() const {
  // @@protoc_insertion_point(field_get:msg.MPARMotionInfo.msg_MPARMotionInfo.TargetPosX)
  return _internal_targetposx();
}
inline void msg_MPARMotionInfo::_internal_set_targetposx(double value) {
  
  _impl_.targetposx_ = value;
}
inline void msg_MPARMotionInfo::set_targetposx(double value) {
  _internal_set_targetposx(value);
  // @@protoc_insertion_point(field_set:msg.MPARMotionInfo.msg_MPARMotionInfo.TargetPosX)
}

// double TargetPosY = 2;
inline void msg_MPARMotionInfo::clear_targetposy() {
  _impl_.targetposy_ = 0;
}
inline double msg_MPARMotionInfo::_internal_targetposy() const {
  return _impl_.targetposy_;
}
inline double msg_MPARMotionInfo::targetposy() const {
  // @@protoc_insertion_point(field_get:msg.MPARMotionInfo.msg_MPARMotionInfo.TargetPosY)
  return _internal_targetposy();
}
inline void msg_MPARMotionInfo::_internal_set_targetposy(double value) {
  
  _impl_.targetposy_ = value;
}
inline void msg_MPARMotionInfo::set_targetposy(double value) {
  _internal_set_targetposy(value);
  // @@protoc_insertion_point(field_set:msg.MPARMotionInfo.msg_MPARMotionInfo.TargetPosY)
}

// double TargetPosZ = 3;
inline void msg_MPARMotionInfo::clear_targetposz() {
  _impl_.targetposz_ = 0;
}
inline double msg_MPARMotionInfo::_internal_targetposz() const {
  return _impl_.targetposz_;
}
inline double msg_MPARMotionInfo::targetposz() const {
  // @@protoc_insertion_point(field_get:msg.MPARMotionInfo.msg_MPARMotionInfo.TargetPosZ)
  return _internal_targetposz();
}
inline void msg_MPARMotionInfo::_internal_set_targetposz(double value) {
  
  _impl_.targetposz_ = value;
}
inline void msg_MPARMotionInfo::set_targetposz(double value) {
  _internal_set_targetposz(value);
  // @@protoc_insertion_point(field_set:msg.MPARMotionInfo.msg_MPARMotionInfo.TargetPosZ)
}

// double TargetVelX = 4;
inline void msg_MPARMotionInfo::clear_targetvelx() {
  _impl_.targetvelx_ = 0;
}
inline double msg_MPARMotionInfo::_internal_targetvelx() const {
  return _impl_.targetvelx_;
}
inline double msg_MPARMotionInfo::targetvelx() const {
  // @@protoc_insertion_point(field_get:msg.MPARMotionInfo.msg_MPARMotionInfo.TargetVelX)
  return _internal_targetvelx();
}
inline void msg_MPARMotionInfo::_internal_set_targetvelx(double value) {
  
  _impl_.targetvelx_ = value;
}
inline void msg_MPARMotionInfo::set_targetvelx(double value) {
  _internal_set_targetvelx(value);
  // @@protoc_insertion_point(field_set:msg.MPARMotionInfo.msg_MPARMotionInfo.TargetVelX)
}

// double TargetVelY = 5;
inline void msg_MPARMotionInfo::clear_targetvely() {
  _impl_.targetvely_ = 0;
}
inline double msg_MPARMotionInfo::_internal_targetvely() const {
  return _impl_.targetvely_;
}
inline double msg_MPARMotionInfo::targetvely() const {
  // @@protoc_insertion_point(field_get:msg.MPARMotionInfo.msg_MPARMotionInfo.TargetVelY)
  return _internal_targetvely();
}
inline void msg_MPARMotionInfo::_internal_set_targetvely(double value) {
  
  _impl_.targetvely_ = value;
}
inline void msg_MPARMotionInfo::set_targetvely(double value) {
  _internal_set_targetvely(value);
  // @@protoc_insertion_point(field_set:msg.MPARMotionInfo.msg_MPARMotionInfo.TargetVelY)
}

// double TargetVelZ = 6;
inline void msg_MPARMotionInfo::clear_targetvelz() {
  _impl_.targetvelz_ = 0;
}
inline double msg_MPARMotionInfo::_internal_targetvelz() const {
  return _impl_.targetvelz_;
}
inline double msg_MPARMotionInfo::targetvelz() const {
  // @@protoc_insertion_point(field_get:msg.MPARMotionInfo.msg_MPARMotionInfo.TargetVelZ)
  return _internal_targetvelz();
}
inline void msg_MPARMotionInfo::_internal_set_targetvelz(double value) {
  
  _impl_.targetvelz_ = value;
}
inline void msg_MPARMotionInfo::set_targetvelz(double value) {
  _internal_set_targetvelz(value);
  // @@protoc_insertion_point(field_set:msg.MPARMotionInfo.msg_MPARMotionInfo.TargetVelZ)
}

// int32 TargetRCS = 7;
inline void msg_MPARMotionInfo::clear_targetrcs() {
  _impl_.targetrcs_ = 0;
}
inline int32_t msg_MPARMotionInfo::_internal_targetrcs() const {
  return _impl_.targetrcs_;
}
inline int32_t msg_MPARMotionInfo::targetrcs() const {
  // @@protoc_insertion_point(field_get:msg.MPARMotionInfo.msg_MPARMotionInfo.TargetRCS)
  return _internal_targetrcs();
}
inline void msg_MPARMotionInfo::_internal_set_targetrcs(int32_t value) {
  
  _impl_.targetrcs_ = value;
}
inline void msg_MPARMotionInfo::set_targetrcs(int32_t value) {
  _internal_set_targetrcs(value);
  // @@protoc_insertion_point(field_set:msg.MPARMotionInfo.msg_MPARMotionInfo.TargetRCS)
}

// string TargetID = 8;
inline void msg_MPARMotionInfo::clear_targetid() {
  _impl_.targetid_.ClearToEmpty();
}
inline const std::string& msg_MPARMotionInfo::targetid() const {
  // @@protoc_insertion_point(field_get:msg.MPARMotionInfo.msg_MPARMotionInfo.TargetID)
  return _internal_targetid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void msg_MPARMotionInfo::set_targetid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.targetid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg.MPARMotionInfo.msg_MPARMotionInfo.TargetID)
}
inline std::string* msg_MPARMotionInfo::mutable_targetid() {
  std::string* _s = _internal_mutable_targetid();
  // @@protoc_insertion_point(field_mutable:msg.MPARMotionInfo.msg_MPARMotionInfo.TargetID)
  return _s;
}
inline const std::string& msg_MPARMotionInfo::_internal_targetid() const {
  return _impl_.targetid_.Get();
}
inline void msg_MPARMotionInfo::_internal_set_targetid(const std::string& value) {
  
  _impl_.targetid_.Set(value, GetArenaForAllocation());
}
inline std::string* msg_MPARMotionInfo::_internal_mutable_targetid() {
  
  return _impl_.targetid_.Mutable(GetArenaForAllocation());
}
inline std::string* msg_MPARMotionInfo::release_targetid() {
  // @@protoc_insertion_point(field_release:msg.MPARMotionInfo.msg_MPARMotionInfo.TargetID)
  return _impl_.targetid_.Release();
}
inline void msg_MPARMotionInfo::set_allocated_targetid(std::string* targetid) {
  if (targetid != nullptr) {
    
  } else {
    
  }
  _impl_.targetid_.SetAllocated(targetid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.targetid_.IsDefault()) {
    _impl_.targetid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg.MPARMotionInfo.msg_MPARMotionInfo.TargetID)
}

// -------------------------------------------------------------------

// msg_MPARMotionInfo_Array

// repeated .msg.MPARMotionInfo.msg_MPARMotionInfo MPARMotionInfos = 1;
inline int msg_MPARMotionInfo_Array::_internal_mparmotioninfos_size() const {
  return _impl_.mparmotioninfos_.size();
}
inline int msg_MPARMotionInfo_Array::mparmotioninfos_size() const {
  return _internal_mparmotioninfos_size();
}
inline void msg_MPARMotionInfo_Array::clear_mparmotioninfos() {
  _impl_.mparmotioninfos_.Clear();
}
inline ::msg::MPARMotionInfo::msg_MPARMotionInfo* msg_MPARMotionInfo_Array::mutable_mparmotioninfos(int index) {
  // @@protoc_insertion_point(field_mutable:msg.MPARMotionInfo.msg_MPARMotionInfo_Array.MPARMotionInfos)
  return _impl_.mparmotioninfos_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::msg::MPARMotionInfo::msg_MPARMotionInfo >*
msg_MPARMotionInfo_Array::mutable_mparmotioninfos() {
  // @@protoc_insertion_point(field_mutable_list:msg.MPARMotionInfo.msg_MPARMotionInfo_Array.MPARMotionInfos)
  return &_impl_.mparmotioninfos_;
}
inline const ::msg::MPARMotionInfo::msg_MPARMotionInfo& msg_MPARMotionInfo_Array::_internal_mparmotioninfos(int index) const {
  return _impl_.mparmotioninfos_.Get(index);
}
inline const ::msg::MPARMotionInfo::msg_MPARMotionInfo& msg_MPARMotionInfo_Array::mparmotioninfos(int index) const {
  // @@protoc_insertion_point(field_get:msg.MPARMotionInfo.msg_MPARMotionInfo_Array.MPARMotionInfos)
  return _internal_mparmotioninfos(index);
}
inline ::msg::MPARMotionInfo::msg_MPARMotionInfo* msg_MPARMotionInfo_Array::_internal_add_mparmotioninfos() {
  return _impl_.mparmotioninfos_.Add();
}
inline ::msg::MPARMotionInfo::msg_MPARMotionInfo* msg_MPARMotionInfo_Array::add_mparmotioninfos() {
  ::msg::MPARMotionInfo::msg_MPARMotionInfo* _add = _internal_add_mparmotioninfos();
  // @@protoc_insertion_point(field_add:msg.MPARMotionInfo.msg_MPARMotionInfo_Array.MPARMotionInfos)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::msg::MPARMotionInfo::msg_MPARMotionInfo >&
msg_MPARMotionInfo_Array::mparmotioninfos() const {
  // @@protoc_insertion_point(field_list:msg.MPARMotionInfo.msg_MPARMotionInfo_Array.MPARMotionInfos)
  return _impl_.mparmotioninfos_;
}

// int32 packageNum = 2;
inline void msg_MPARMotionInfo_Array::clear_packagenum() {
  _impl_.packagenum_ = 0;
}
inline int32_t msg_MPARMotionInfo_Array::_internal_packagenum() const {
  return _impl_.packagenum_;
}
inline int32_t msg_MPARMotionInfo_Array::packagenum() const {
  // @@protoc_insertion_point(field_get:msg.MPARMotionInfo.msg_MPARMotionInfo_Array.packageNum)
  return _internal_packagenum();
}
inline void msg_MPARMotionInfo_Array::_internal_set_packagenum(int32_t value) {
  
  _impl_.packagenum_ = value;
}
inline void msg_MPARMotionInfo_Array::set_packagenum(int32_t value) {
  _internal_set_packagenum(value);
  // @@protoc_insertion_point(field_set:msg.MPARMotionInfo.msg_MPARMotionInfo_Array.packageNum)
}

// int32 selectedRouteID = 3;
inline void msg_MPARMotionInfo_Array::clear_selectedrouteid() {
  _impl_.selectedrouteid_ = 0;
}
inline int32_t msg_MPARMotionInfo_Array::_internal_selectedrouteid() const {
  return _impl_.selectedrouteid_;
}
inline int32_t msg_MPARMotionInfo_Array::selectedrouteid() const {
  // @@protoc_insertion_point(field_get:msg.MPARMotionInfo.msg_MPARMotionInfo_Array.selectedRouteID)
  return _internal_selectedrouteid();
}
inline void msg_MPARMotionInfo_Array::_internal_set_selectedrouteid(int32_t value) {
  
  _impl_.selectedrouteid_ = value;
}
inline void msg_MPARMotionInfo_Array::set_selectedrouteid(int32_t value) {
  _internal_set_selectedrouteid(value);
  // @@protoc_insertion_point(field_set:msg.MPARMotionInfo.msg_MPARMotionInfo_Array.selectedRouteID)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace MPARMotionInfo
}  // namespace msg

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_MPARMotionInfo_2eproto
