// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MparFrame.proto

#include "MparFrame.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace msg {
namespace MparFrame {
PROTOBUF_CONSTEXPR msg_MparFrame::msg_MparFrame(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.targetpos_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.targetvel_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.targetrcs_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct msg_MparFrameDefaultTypeInternal {
  PROTOBUF_CONSTEXPR msg_MparFrameDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~msg_MparFrameDefaultTypeInternal() {}
  union {
    msg_MparFrame _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 msg_MparFrameDefaultTypeInternal _msg_MparFrame_default_instance_;
}  // namespace MparFrame
}  // namespace msg
static ::_pb::Metadata file_level_metadata_MparFrame_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_MparFrame_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_MparFrame_2eproto = nullptr;

const uint32_t TableStruct_MparFrame_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::msg::MparFrame::msg_MparFrame, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::msg::MparFrame::msg_MparFrame, _impl_.targetpos_),
  PROTOBUF_FIELD_OFFSET(::msg::MparFrame::msg_MparFrame, _impl_.targetvel_),
  PROTOBUF_FIELD_OFFSET(::msg::MparFrame::msg_MparFrame, _impl_.targetrcs_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::msg::MparFrame::msg_MparFrame)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::msg::MparFrame::_msg_MparFrame_default_instance_._instance,
};

const char descriptor_table_protodef_MparFrame_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017MparFrame.proto\022\rmsg.MparFrame\"H\n\rmsg_"
  "MparFrame\022\021\n\tTargetPos\030\001 \001(\014\022\021\n\tTargetVe"
  "l\030\002 \001(\014\022\021\n\tTargetRCS\030\003 \001(\014b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_MparFrame_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_MparFrame_2eproto = {
    false, false, 114, descriptor_table_protodef_MparFrame_2eproto,
    "MparFrame.proto",
    &descriptor_table_MparFrame_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_MparFrame_2eproto::offsets,
    file_level_metadata_MparFrame_2eproto, file_level_enum_descriptors_MparFrame_2eproto,
    file_level_service_descriptors_MparFrame_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_MparFrame_2eproto_getter() {
  return &descriptor_table_MparFrame_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_MparFrame_2eproto(&descriptor_table_MparFrame_2eproto);
namespace msg {
namespace MparFrame {

// ===================================================================

class msg_MparFrame::_Internal {
 public:
};

msg_MparFrame::msg_MparFrame(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:msg.MparFrame.msg_MparFrame)
}
msg_MparFrame::msg_MparFrame(const msg_MparFrame& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  msg_MparFrame* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.targetpos_){}
    , decltype(_impl_.targetvel_){}
    , decltype(_impl_.targetrcs_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.targetpos_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.targetpos_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_targetpos().empty()) {
    _this->_impl_.targetpos_.Set(from._internal_targetpos(), 
      _this->GetArenaForAllocation());
  }
  _impl_.targetvel_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.targetvel_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_targetvel().empty()) {
    _this->_impl_.targetvel_.Set(from._internal_targetvel(), 
      _this->GetArenaForAllocation());
  }
  _impl_.targetrcs_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.targetrcs_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_targetrcs().empty()) {
    _this->_impl_.targetrcs_.Set(from._internal_targetrcs(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:msg.MparFrame.msg_MparFrame)
}

inline void msg_MparFrame::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.targetpos_){}
    , decltype(_impl_.targetvel_){}
    , decltype(_impl_.targetrcs_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.targetpos_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.targetpos_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.targetvel_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.targetvel_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.targetrcs_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.targetrcs_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

msg_MparFrame::~msg_MparFrame() {
  // @@protoc_insertion_point(destructor:msg.MparFrame.msg_MparFrame)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void msg_MparFrame::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.targetpos_.Destroy();
  _impl_.targetvel_.Destroy();
  _impl_.targetrcs_.Destroy();
}

void msg_MparFrame::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void msg_MparFrame::Clear() {
// @@protoc_insertion_point(message_clear_start:msg.MparFrame.msg_MparFrame)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.targetpos_.ClearToEmpty();
  _impl_.targetvel_.ClearToEmpty();
  _impl_.targetrcs_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* msg_MparFrame::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bytes TargetPos = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_targetpos();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes TargetVel = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_targetvel();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes TargetRCS = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_targetrcs();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* msg_MparFrame::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:msg.MparFrame.msg_MparFrame)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes TargetPos = 1;
  if (!this->_internal_targetpos().empty()) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_targetpos(), target);
  }

  // bytes TargetVel = 2;
  if (!this->_internal_targetvel().empty()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_targetvel(), target);
  }

  // bytes TargetRCS = 3;
  if (!this->_internal_targetrcs().empty()) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_targetrcs(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:msg.MparFrame.msg_MparFrame)
  return target;
}

size_t msg_MparFrame::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:msg.MparFrame.msg_MparFrame)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes TargetPos = 1;
  if (!this->_internal_targetpos().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_targetpos());
  }

  // bytes TargetVel = 2;
  if (!this->_internal_targetvel().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_targetvel());
  }

  // bytes TargetRCS = 3;
  if (!this->_internal_targetrcs().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_targetrcs());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData msg_MparFrame::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    msg_MparFrame::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*msg_MparFrame::GetClassData() const { return &_class_data_; }


void msg_MparFrame::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<msg_MparFrame*>(&to_msg);
  auto& from = static_cast<const msg_MparFrame&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:msg.MparFrame.msg_MparFrame)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_targetpos().empty()) {
    _this->_internal_set_targetpos(from._internal_targetpos());
  }
  if (!from._internal_targetvel().empty()) {
    _this->_internal_set_targetvel(from._internal_targetvel());
  }
  if (!from._internal_targetrcs().empty()) {
    _this->_internal_set_targetrcs(from._internal_targetrcs());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void msg_MparFrame::CopyFrom(const msg_MparFrame& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:msg.MparFrame.msg_MparFrame)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool msg_MparFrame::IsInitialized() const {
  return true;
}

void msg_MparFrame::InternalSwap(msg_MparFrame* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.targetpos_, lhs_arena,
      &other->_impl_.targetpos_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.targetvel_, lhs_arena,
      &other->_impl_.targetvel_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.targetrcs_, lhs_arena,
      &other->_impl_.targetrcs_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata msg_MparFrame::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_MparFrame_2eproto_getter, &descriptor_table_MparFrame_2eproto_once,
      file_level_metadata_MparFrame_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace MparFrame
}  // namespace msg
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::msg::MparFrame::msg_MparFrame*
Arena::CreateMaybeMessage< ::msg::MparFrame::msg_MparFrame >(Arena* arena) {
  return Arena::CreateMessageInternal< ::msg::MparFrame::msg_MparFrame >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
