// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MparFrame.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_MparFrame_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_MparFrame_2eproto

#include "gaeactor_comm_global.h"

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_MparFrame_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_MparFrame_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_MparFrame_2eproto;
namespace msg {
namespace MparFrame {
class msg_MparFrame;
struct msg_MparFrameDefaultTypeInternal;
extern msg_MparFrameDefaultTypeInternal _msg_MparFrame_default_instance_;
}  // namespace MparFrame
}  // namespace msg
PROTOBUF_NAMESPACE_OPEN
template<> ::msg::MparFrame::msg_MparFrame* Arena::CreateMaybeMessage<::msg::MparFrame::msg_MparFrame>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace msg {
namespace MparFrame {

// ===================================================================

class GAEACTOR_COMM_EXPORT msg_MparFrame final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg.MparFrame.msg_MparFrame) */ {
 public:
  inline msg_MparFrame() : msg_MparFrame(nullptr) {}
  ~msg_MparFrame() override;
  explicit PROTOBUF_CONSTEXPR msg_MparFrame(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  msg_MparFrame(const msg_MparFrame& from);
  msg_MparFrame(msg_MparFrame&& from) noexcept
    : msg_MparFrame() {
    *this = ::std::move(from);
  }

  inline msg_MparFrame& operator=(const msg_MparFrame& from) {
    CopyFrom(from);
    return *this;
  }
  inline msg_MparFrame& operator=(msg_MparFrame&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const msg_MparFrame& default_instance() {
    return *internal_default_instance();
  }
  static inline const msg_MparFrame* internal_default_instance() {
    return reinterpret_cast<const msg_MparFrame*>(
               &_msg_MparFrame_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(msg_MparFrame& a, msg_MparFrame& b) {
    a.Swap(&b);
  }
  inline void Swap(msg_MparFrame* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(msg_MparFrame* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  msg_MparFrame* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<msg_MparFrame>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const msg_MparFrame& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const msg_MparFrame& from) {
    msg_MparFrame::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(msg_MparFrame* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg.MparFrame.msg_MparFrame";
  }
  protected:
  explicit msg_MparFrame(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTargetPosFieldNumber = 1,
    kTargetVelFieldNumber = 2,
    kTargetRCSFieldNumber = 3,
  };
  // bytes TargetPos = 1;
  void clear_targetpos();
  const std::string& targetpos() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_targetpos(ArgT0&& arg0, ArgT... args);
  std::string* mutable_targetpos();
  PROTOBUF_NODISCARD std::string* release_targetpos();
  void set_allocated_targetpos(std::string* targetpos);
  private:
  const std::string& _internal_targetpos() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_targetpos(const std::string& value);
  std::string* _internal_mutable_targetpos();
  public:

  // bytes TargetVel = 2;
  void clear_targetvel();
  const std::string& targetvel() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_targetvel(ArgT0&& arg0, ArgT... args);
  std::string* mutable_targetvel();
  PROTOBUF_NODISCARD std::string* release_targetvel();
  void set_allocated_targetvel(std::string* targetvel);
  private:
  const std::string& _internal_targetvel() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_targetvel(const std::string& value);
  std::string* _internal_mutable_targetvel();
  public:

  // bytes TargetRCS = 3;
  void clear_targetrcs();
  const std::string& targetrcs() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_targetrcs(ArgT0&& arg0, ArgT... args);
  std::string* mutable_targetrcs();
  PROTOBUF_NODISCARD std::string* release_targetrcs();
  void set_allocated_targetrcs(std::string* targetrcs);
  private:
  const std::string& _internal_targetrcs() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_targetrcs(const std::string& value);
  std::string* _internal_mutable_targetrcs();
  public:

  // @@protoc_insertion_point(class_scope:msg.MparFrame.msg_MparFrame)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr targetpos_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr targetvel_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr targetrcs_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_MparFrame_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// msg_MparFrame

// bytes TargetPos = 1;
inline void msg_MparFrame::clear_targetpos() {
  _impl_.targetpos_.ClearToEmpty();
}
inline const std::string& msg_MparFrame::targetpos() const {
  // @@protoc_insertion_point(field_get:msg.MparFrame.msg_MparFrame.TargetPos)
  return _internal_targetpos();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void msg_MparFrame::set_targetpos(ArgT0&& arg0, ArgT... args) {
 
 _impl_.targetpos_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg.MparFrame.msg_MparFrame.TargetPos)
}
inline std::string* msg_MparFrame::mutable_targetpos() {
  std::string* _s = _internal_mutable_targetpos();
  // @@protoc_insertion_point(field_mutable:msg.MparFrame.msg_MparFrame.TargetPos)
  return _s;
}
inline const std::string& msg_MparFrame::_internal_targetpos() const {
  return _impl_.targetpos_.Get();
}
inline void msg_MparFrame::_internal_set_targetpos(const std::string& value) {
  
  _impl_.targetpos_.Set(value, GetArenaForAllocation());
}
inline std::string* msg_MparFrame::_internal_mutable_targetpos() {
  
  return _impl_.targetpos_.Mutable(GetArenaForAllocation());
}
inline std::string* msg_MparFrame::release_targetpos() {
  // @@protoc_insertion_point(field_release:msg.MparFrame.msg_MparFrame.TargetPos)
  return _impl_.targetpos_.Release();
}
inline void msg_MparFrame::set_allocated_targetpos(std::string* targetpos) {
  if (targetpos != nullptr) {
    
  } else {
    
  }
  _impl_.targetpos_.SetAllocated(targetpos, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.targetpos_.IsDefault()) {
    _impl_.targetpos_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg.MparFrame.msg_MparFrame.TargetPos)
}

// bytes TargetVel = 2;
inline void msg_MparFrame::clear_targetvel() {
  _impl_.targetvel_.ClearToEmpty();
}
inline const std::string& msg_MparFrame::targetvel() const {
  // @@protoc_insertion_point(field_get:msg.MparFrame.msg_MparFrame.TargetVel)
  return _internal_targetvel();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void msg_MparFrame::set_targetvel(ArgT0&& arg0, ArgT... args) {
 
 _impl_.targetvel_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg.MparFrame.msg_MparFrame.TargetVel)
}
inline std::string* msg_MparFrame::mutable_targetvel() {
  std::string* _s = _internal_mutable_targetvel();
  // @@protoc_insertion_point(field_mutable:msg.MparFrame.msg_MparFrame.TargetVel)
  return _s;
}
inline const std::string& msg_MparFrame::_internal_targetvel() const {
  return _impl_.targetvel_.Get();
}
inline void msg_MparFrame::_internal_set_targetvel(const std::string& value) {
  
  _impl_.targetvel_.Set(value, GetArenaForAllocation());
}
inline std::string* msg_MparFrame::_internal_mutable_targetvel() {
  
  return _impl_.targetvel_.Mutable(GetArenaForAllocation());
}
inline std::string* msg_MparFrame::release_targetvel() {
  // @@protoc_insertion_point(field_release:msg.MparFrame.msg_MparFrame.TargetVel)
  return _impl_.targetvel_.Release();
}
inline void msg_MparFrame::set_allocated_targetvel(std::string* targetvel) {
  if (targetvel != nullptr) {
    
  } else {
    
  }
  _impl_.targetvel_.SetAllocated(targetvel, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.targetvel_.IsDefault()) {
    _impl_.targetvel_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg.MparFrame.msg_MparFrame.TargetVel)
}

// bytes TargetRCS = 3;
inline void msg_MparFrame::clear_targetrcs() {
  _impl_.targetrcs_.ClearToEmpty();
}
inline const std::string& msg_MparFrame::targetrcs() const {
  // @@protoc_insertion_point(field_get:msg.MparFrame.msg_MparFrame.TargetRCS)
  return _internal_targetrcs();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void msg_MparFrame::set_targetrcs(ArgT0&& arg0, ArgT... args) {
 
 _impl_.targetrcs_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg.MparFrame.msg_MparFrame.TargetRCS)
}
inline std::string* msg_MparFrame::mutable_targetrcs() {
  std::string* _s = _internal_mutable_targetrcs();
  // @@protoc_insertion_point(field_mutable:msg.MparFrame.msg_MparFrame.TargetRCS)
  return _s;
}
inline const std::string& msg_MparFrame::_internal_targetrcs() const {
  return _impl_.targetrcs_.Get();
}
inline void msg_MparFrame::_internal_set_targetrcs(const std::string& value) {
  
  _impl_.targetrcs_.Set(value, GetArenaForAllocation());
}
inline std::string* msg_MparFrame::_internal_mutable_targetrcs() {
  
  return _impl_.targetrcs_.Mutable(GetArenaForAllocation());
}
inline std::string* msg_MparFrame::release_targetrcs() {
  // @@protoc_insertion_point(field_release:msg.MparFrame.msg_MparFrame.TargetRCS)
  return _impl_.targetrcs_.Release();
}
inline void msg_MparFrame::set_allocated_targetrcs(std::string* targetrcs) {
  if (targetrcs != nullptr) {
    
  } else {
    
  }
  _impl_.targetrcs_.SetAllocated(targetrcs, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.targetrcs_.IsDefault()) {
    _impl_.targetrcs_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg.MparFrame.msg_MparFrame.TargetRCS)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace MparFrame
}  // namespace msg

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_MparFrame_2eproto
