// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SARMotionInfo.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_SARMotionInfo_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_SARMotionInfo_2eproto

#include "gaeactor_comm_global.h"

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_SARMotionInfo_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_SARMotionInfo_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_SARMotionInfo_2eproto;
namespace msg {
namespace SARMotionInfo {
class msg_SARMotionInfo;
struct msg_SARMotionInfoDefaultTypeInternal;
extern msg_SARMotionInfoDefaultTypeInternal _msg_SARMotionInfo_default_instance_;
class msg_SARMotionResult;
struct msg_SARMotionResultDefaultTypeInternal;
extern msg_SARMotionResultDefaultTypeInternal _msg_SARMotionResult_default_instance_;
}  // namespace SARMotionInfo
}  // namespace msg
PROTOBUF_NAMESPACE_OPEN
template<> ::msg::SARMotionInfo::msg_SARMotionInfo* Arena::CreateMaybeMessage<::msg::SARMotionInfo::msg_SARMotionInfo>(Arena*);
template<> ::msg::SARMotionInfo::msg_SARMotionResult* Arena::CreateMaybeMessage<::msg::SARMotionInfo::msg_SARMotionResult>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace msg {
namespace SARMotionInfo {

// ===================================================================

class GAEACTOR_COMM_EXPORT msg_SARMotionInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg.SARMotionInfo.msg_SARMotionInfo) */ {
 public:
  inline msg_SARMotionInfo() : msg_SARMotionInfo(nullptr) {}
  ~msg_SARMotionInfo() override;
  explicit PROTOBUF_CONSTEXPR msg_SARMotionInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  msg_SARMotionInfo(const msg_SARMotionInfo& from);
  msg_SARMotionInfo(msg_SARMotionInfo&& from) noexcept
    : msg_SARMotionInfo() {
    *this = ::std::move(from);
  }

  inline msg_SARMotionInfo& operator=(const msg_SARMotionInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline msg_SARMotionInfo& operator=(msg_SARMotionInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const msg_SARMotionInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const msg_SARMotionInfo* internal_default_instance() {
    return reinterpret_cast<const msg_SARMotionInfo*>(
               &_msg_SARMotionInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(msg_SARMotionInfo& a, msg_SARMotionInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(msg_SARMotionInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(msg_SARMotionInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  msg_SARMotionInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<msg_SARMotionInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const msg_SARMotionInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const msg_SARMotionInfo& from) {
    msg_SARMotionInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(msg_SARMotionInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg.SARMotionInfo.msg_SARMotionInfo";
  }
  protected:
  explicit msg_SARMotionInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTarget2RardarIDFieldNumber = 3,
    kTargetAzimuthFieldNumber = 1,
    kRadarAzimuthFieldNumber = 2,
  };
  // string Target2RardarID = 3;
  void clear_target2rardarid();
  const std::string& target2rardarid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_target2rardarid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_target2rardarid();
  PROTOBUF_NODISCARD std::string* release_target2rardarid();
  void set_allocated_target2rardarid(std::string* target2rardarid);
  private:
  const std::string& _internal_target2rardarid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_target2rardarid(const std::string& value);
  std::string* _internal_mutable_target2rardarid();
  public:

  // double TargetAzimuth = 1;
  void clear_targetazimuth();
  double targetazimuth() const;
  void set_targetazimuth(double value);
  private:
  double _internal_targetazimuth() const;
  void _internal_set_targetazimuth(double value);
  public:

  // double RadarAzimuth = 2;
  void clear_radarazimuth();
  double radarazimuth() const;
  void set_radarazimuth(double value);
  private:
  double _internal_radarazimuth() const;
  void _internal_set_radarazimuth(double value);
  public:

  // @@protoc_insertion_point(class_scope:msg.SARMotionInfo.msg_SARMotionInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr target2rardarid_;
    double targetazimuth_;
    double radarazimuth_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_SARMotionInfo_2eproto;
};
// -------------------------------------------------------------------

class GAEACTOR_COMM_EXPORT msg_SARMotionResult final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg.SARMotionInfo.msg_SARMotionResult) */ {
 public:
  inline msg_SARMotionResult() : msg_SARMotionResult(nullptr) {}
  ~msg_SARMotionResult() override;
  explicit PROTOBUF_CONSTEXPR msg_SARMotionResult(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  msg_SARMotionResult(const msg_SARMotionResult& from);
  msg_SARMotionResult(msg_SARMotionResult&& from) noexcept
    : msg_SARMotionResult() {
    *this = ::std::move(from);
  }

  inline msg_SARMotionResult& operator=(const msg_SARMotionResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline msg_SARMotionResult& operator=(msg_SARMotionResult&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const msg_SARMotionResult& default_instance() {
    return *internal_default_instance();
  }
  static inline const msg_SARMotionResult* internal_default_instance() {
    return reinterpret_cast<const msg_SARMotionResult*>(
               &_msg_SARMotionResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(msg_SARMotionResult& a, msg_SARMotionResult& b) {
    a.Swap(&b);
  }
  inline void Swap(msg_SARMotionResult* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(msg_SARMotionResult* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  msg_SARMotionResult* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<msg_SARMotionResult>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const msg_SARMotionResult& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const msg_SARMotionResult& from) {
    msg_SARMotionResult::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(msg_SARMotionResult* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg.SARMotionInfo.msg_SARMotionResult";
  }
  protected:
  explicit msg_SARMotionResult(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTargetIDFieldNumber = 1,
    kResultPathFieldNumber = 2,
  };
  // string TargetID = 1;
  void clear_targetid();
  const std::string& targetid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_targetid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_targetid();
  PROTOBUF_NODISCARD std::string* release_targetid();
  void set_allocated_targetid(std::string* targetid);
  private:
  const std::string& _internal_targetid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_targetid(const std::string& value);
  std::string* _internal_mutable_targetid();
  public:

  // string ResultPath = 2;
  void clear_resultpath();
  const std::string& resultpath() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_resultpath(ArgT0&& arg0, ArgT... args);
  std::string* mutable_resultpath();
  PROTOBUF_NODISCARD std::string* release_resultpath();
  void set_allocated_resultpath(std::string* resultpath);
  private:
  const std::string& _internal_resultpath() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_resultpath(const std::string& value);
  std::string* _internal_mutable_resultpath();
  public:

  // @@protoc_insertion_point(class_scope:msg.SARMotionInfo.msg_SARMotionResult)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr targetid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr resultpath_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_SARMotionInfo_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// msg_SARMotionInfo

// double TargetAzimuth = 1;
inline void msg_SARMotionInfo::clear_targetazimuth() {
  _impl_.targetazimuth_ = 0;
}
inline double msg_SARMotionInfo::_internal_targetazimuth() const {
  return _impl_.targetazimuth_;
}
inline double msg_SARMotionInfo::targetazimuth() const {
  // @@protoc_insertion_point(field_get:msg.SARMotionInfo.msg_SARMotionInfo.TargetAzimuth)
  return _internal_targetazimuth();
}
inline void msg_SARMotionInfo::_internal_set_targetazimuth(double value) {
  
  _impl_.targetazimuth_ = value;
}
inline void msg_SARMotionInfo::set_targetazimuth(double value) {
  _internal_set_targetazimuth(value);
  // @@protoc_insertion_point(field_set:msg.SARMotionInfo.msg_SARMotionInfo.TargetAzimuth)
}

// double RadarAzimuth = 2;
inline void msg_SARMotionInfo::clear_radarazimuth() {
  _impl_.radarazimuth_ = 0;
}
inline double msg_SARMotionInfo::_internal_radarazimuth() const {
  return _impl_.radarazimuth_;
}
inline double msg_SARMotionInfo::radarazimuth() const {
  // @@protoc_insertion_point(field_get:msg.SARMotionInfo.msg_SARMotionInfo.RadarAzimuth)
  return _internal_radarazimuth();
}
inline void msg_SARMotionInfo::_internal_set_radarazimuth(double value) {
  
  _impl_.radarazimuth_ = value;
}
inline void msg_SARMotionInfo::set_radarazimuth(double value) {
  _internal_set_radarazimuth(value);
  // @@protoc_insertion_point(field_set:msg.SARMotionInfo.msg_SARMotionInfo.RadarAzimuth)
}

// string Target2RardarID = 3;
inline void msg_SARMotionInfo::clear_target2rardarid() {
  _impl_.target2rardarid_.ClearToEmpty();
}
inline const std::string& msg_SARMotionInfo::target2rardarid() const {
  // @@protoc_insertion_point(field_get:msg.SARMotionInfo.msg_SARMotionInfo.Target2RardarID)
  return _internal_target2rardarid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void msg_SARMotionInfo::set_target2rardarid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.target2rardarid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg.SARMotionInfo.msg_SARMotionInfo.Target2RardarID)
}
inline std::string* msg_SARMotionInfo::mutable_target2rardarid() {
  std::string* _s = _internal_mutable_target2rardarid();
  // @@protoc_insertion_point(field_mutable:msg.SARMotionInfo.msg_SARMotionInfo.Target2RardarID)
  return _s;
}
inline const std::string& msg_SARMotionInfo::_internal_target2rardarid() const {
  return _impl_.target2rardarid_.Get();
}
inline void msg_SARMotionInfo::_internal_set_target2rardarid(const std::string& value) {
  
  _impl_.target2rardarid_.Set(value, GetArenaForAllocation());
}
inline std::string* msg_SARMotionInfo::_internal_mutable_target2rardarid() {
  
  return _impl_.target2rardarid_.Mutable(GetArenaForAllocation());
}
inline std::string* msg_SARMotionInfo::release_target2rardarid() {
  // @@protoc_insertion_point(field_release:msg.SARMotionInfo.msg_SARMotionInfo.Target2RardarID)
  return _impl_.target2rardarid_.Release();
}
inline void msg_SARMotionInfo::set_allocated_target2rardarid(std::string* target2rardarid) {
  if (target2rardarid != nullptr) {
    
  } else {
    
  }
  _impl_.target2rardarid_.SetAllocated(target2rardarid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.target2rardarid_.IsDefault()) {
    _impl_.target2rardarid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg.SARMotionInfo.msg_SARMotionInfo.Target2RardarID)
}

// -------------------------------------------------------------------

// msg_SARMotionResult

// string TargetID = 1;
inline void msg_SARMotionResult::clear_targetid() {
  _impl_.targetid_.ClearToEmpty();
}
inline const std::string& msg_SARMotionResult::targetid() const {
  // @@protoc_insertion_point(field_get:msg.SARMotionInfo.msg_SARMotionResult.TargetID)
  return _internal_targetid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void msg_SARMotionResult::set_targetid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.targetid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg.SARMotionInfo.msg_SARMotionResult.TargetID)
}
inline std::string* msg_SARMotionResult::mutable_targetid() {
  std::string* _s = _internal_mutable_targetid();
  // @@protoc_insertion_point(field_mutable:msg.SARMotionInfo.msg_SARMotionResult.TargetID)
  return _s;
}
inline const std::string& msg_SARMotionResult::_internal_targetid() const {
  return _impl_.targetid_.Get();
}
inline void msg_SARMotionResult::_internal_set_targetid(const std::string& value) {
  
  _impl_.targetid_.Set(value, GetArenaForAllocation());
}
inline std::string* msg_SARMotionResult::_internal_mutable_targetid() {
  
  return _impl_.targetid_.Mutable(GetArenaForAllocation());
}
inline std::string* msg_SARMotionResult::release_targetid() {
  // @@protoc_insertion_point(field_release:msg.SARMotionInfo.msg_SARMotionResult.TargetID)
  return _impl_.targetid_.Release();
}
inline void msg_SARMotionResult::set_allocated_targetid(std::string* targetid) {
  if (targetid != nullptr) {
    
  } else {
    
  }
  _impl_.targetid_.SetAllocated(targetid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.targetid_.IsDefault()) {
    _impl_.targetid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg.SARMotionInfo.msg_SARMotionResult.TargetID)
}

// string ResultPath = 2;
inline void msg_SARMotionResult::clear_resultpath() {
  _impl_.resultpath_.ClearToEmpty();
}
inline const std::string& msg_SARMotionResult::resultpath() const {
  // @@protoc_insertion_point(field_get:msg.SARMotionInfo.msg_SARMotionResult.ResultPath)
  return _internal_resultpath();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void msg_SARMotionResult::set_resultpath(ArgT0&& arg0, ArgT... args) {
 
 _impl_.resultpath_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg.SARMotionInfo.msg_SARMotionResult.ResultPath)
}
inline std::string* msg_SARMotionResult::mutable_resultpath() {
  std::string* _s = _internal_mutable_resultpath();
  // @@protoc_insertion_point(field_mutable:msg.SARMotionInfo.msg_SARMotionResult.ResultPath)
  return _s;
}
inline const std::string& msg_SARMotionResult::_internal_resultpath() const {
  return _impl_.resultpath_.Get();
}
inline void msg_SARMotionResult::_internal_set_resultpath(const std::string& value) {
  
  _impl_.resultpath_.Set(value, GetArenaForAllocation());
}
inline std::string* msg_SARMotionResult::_internal_mutable_resultpath() {
  
  return _impl_.resultpath_.Mutable(GetArenaForAllocation());
}
inline std::string* msg_SARMotionResult::release_resultpath() {
  // @@protoc_insertion_point(field_release:msg.SARMotionInfo.msg_SARMotionResult.ResultPath)
  return _impl_.resultpath_.Release();
}
inline void msg_SARMotionResult::set_allocated_resultpath(std::string* resultpath) {
  if (resultpath != nullptr) {
    
  } else {
    
  }
  _impl_.resultpath_.SetAllocated(resultpath, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.resultpath_.IsDefault()) {
    _impl_.resultpath_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg.SARMotionInfo.msg_SARMotionResult.ResultPath)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace SARMotionInfo
}  // namespace msg

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_SARMotionInfo_2eproto
