// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SimParamsInfo.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_SimParamsInfo_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_SimParamsInfo_2eproto

#include "gaeactor_comm_global.h"

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_SimParamsInfo_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_SimParamsInfo_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_SimParamsInfo_2eproto;
namespace msg {
namespace SimParamsInfo {
class msg_BinaryData;
struct msg_BinaryDataDefaultTypeInternal;
extern msg_BinaryDataDefaultTypeInternal _msg_BinaryData_default_instance_;
class msg_BinaryData_Array;
struct msg_BinaryData_ArrayDefaultTypeInternal;
extern msg_BinaryData_ArrayDefaultTypeInternal _msg_BinaryData_Array_default_instance_;
class msg_SimParamsInfo;
struct msg_SimParamsInfoDefaultTypeInternal;
extern msg_SimParamsInfoDefaultTypeInternal _msg_SimParamsInfo_default_instance_;
class msg_SimTimestampInfo;
struct msg_SimTimestampInfoDefaultTypeInternal;
extern msg_SimTimestampInfoDefaultTypeInternal _msg_SimTimestampInfo_default_instance_;
}  // namespace SimParamsInfo
}  // namespace msg
PROTOBUF_NAMESPACE_OPEN
template<> ::msg::SimParamsInfo::msg_BinaryData* Arena::CreateMaybeMessage<::msg::SimParamsInfo::msg_BinaryData>(Arena*);
template<> ::msg::SimParamsInfo::msg_BinaryData_Array* Arena::CreateMaybeMessage<::msg::SimParamsInfo::msg_BinaryData_Array>(Arena*);
template<> ::msg::SimParamsInfo::msg_SimParamsInfo* Arena::CreateMaybeMessage<::msg::SimParamsInfo::msg_SimParamsInfo>(Arena*);
template<> ::msg::SimParamsInfo::msg_SimTimestampInfo* Arena::CreateMaybeMessage<::msg::SimParamsInfo::msg_SimTimestampInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace msg {
namespace SimParamsInfo {

// ===================================================================

class GAEACTOR_COMM_EXPORT msg_SimTimestampInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg.SimParamsInfo.msg_SimTimestampInfo) */ {
 public:
  inline msg_SimTimestampInfo() : msg_SimTimestampInfo(nullptr) {}
  ~msg_SimTimestampInfo() override;
  explicit PROTOBUF_CONSTEXPR msg_SimTimestampInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  msg_SimTimestampInfo(const msg_SimTimestampInfo& from);
  msg_SimTimestampInfo(msg_SimTimestampInfo&& from) noexcept
    : msg_SimTimestampInfo() {
    *this = ::std::move(from);
  }

  inline msg_SimTimestampInfo& operator=(const msg_SimTimestampInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline msg_SimTimestampInfo& operator=(msg_SimTimestampInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const msg_SimTimestampInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const msg_SimTimestampInfo* internal_default_instance() {
    return reinterpret_cast<const msg_SimTimestampInfo*>(
               &_msg_SimTimestampInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(msg_SimTimestampInfo& a, msg_SimTimestampInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(msg_SimTimestampInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(msg_SimTimestampInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  msg_SimTimestampInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<msg_SimTimestampInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const msg_SimTimestampInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const msg_SimTimestampInfo& from) {
    msg_SimTimestampInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(msg_SimTimestampInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg.SimParamsInfo.msg_SimTimestampInfo";
  }
  protected:
  explicit msg_SimTimestampInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUtcTimestampBeginFieldNumber = 1,
    kUtcTimestampCurFieldNumber = 2,
    kSimTimestampFieldNumber = 3,
    kPhysicsTimestampFieldNumber = 4,
    kStepPosUpdateCostFieldNumber = 5,
    kStepCompleteUpdateCostFieldNumber = 6,
    kStepCallFreqDtFieldNumber = 8,
    kStepPosUpdateCostAvgFieldNumber = 9,
    kStepCompleteUpdateAvgFieldNumber = 10,
    kStepCallFreqAvgFieldNumber = 11,
  };
  // string utc_timestamp_begin = 1;
  void clear_utc_timestamp_begin();
  const std::string& utc_timestamp_begin() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_utc_timestamp_begin(ArgT0&& arg0, ArgT... args);
  std::string* mutable_utc_timestamp_begin();
  PROTOBUF_NODISCARD std::string* release_utc_timestamp_begin();
  void set_allocated_utc_timestamp_begin(std::string* utc_timestamp_begin);
  private:
  const std::string& _internal_utc_timestamp_begin() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_utc_timestamp_begin(const std::string& value);
  std::string* _internal_mutable_utc_timestamp_begin();
  public:

  // string utc_timestamp_cur = 2;
  void clear_utc_timestamp_cur();
  const std::string& utc_timestamp_cur() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_utc_timestamp_cur(ArgT0&& arg0, ArgT... args);
  std::string* mutable_utc_timestamp_cur();
  PROTOBUF_NODISCARD std::string* release_utc_timestamp_cur();
  void set_allocated_utc_timestamp_cur(std::string* utc_timestamp_cur);
  private:
  const std::string& _internal_utc_timestamp_cur() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_utc_timestamp_cur(const std::string& value);
  std::string* _internal_mutable_utc_timestamp_cur();
  public:

  // double sim_timestamp = 3;
  void clear_sim_timestamp();
  double sim_timestamp() const;
  void set_sim_timestamp(double value);
  private:
  double _internal_sim_timestamp() const;
  void _internal_set_sim_timestamp(double value);
  public:

  // double physics_timestamp = 4;
  void clear_physics_timestamp();
  double physics_timestamp() const;
  void set_physics_timestamp(double value);
  private:
  double _internal_physics_timestamp() const;
  void _internal_set_physics_timestamp(double value);
  public:

  // double step_pos_update_cost = 5;
  void clear_step_pos_update_cost();
  double step_pos_update_cost() const;
  void set_step_pos_update_cost(double value);
  private:
  double _internal_step_pos_update_cost() const;
  void _internal_set_step_pos_update_cost(double value);
  public:

  // double step_complete_update_cost = 6;
  void clear_step_complete_update_cost();
  double step_complete_update_cost() const;
  void set_step_complete_update_cost(double value);
  private:
  double _internal_step_complete_update_cost() const;
  void _internal_set_step_complete_update_cost(double value);
  public:

  // double step_call_freq_dt = 8;
  void clear_step_call_freq_dt();
  double step_call_freq_dt() const;
  void set_step_call_freq_dt(double value);
  private:
  double _internal_step_call_freq_dt() const;
  void _internal_set_step_call_freq_dt(double value);
  public:

  // double step_pos_update_cost_avg = 9;
  void clear_step_pos_update_cost_avg();
  double step_pos_update_cost_avg() const;
  void set_step_pos_update_cost_avg(double value);
  private:
  double _internal_step_pos_update_cost_avg() const;
  void _internal_set_step_pos_update_cost_avg(double value);
  public:

  // double step_complete_update_avg = 10;
  void clear_step_complete_update_avg();
  double step_complete_update_avg() const;
  void set_step_complete_update_avg(double value);
  private:
  double _internal_step_complete_update_avg() const;
  void _internal_set_step_complete_update_avg(double value);
  public:

  // double step_call_freq_avg = 11;
  void clear_step_call_freq_avg();
  double step_call_freq_avg() const;
  void set_step_call_freq_avg(double value);
  private:
  double _internal_step_call_freq_avg() const;
  void _internal_set_step_call_freq_avg(double value);
  public:

  // @@protoc_insertion_point(class_scope:msg.SimParamsInfo.msg_SimTimestampInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr utc_timestamp_begin_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr utc_timestamp_cur_;
    double sim_timestamp_;
    double physics_timestamp_;
    double step_pos_update_cost_;
    double step_complete_update_cost_;
    double step_call_freq_dt_;
    double step_pos_update_cost_avg_;
    double step_complete_update_avg_;
    double step_call_freq_avg_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_SimParamsInfo_2eproto;
};
// -------------------------------------------------------------------

class GAEACTOR_COMM_EXPORT msg_SimParamsInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg.SimParamsInfo.msg_SimParamsInfo) */ {
 public:
  inline msg_SimParamsInfo() : msg_SimParamsInfo(nullptr) {}
  ~msg_SimParamsInfo() override;
  explicit PROTOBUF_CONSTEXPR msg_SimParamsInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  msg_SimParamsInfo(const msg_SimParamsInfo& from);
  msg_SimParamsInfo(msg_SimParamsInfo&& from) noexcept
    : msg_SimParamsInfo() {
    *this = ::std::move(from);
  }

  inline msg_SimParamsInfo& operator=(const msg_SimParamsInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline msg_SimParamsInfo& operator=(msg_SimParamsInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const msg_SimParamsInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const msg_SimParamsInfo* internal_default_instance() {
    return reinterpret_cast<const msg_SimParamsInfo*>(
               &_msg_SimParamsInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(msg_SimParamsInfo& a, msg_SimParamsInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(msg_SimParamsInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(msg_SimParamsInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  msg_SimParamsInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<msg_SimParamsInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const msg_SimParamsInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const msg_SimParamsInfo& from) {
    msg_SimParamsInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(msg_SimParamsInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg.SimParamsInfo.msg_SimParamsInfo";
  }
  protected:
  explicit msg_SimParamsInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSimtimestampFieldNumber = 6,
    kStepDtFieldNumber = 2,
    kStepFreqFieldNumber = 3,
    kStepIntervalFieldNumber = 1,
    kAgentinstanceNumFieldNumber = 5,
    kOneSecondSimStepSecondFieldNumber = 4,
    kSpeedFieldNumber = 7,
  };
  // .msg.SimParamsInfo.msg_SimTimestampInfo simtimestamp = 6;
  bool has_simtimestamp() const;
  private:
  bool _internal_has_simtimestamp() const;
  public:
  void clear_simtimestamp();
  const ::msg::SimParamsInfo::msg_SimTimestampInfo& simtimestamp() const;
  PROTOBUF_NODISCARD ::msg::SimParamsInfo::msg_SimTimestampInfo* release_simtimestamp();
  ::msg::SimParamsInfo::msg_SimTimestampInfo* mutable_simtimestamp();
  void set_allocated_simtimestamp(::msg::SimParamsInfo::msg_SimTimestampInfo* simtimestamp);
  private:
  const ::msg::SimParamsInfo::msg_SimTimestampInfo& _internal_simtimestamp() const;
  ::msg::SimParamsInfo::msg_SimTimestampInfo* _internal_mutable_simtimestamp();
  public:
  void unsafe_arena_set_allocated_simtimestamp(
      ::msg::SimParamsInfo::msg_SimTimestampInfo* simtimestamp);
  ::msg::SimParamsInfo::msg_SimTimestampInfo* unsafe_arena_release_simtimestamp();

  // double step_dt = 2;
  void clear_step_dt();
  double step_dt() const;
  void set_step_dt(double value);
  private:
  double _internal_step_dt() const;
  void _internal_set_step_dt(double value);
  public:

  // double step_freq = 3;
  void clear_step_freq();
  double step_freq() const;
  void set_step_freq(double value);
  private:
  double _internal_step_freq() const;
  void _internal_set_step_freq(double value);
  public:

  // int32 step_interval = 1;
  void clear_step_interval();
  int32_t step_interval() const;
  void set_step_interval(int32_t value);
  private:
  int32_t _internal_step_interval() const;
  void _internal_set_step_interval(int32_t value);
  public:

  // int32 agentinstance_num = 5;
  void clear_agentinstance_num();
  int32_t agentinstance_num() const;
  void set_agentinstance_num(int32_t value);
  private:
  int32_t _internal_agentinstance_num() const;
  void _internal_set_agentinstance_num(int32_t value);
  public:

  // double one_second_sim_step_second = 4;
  void clear_one_second_sim_step_second();
  double one_second_sim_step_second() const;
  void set_one_second_sim_step_second(double value);
  private:
  double _internal_one_second_sim_step_second() const;
  void _internal_set_one_second_sim_step_second(double value);
  public:

  // double speed = 7;
  void clear_speed();
  double speed() const;
  void set_speed(double value);
  private:
  double _internal_speed() const;
  void _internal_set_speed(double value);
  public:

  // @@protoc_insertion_point(class_scope:msg.SimParamsInfo.msg_SimParamsInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::msg::SimParamsInfo::msg_SimTimestampInfo* simtimestamp_;
    double step_dt_;
    double step_freq_;
    int32_t step_interval_;
    int32_t agentinstance_num_;
    double one_second_sim_step_second_;
    double speed_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_SimParamsInfo_2eproto;
};
// -------------------------------------------------------------------

class GAEACTOR_COMM_EXPORT msg_BinaryData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg.SimParamsInfo.msg_BinaryData) */ {
 public:
  inline msg_BinaryData() : msg_BinaryData(nullptr) {}
  ~msg_BinaryData() override;
  explicit PROTOBUF_CONSTEXPR msg_BinaryData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  msg_BinaryData(const msg_BinaryData& from);
  msg_BinaryData(msg_BinaryData&& from) noexcept
    : msg_BinaryData() {
    *this = ::std::move(from);
  }

  inline msg_BinaryData& operator=(const msg_BinaryData& from) {
    CopyFrom(from);
    return *this;
  }
  inline msg_BinaryData& operator=(msg_BinaryData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const msg_BinaryData& default_instance() {
    return *internal_default_instance();
  }
  static inline const msg_BinaryData* internal_default_instance() {
    return reinterpret_cast<const msg_BinaryData*>(
               &_msg_BinaryData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(msg_BinaryData& a, msg_BinaryData& b) {
    a.Swap(&b);
  }
  inline void Swap(msg_BinaryData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(msg_BinaryData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  msg_BinaryData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<msg_BinaryData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const msg_BinaryData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const msg_BinaryData& from) {
    msg_BinaryData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(msg_BinaryData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg.SimParamsInfo.msg_BinaryData";
  }
  protected:
  explicit msg_BinaryData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBinarydataFieldNumber = 4,
    kPackindexFieldNumber = 1,
    kTimestampFieldNumber = 3,
    kBinarysizeFieldNumber = 2,
  };
  // bytes binarydata = 4;
  void clear_binarydata();
  const std::string& binarydata() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_binarydata(ArgT0&& arg0, ArgT... args);
  std::string* mutable_binarydata();
  PROTOBUF_NODISCARD std::string* release_binarydata();
  void set_allocated_binarydata(std::string* binarydata);
  private:
  const std::string& _internal_binarydata() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_binarydata(const std::string& value);
  std::string* _internal_mutable_binarydata();
  public:

  // uint64 packindex = 1;
  void clear_packindex();
  uint64_t packindex() const;
  void set_packindex(uint64_t value);
  private:
  uint64_t _internal_packindex() const;
  void _internal_set_packindex(uint64_t value);
  public:

  // uint64 timestamp = 3;
  void clear_timestamp();
  uint64_t timestamp() const;
  void set_timestamp(uint64_t value);
  private:
  uint64_t _internal_timestamp() const;
  void _internal_set_timestamp(uint64_t value);
  public:

  // int32 binarysize = 2;
  void clear_binarysize();
  int32_t binarysize() const;
  void set_binarysize(int32_t value);
  private:
  int32_t _internal_binarysize() const;
  void _internal_set_binarysize(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:msg.SimParamsInfo.msg_BinaryData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr binarydata_;
    uint64_t packindex_;
    uint64_t timestamp_;
    int32_t binarysize_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_SimParamsInfo_2eproto;
};
// -------------------------------------------------------------------

class GAEACTOR_COMM_EXPORT msg_BinaryData_Array final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg.SimParamsInfo.msg_BinaryData_Array) */ {
 public:
  inline msg_BinaryData_Array() : msg_BinaryData_Array(nullptr) {}
  ~msg_BinaryData_Array() override;
  explicit PROTOBUF_CONSTEXPR msg_BinaryData_Array(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  msg_BinaryData_Array(const msg_BinaryData_Array& from);
  msg_BinaryData_Array(msg_BinaryData_Array&& from) noexcept
    : msg_BinaryData_Array() {
    *this = ::std::move(from);
  }

  inline msg_BinaryData_Array& operator=(const msg_BinaryData_Array& from) {
    CopyFrom(from);
    return *this;
  }
  inline msg_BinaryData_Array& operator=(msg_BinaryData_Array&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const msg_BinaryData_Array& default_instance() {
    return *internal_default_instance();
  }
  static inline const msg_BinaryData_Array* internal_default_instance() {
    return reinterpret_cast<const msg_BinaryData_Array*>(
               &_msg_BinaryData_Array_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(msg_BinaryData_Array& a, msg_BinaryData_Array& b) {
    a.Swap(&b);
  }
  inline void Swap(msg_BinaryData_Array* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(msg_BinaryData_Array* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  msg_BinaryData_Array* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<msg_BinaryData_Array>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const msg_BinaryData_Array& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const msg_BinaryData_Array& from) {
    msg_BinaryData_Array::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(msg_BinaryData_Array* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg.SimParamsInfo.msg_BinaryData_Array";
  }
  protected:
  explicit msg_BinaryData_Array(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBinarydatasFieldNumber = 2,
    kPackindexFieldNumber = 1,
  };
  // repeated .msg.SimParamsInfo.msg_BinaryData binarydatas = 2;
  int binarydatas_size() const;
  private:
  int _internal_binarydatas_size() const;
  public:
  void clear_binarydatas();
  ::msg::SimParamsInfo::msg_BinaryData* mutable_binarydatas(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::msg::SimParamsInfo::msg_BinaryData >*
      mutable_binarydatas();
  private:
  const ::msg::SimParamsInfo::msg_BinaryData& _internal_binarydatas(int index) const;
  ::msg::SimParamsInfo::msg_BinaryData* _internal_add_binarydatas();
  public:
  const ::msg::SimParamsInfo::msg_BinaryData& binarydatas(int index) const;
  ::msg::SimParamsInfo::msg_BinaryData* add_binarydatas();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::msg::SimParamsInfo::msg_BinaryData >&
      binarydatas() const;

  // uint64 packindex = 1;
  void clear_packindex();
  uint64_t packindex() const;
  void set_packindex(uint64_t value);
  private:
  uint64_t _internal_packindex() const;
  void _internal_set_packindex(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:msg.SimParamsInfo.msg_BinaryData_Array)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::msg::SimParamsInfo::msg_BinaryData > binarydatas_;
    uint64_t packindex_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_SimParamsInfo_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// msg_SimTimestampInfo

// string utc_timestamp_begin = 1;
inline void msg_SimTimestampInfo::clear_utc_timestamp_begin() {
  _impl_.utc_timestamp_begin_.ClearToEmpty();
}
inline const std::string& msg_SimTimestampInfo::utc_timestamp_begin() const {
  // @@protoc_insertion_point(field_get:msg.SimParamsInfo.msg_SimTimestampInfo.utc_timestamp_begin)
  return _internal_utc_timestamp_begin();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void msg_SimTimestampInfo::set_utc_timestamp_begin(ArgT0&& arg0, ArgT... args) {
 
 _impl_.utc_timestamp_begin_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg.SimParamsInfo.msg_SimTimestampInfo.utc_timestamp_begin)
}
inline std::string* msg_SimTimestampInfo::mutable_utc_timestamp_begin() {
  std::string* _s = _internal_mutable_utc_timestamp_begin();
  // @@protoc_insertion_point(field_mutable:msg.SimParamsInfo.msg_SimTimestampInfo.utc_timestamp_begin)
  return _s;
}
inline const std::string& msg_SimTimestampInfo::_internal_utc_timestamp_begin() const {
  return _impl_.utc_timestamp_begin_.Get();
}
inline void msg_SimTimestampInfo::_internal_set_utc_timestamp_begin(const std::string& value) {
  
  _impl_.utc_timestamp_begin_.Set(value, GetArenaForAllocation());
}
inline std::string* msg_SimTimestampInfo::_internal_mutable_utc_timestamp_begin() {
  
  return _impl_.utc_timestamp_begin_.Mutable(GetArenaForAllocation());
}
inline std::string* msg_SimTimestampInfo::release_utc_timestamp_begin() {
  // @@protoc_insertion_point(field_release:msg.SimParamsInfo.msg_SimTimestampInfo.utc_timestamp_begin)
  return _impl_.utc_timestamp_begin_.Release();
}
inline void msg_SimTimestampInfo::set_allocated_utc_timestamp_begin(std::string* utc_timestamp_begin) {
  if (utc_timestamp_begin != nullptr) {
    
  } else {
    
  }
  _impl_.utc_timestamp_begin_.SetAllocated(utc_timestamp_begin, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.utc_timestamp_begin_.IsDefault()) {
    _impl_.utc_timestamp_begin_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg.SimParamsInfo.msg_SimTimestampInfo.utc_timestamp_begin)
}

// string utc_timestamp_cur = 2;
inline void msg_SimTimestampInfo::clear_utc_timestamp_cur() {
  _impl_.utc_timestamp_cur_.ClearToEmpty();
}
inline const std::string& msg_SimTimestampInfo::utc_timestamp_cur() const {
  // @@protoc_insertion_point(field_get:msg.SimParamsInfo.msg_SimTimestampInfo.utc_timestamp_cur)
  return _internal_utc_timestamp_cur();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void msg_SimTimestampInfo::set_utc_timestamp_cur(ArgT0&& arg0, ArgT... args) {
 
 _impl_.utc_timestamp_cur_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg.SimParamsInfo.msg_SimTimestampInfo.utc_timestamp_cur)
}
inline std::string* msg_SimTimestampInfo::mutable_utc_timestamp_cur() {
  std::string* _s = _internal_mutable_utc_timestamp_cur();
  // @@protoc_insertion_point(field_mutable:msg.SimParamsInfo.msg_SimTimestampInfo.utc_timestamp_cur)
  return _s;
}
inline const std::string& msg_SimTimestampInfo::_internal_utc_timestamp_cur() const {
  return _impl_.utc_timestamp_cur_.Get();
}
inline void msg_SimTimestampInfo::_internal_set_utc_timestamp_cur(const std::string& value) {
  
  _impl_.utc_timestamp_cur_.Set(value, GetArenaForAllocation());
}
inline std::string* msg_SimTimestampInfo::_internal_mutable_utc_timestamp_cur() {
  
  return _impl_.utc_timestamp_cur_.Mutable(GetArenaForAllocation());
}
inline std::string* msg_SimTimestampInfo::release_utc_timestamp_cur() {
  // @@protoc_insertion_point(field_release:msg.SimParamsInfo.msg_SimTimestampInfo.utc_timestamp_cur)
  return _impl_.utc_timestamp_cur_.Release();
}
inline void msg_SimTimestampInfo::set_allocated_utc_timestamp_cur(std::string* utc_timestamp_cur) {
  if (utc_timestamp_cur != nullptr) {
    
  } else {
    
  }
  _impl_.utc_timestamp_cur_.SetAllocated(utc_timestamp_cur, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.utc_timestamp_cur_.IsDefault()) {
    _impl_.utc_timestamp_cur_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg.SimParamsInfo.msg_SimTimestampInfo.utc_timestamp_cur)
}

// double sim_timestamp = 3;
inline void msg_SimTimestampInfo::clear_sim_timestamp() {
  _impl_.sim_timestamp_ = 0;
}
inline double msg_SimTimestampInfo::_internal_sim_timestamp() const {
  return _impl_.sim_timestamp_;
}
inline double msg_SimTimestampInfo::sim_timestamp() const {
  // @@protoc_insertion_point(field_get:msg.SimParamsInfo.msg_SimTimestampInfo.sim_timestamp)
  return _internal_sim_timestamp();
}
inline void msg_SimTimestampInfo::_internal_set_sim_timestamp(double value) {
  
  _impl_.sim_timestamp_ = value;
}
inline void msg_SimTimestampInfo::set_sim_timestamp(double value) {
  _internal_set_sim_timestamp(value);
  // @@protoc_insertion_point(field_set:msg.SimParamsInfo.msg_SimTimestampInfo.sim_timestamp)
}

// double physics_timestamp = 4;
inline void msg_SimTimestampInfo::clear_physics_timestamp() {
  _impl_.physics_timestamp_ = 0;
}
inline double msg_SimTimestampInfo::_internal_physics_timestamp() const {
  return _impl_.physics_timestamp_;
}
inline double msg_SimTimestampInfo::physics_timestamp() const {
  // @@protoc_insertion_point(field_get:msg.SimParamsInfo.msg_SimTimestampInfo.physics_timestamp)
  return _internal_physics_timestamp();
}
inline void msg_SimTimestampInfo::_internal_set_physics_timestamp(double value) {
  
  _impl_.physics_timestamp_ = value;
}
inline void msg_SimTimestampInfo::set_physics_timestamp(double value) {
  _internal_set_physics_timestamp(value);
  // @@protoc_insertion_point(field_set:msg.SimParamsInfo.msg_SimTimestampInfo.physics_timestamp)
}

// double step_pos_update_cost = 5;
inline void msg_SimTimestampInfo::clear_step_pos_update_cost() {
  _impl_.step_pos_update_cost_ = 0;
}
inline double msg_SimTimestampInfo::_internal_step_pos_update_cost() const {
  return _impl_.step_pos_update_cost_;
}
inline double msg_SimTimestampInfo::step_pos_update_cost() const {
  // @@protoc_insertion_point(field_get:msg.SimParamsInfo.msg_SimTimestampInfo.step_pos_update_cost)
  return _internal_step_pos_update_cost();
}
inline void msg_SimTimestampInfo::_internal_set_step_pos_update_cost(double value) {
  
  _impl_.step_pos_update_cost_ = value;
}
inline void msg_SimTimestampInfo::set_step_pos_update_cost(double value) {
  _internal_set_step_pos_update_cost(value);
  // @@protoc_insertion_point(field_set:msg.SimParamsInfo.msg_SimTimestampInfo.step_pos_update_cost)
}

// double step_complete_update_cost = 6;
inline void msg_SimTimestampInfo::clear_step_complete_update_cost() {
  _impl_.step_complete_update_cost_ = 0;
}
inline double msg_SimTimestampInfo::_internal_step_complete_update_cost() const {
  return _impl_.step_complete_update_cost_;
}
inline double msg_SimTimestampInfo::step_complete_update_cost() const {
  // @@protoc_insertion_point(field_get:msg.SimParamsInfo.msg_SimTimestampInfo.step_complete_update_cost)
  return _internal_step_complete_update_cost();
}
inline void msg_SimTimestampInfo::_internal_set_step_complete_update_cost(double value) {
  
  _impl_.step_complete_update_cost_ = value;
}
inline void msg_SimTimestampInfo::set_step_complete_update_cost(double value) {
  _internal_set_step_complete_update_cost(value);
  // @@protoc_insertion_point(field_set:msg.SimParamsInfo.msg_SimTimestampInfo.step_complete_update_cost)
}

// double step_call_freq_dt = 8;
inline void msg_SimTimestampInfo::clear_step_call_freq_dt() {
  _impl_.step_call_freq_dt_ = 0;
}
inline double msg_SimTimestampInfo::_internal_step_call_freq_dt() const {
  return _impl_.step_call_freq_dt_;
}
inline double msg_SimTimestampInfo::step_call_freq_dt() const {
  // @@protoc_insertion_point(field_get:msg.SimParamsInfo.msg_SimTimestampInfo.step_call_freq_dt)
  return _internal_step_call_freq_dt();
}
inline void msg_SimTimestampInfo::_internal_set_step_call_freq_dt(double value) {
  
  _impl_.step_call_freq_dt_ = value;
}
inline void msg_SimTimestampInfo::set_step_call_freq_dt(double value) {
  _internal_set_step_call_freq_dt(value);
  // @@protoc_insertion_point(field_set:msg.SimParamsInfo.msg_SimTimestampInfo.step_call_freq_dt)
}

// double step_pos_update_cost_avg = 9;
inline void msg_SimTimestampInfo::clear_step_pos_update_cost_avg() {
  _impl_.step_pos_update_cost_avg_ = 0;
}
inline double msg_SimTimestampInfo::_internal_step_pos_update_cost_avg() const {
  return _impl_.step_pos_update_cost_avg_;
}
inline double msg_SimTimestampInfo::step_pos_update_cost_avg() const {
  // @@protoc_insertion_point(field_get:msg.SimParamsInfo.msg_SimTimestampInfo.step_pos_update_cost_avg)
  return _internal_step_pos_update_cost_avg();
}
inline void msg_SimTimestampInfo::_internal_set_step_pos_update_cost_avg(double value) {
  
  _impl_.step_pos_update_cost_avg_ = value;
}
inline void msg_SimTimestampInfo::set_step_pos_update_cost_avg(double value) {
  _internal_set_step_pos_update_cost_avg(value);
  // @@protoc_insertion_point(field_set:msg.SimParamsInfo.msg_SimTimestampInfo.step_pos_update_cost_avg)
}

// double step_complete_update_avg = 10;
inline void msg_SimTimestampInfo::clear_step_complete_update_avg() {
  _impl_.step_complete_update_avg_ = 0;
}
inline double msg_SimTimestampInfo::_internal_step_complete_update_avg() const {
  return _impl_.step_complete_update_avg_;
}
inline double msg_SimTimestampInfo::step_complete_update_avg() const {
  // @@protoc_insertion_point(field_get:msg.SimParamsInfo.msg_SimTimestampInfo.step_complete_update_avg)
  return _internal_step_complete_update_avg();
}
inline void msg_SimTimestampInfo::_internal_set_step_complete_update_avg(double value) {
  
  _impl_.step_complete_update_avg_ = value;
}
inline void msg_SimTimestampInfo::set_step_complete_update_avg(double value) {
  _internal_set_step_complete_update_avg(value);
  // @@protoc_insertion_point(field_set:msg.SimParamsInfo.msg_SimTimestampInfo.step_complete_update_avg)
}

// double step_call_freq_avg = 11;
inline void msg_SimTimestampInfo::clear_step_call_freq_avg() {
  _impl_.step_call_freq_avg_ = 0;
}
inline double msg_SimTimestampInfo::_internal_step_call_freq_avg() const {
  return _impl_.step_call_freq_avg_;
}
inline double msg_SimTimestampInfo::step_call_freq_avg() const {
  // @@protoc_insertion_point(field_get:msg.SimParamsInfo.msg_SimTimestampInfo.step_call_freq_avg)
  return _internal_step_call_freq_avg();
}
inline void msg_SimTimestampInfo::_internal_set_step_call_freq_avg(double value) {
  
  _impl_.step_call_freq_avg_ = value;
}
inline void msg_SimTimestampInfo::set_step_call_freq_avg(double value) {
  _internal_set_step_call_freq_avg(value);
  // @@protoc_insertion_point(field_set:msg.SimParamsInfo.msg_SimTimestampInfo.step_call_freq_avg)
}

// -------------------------------------------------------------------

// msg_SimParamsInfo

// int32 step_interval = 1;
inline void msg_SimParamsInfo::clear_step_interval() {
  _impl_.step_interval_ = 0;
}
inline int32_t msg_SimParamsInfo::_internal_step_interval() const {
  return _impl_.step_interval_;
}
inline int32_t msg_SimParamsInfo::step_interval() const {
  // @@protoc_insertion_point(field_get:msg.SimParamsInfo.msg_SimParamsInfo.step_interval)
  return _internal_step_interval();
}
inline void msg_SimParamsInfo::_internal_set_step_interval(int32_t value) {
  
  _impl_.step_interval_ = value;
}
inline void msg_SimParamsInfo::set_step_interval(int32_t value) {
  _internal_set_step_interval(value);
  // @@protoc_insertion_point(field_set:msg.SimParamsInfo.msg_SimParamsInfo.step_interval)
}

// double step_dt = 2;
inline void msg_SimParamsInfo::clear_step_dt() {
  _impl_.step_dt_ = 0;
}
inline double msg_SimParamsInfo::_internal_step_dt() const {
  return _impl_.step_dt_;
}
inline double msg_SimParamsInfo::step_dt() const {
  // @@protoc_insertion_point(field_get:msg.SimParamsInfo.msg_SimParamsInfo.step_dt)
  return _internal_step_dt();
}
inline void msg_SimParamsInfo::_internal_set_step_dt(double value) {
  
  _impl_.step_dt_ = value;
}
inline void msg_SimParamsInfo::set_step_dt(double value) {
  _internal_set_step_dt(value);
  // @@protoc_insertion_point(field_set:msg.SimParamsInfo.msg_SimParamsInfo.step_dt)
}

// double step_freq = 3;
inline void msg_SimParamsInfo::clear_step_freq() {
  _impl_.step_freq_ = 0;
}
inline double msg_SimParamsInfo::_internal_step_freq() const {
  return _impl_.step_freq_;
}
inline double msg_SimParamsInfo::step_freq() const {
  // @@protoc_insertion_point(field_get:msg.SimParamsInfo.msg_SimParamsInfo.step_freq)
  return _internal_step_freq();
}
inline void msg_SimParamsInfo::_internal_set_step_freq(double value) {
  
  _impl_.step_freq_ = value;
}
inline void msg_SimParamsInfo::set_step_freq(double value) {
  _internal_set_step_freq(value);
  // @@protoc_insertion_point(field_set:msg.SimParamsInfo.msg_SimParamsInfo.step_freq)
}

// double one_second_sim_step_second = 4;
inline void msg_SimParamsInfo::clear_one_second_sim_step_second() {
  _impl_.one_second_sim_step_second_ = 0;
}
inline double msg_SimParamsInfo::_internal_one_second_sim_step_second() const {
  return _impl_.one_second_sim_step_second_;
}
inline double msg_SimParamsInfo::one_second_sim_step_second() const {
  // @@protoc_insertion_point(field_get:msg.SimParamsInfo.msg_SimParamsInfo.one_second_sim_step_second)
  return _internal_one_second_sim_step_second();
}
inline void msg_SimParamsInfo::_internal_set_one_second_sim_step_second(double value) {
  
  _impl_.one_second_sim_step_second_ = value;
}
inline void msg_SimParamsInfo::set_one_second_sim_step_second(double value) {
  _internal_set_one_second_sim_step_second(value);
  // @@protoc_insertion_point(field_set:msg.SimParamsInfo.msg_SimParamsInfo.one_second_sim_step_second)
}

// int32 agentinstance_num = 5;
inline void msg_SimParamsInfo::clear_agentinstance_num() {
  _impl_.agentinstance_num_ = 0;
}
inline int32_t msg_SimParamsInfo::_internal_agentinstance_num() const {
  return _impl_.agentinstance_num_;
}
inline int32_t msg_SimParamsInfo::agentinstance_num() const {
  // @@protoc_insertion_point(field_get:msg.SimParamsInfo.msg_SimParamsInfo.agentinstance_num)
  return _internal_agentinstance_num();
}
inline void msg_SimParamsInfo::_internal_set_agentinstance_num(int32_t value) {
  
  _impl_.agentinstance_num_ = value;
}
inline void msg_SimParamsInfo::set_agentinstance_num(int32_t value) {
  _internal_set_agentinstance_num(value);
  // @@protoc_insertion_point(field_set:msg.SimParamsInfo.msg_SimParamsInfo.agentinstance_num)
}

// .msg.SimParamsInfo.msg_SimTimestampInfo simtimestamp = 6;
inline bool msg_SimParamsInfo::_internal_has_simtimestamp() const {
  return this != internal_default_instance() && _impl_.simtimestamp_ != nullptr;
}
inline bool msg_SimParamsInfo::has_simtimestamp() const {
  return _internal_has_simtimestamp();
}
inline void msg_SimParamsInfo::clear_simtimestamp() {
  if (GetArenaForAllocation() == nullptr && _impl_.simtimestamp_ != nullptr) {
    delete _impl_.simtimestamp_;
  }
  _impl_.simtimestamp_ = nullptr;
}
inline const ::msg::SimParamsInfo::msg_SimTimestampInfo& msg_SimParamsInfo::_internal_simtimestamp() const {
  const ::msg::SimParamsInfo::msg_SimTimestampInfo* p = _impl_.simtimestamp_;
  return p != nullptr ? *p : reinterpret_cast<const ::msg::SimParamsInfo::msg_SimTimestampInfo&>(
      ::msg::SimParamsInfo::_msg_SimTimestampInfo_default_instance_);
}
inline const ::msg::SimParamsInfo::msg_SimTimestampInfo& msg_SimParamsInfo::simtimestamp() const {
  // @@protoc_insertion_point(field_get:msg.SimParamsInfo.msg_SimParamsInfo.simtimestamp)
  return _internal_simtimestamp();
}
inline void msg_SimParamsInfo::unsafe_arena_set_allocated_simtimestamp(
    ::msg::SimParamsInfo::msg_SimTimestampInfo* simtimestamp) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.simtimestamp_);
  }
  _impl_.simtimestamp_ = simtimestamp;
  if (simtimestamp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:msg.SimParamsInfo.msg_SimParamsInfo.simtimestamp)
}
inline ::msg::SimParamsInfo::msg_SimTimestampInfo* msg_SimParamsInfo::release_simtimestamp() {
  
  ::msg::SimParamsInfo::msg_SimTimestampInfo* temp = _impl_.simtimestamp_;
  _impl_.simtimestamp_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::msg::SimParamsInfo::msg_SimTimestampInfo* msg_SimParamsInfo::unsafe_arena_release_simtimestamp() {
  // @@protoc_insertion_point(field_release:msg.SimParamsInfo.msg_SimParamsInfo.simtimestamp)
  
  ::msg::SimParamsInfo::msg_SimTimestampInfo* temp = _impl_.simtimestamp_;
  _impl_.simtimestamp_ = nullptr;
  return temp;
}
inline ::msg::SimParamsInfo::msg_SimTimestampInfo* msg_SimParamsInfo::_internal_mutable_simtimestamp() {
  
  if (_impl_.simtimestamp_ == nullptr) {
    auto* p = CreateMaybeMessage<::msg::SimParamsInfo::msg_SimTimestampInfo>(GetArenaForAllocation());
    _impl_.simtimestamp_ = p;
  }
  return _impl_.simtimestamp_;
}
inline ::msg::SimParamsInfo::msg_SimTimestampInfo* msg_SimParamsInfo::mutable_simtimestamp() {
  ::msg::SimParamsInfo::msg_SimTimestampInfo* _msg = _internal_mutable_simtimestamp();
  // @@protoc_insertion_point(field_mutable:msg.SimParamsInfo.msg_SimParamsInfo.simtimestamp)
  return _msg;
}
inline void msg_SimParamsInfo::set_allocated_simtimestamp(::msg::SimParamsInfo::msg_SimTimestampInfo* simtimestamp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.simtimestamp_;
  }
  if (simtimestamp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(simtimestamp);
    if (message_arena != submessage_arena) {
      simtimestamp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, simtimestamp, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.simtimestamp_ = simtimestamp;
  // @@protoc_insertion_point(field_set_allocated:msg.SimParamsInfo.msg_SimParamsInfo.simtimestamp)
}

// double speed = 7;
inline void msg_SimParamsInfo::clear_speed() {
  _impl_.speed_ = 0;
}
inline double msg_SimParamsInfo::_internal_speed() const {
  return _impl_.speed_;
}
inline double msg_SimParamsInfo::speed() const {
  // @@protoc_insertion_point(field_get:msg.SimParamsInfo.msg_SimParamsInfo.speed)
  return _internal_speed();
}
inline void msg_SimParamsInfo::_internal_set_speed(double value) {
  
  _impl_.speed_ = value;
}
inline void msg_SimParamsInfo::set_speed(double value) {
  _internal_set_speed(value);
  // @@protoc_insertion_point(field_set:msg.SimParamsInfo.msg_SimParamsInfo.speed)
}

// -------------------------------------------------------------------

// msg_BinaryData

// uint64 packindex = 1;
inline void msg_BinaryData::clear_packindex() {
  _impl_.packindex_ = uint64_t{0u};
}
inline uint64_t msg_BinaryData::_internal_packindex() const {
  return _impl_.packindex_;
}
inline uint64_t msg_BinaryData::packindex() const {
  // @@protoc_insertion_point(field_get:msg.SimParamsInfo.msg_BinaryData.packindex)
  return _internal_packindex();
}
inline void msg_BinaryData::_internal_set_packindex(uint64_t value) {
  
  _impl_.packindex_ = value;
}
inline void msg_BinaryData::set_packindex(uint64_t value) {
  _internal_set_packindex(value);
  // @@protoc_insertion_point(field_set:msg.SimParamsInfo.msg_BinaryData.packindex)
}

// int32 binarysize = 2;
inline void msg_BinaryData::clear_binarysize() {
  _impl_.binarysize_ = 0;
}
inline int32_t msg_BinaryData::_internal_binarysize() const {
  return _impl_.binarysize_;
}
inline int32_t msg_BinaryData::binarysize() const {
  // @@protoc_insertion_point(field_get:msg.SimParamsInfo.msg_BinaryData.binarysize)
  return _internal_binarysize();
}
inline void msg_BinaryData::_internal_set_binarysize(int32_t value) {
  
  _impl_.binarysize_ = value;
}
inline void msg_BinaryData::set_binarysize(int32_t value) {
  _internal_set_binarysize(value);
  // @@protoc_insertion_point(field_set:msg.SimParamsInfo.msg_BinaryData.binarysize)
}

// uint64 timestamp = 3;
inline void msg_BinaryData::clear_timestamp() {
  _impl_.timestamp_ = uint64_t{0u};
}
inline uint64_t msg_BinaryData::_internal_timestamp() const {
  return _impl_.timestamp_;
}
inline uint64_t msg_BinaryData::timestamp() const {
  // @@protoc_insertion_point(field_get:msg.SimParamsInfo.msg_BinaryData.timestamp)
  return _internal_timestamp();
}
inline void msg_BinaryData::_internal_set_timestamp(uint64_t value) {
  
  _impl_.timestamp_ = value;
}
inline void msg_BinaryData::set_timestamp(uint64_t value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:msg.SimParamsInfo.msg_BinaryData.timestamp)
}

// bytes binarydata = 4;
inline void msg_BinaryData::clear_binarydata() {
  _impl_.binarydata_.ClearToEmpty();
}
inline const std::string& msg_BinaryData::binarydata() const {
  // @@protoc_insertion_point(field_get:msg.SimParamsInfo.msg_BinaryData.binarydata)
  return _internal_binarydata();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void msg_BinaryData::set_binarydata(ArgT0&& arg0, ArgT... args) {
 
 _impl_.binarydata_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:msg.SimParamsInfo.msg_BinaryData.binarydata)
}
inline std::string* msg_BinaryData::mutable_binarydata() {
  std::string* _s = _internal_mutable_binarydata();
  // @@protoc_insertion_point(field_mutable:msg.SimParamsInfo.msg_BinaryData.binarydata)
  return _s;
}
inline const std::string& msg_BinaryData::_internal_binarydata() const {
  return _impl_.binarydata_.Get();
}
inline void msg_BinaryData::_internal_set_binarydata(const std::string& value) {
  
  _impl_.binarydata_.Set(value, GetArenaForAllocation());
}
inline std::string* msg_BinaryData::_internal_mutable_binarydata() {
  
  return _impl_.binarydata_.Mutable(GetArenaForAllocation());
}
inline std::string* msg_BinaryData::release_binarydata() {
  // @@protoc_insertion_point(field_release:msg.SimParamsInfo.msg_BinaryData.binarydata)
  return _impl_.binarydata_.Release();
}
inline void msg_BinaryData::set_allocated_binarydata(std::string* binarydata) {
  if (binarydata != nullptr) {
    
  } else {
    
  }
  _impl_.binarydata_.SetAllocated(binarydata, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.binarydata_.IsDefault()) {
    _impl_.binarydata_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:msg.SimParamsInfo.msg_BinaryData.binarydata)
}

// -------------------------------------------------------------------

// msg_BinaryData_Array

// uint64 packindex = 1;
inline void msg_BinaryData_Array::clear_packindex() {
  _impl_.packindex_ = uint64_t{0u};
}
inline uint64_t msg_BinaryData_Array::_internal_packindex() const {
  return _impl_.packindex_;
}
inline uint64_t msg_BinaryData_Array::packindex() const {
  // @@protoc_insertion_point(field_get:msg.SimParamsInfo.msg_BinaryData_Array.packindex)
  return _internal_packindex();
}
inline void msg_BinaryData_Array::_internal_set_packindex(uint64_t value) {
  
  _impl_.packindex_ = value;
}
inline void msg_BinaryData_Array::set_packindex(uint64_t value) {
  _internal_set_packindex(value);
  // @@protoc_insertion_point(field_set:msg.SimParamsInfo.msg_BinaryData_Array.packindex)
}

// repeated .msg.SimParamsInfo.msg_BinaryData binarydatas = 2;
inline int msg_BinaryData_Array::_internal_binarydatas_size() const {
  return _impl_.binarydatas_.size();
}
inline int msg_BinaryData_Array::binarydatas_size() const {
  return _internal_binarydatas_size();
}
inline void msg_BinaryData_Array::clear_binarydatas() {
  _impl_.binarydatas_.Clear();
}
inline ::msg::SimParamsInfo::msg_BinaryData* msg_BinaryData_Array::mutable_binarydatas(int index) {
  // @@protoc_insertion_point(field_mutable:msg.SimParamsInfo.msg_BinaryData_Array.binarydatas)
  return _impl_.binarydatas_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::msg::SimParamsInfo::msg_BinaryData >*
msg_BinaryData_Array::mutable_binarydatas() {
  // @@protoc_insertion_point(field_mutable_list:msg.SimParamsInfo.msg_BinaryData_Array.binarydatas)
  return &_impl_.binarydatas_;
}
inline const ::msg::SimParamsInfo::msg_BinaryData& msg_BinaryData_Array::_internal_binarydatas(int index) const {
  return _impl_.binarydatas_.Get(index);
}
inline const ::msg::SimParamsInfo::msg_BinaryData& msg_BinaryData_Array::binarydatas(int index) const {
  // @@protoc_insertion_point(field_get:msg.SimParamsInfo.msg_BinaryData_Array.binarydatas)
  return _internal_binarydatas(index);
}
inline ::msg::SimParamsInfo::msg_BinaryData* msg_BinaryData_Array::_internal_add_binarydatas() {
  return _impl_.binarydatas_.Add();
}
inline ::msg::SimParamsInfo::msg_BinaryData* msg_BinaryData_Array::add_binarydatas() {
  ::msg::SimParamsInfo::msg_BinaryData* _add = _internal_add_binarydatas();
  // @@protoc_insertion_point(field_add:msg.SimParamsInfo.msg_BinaryData_Array.binarydatas)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::msg::SimParamsInfo::msg_BinaryData >&
msg_BinaryData_Array::binarydatas() const {
  // @@protoc_insertion_point(field_list:msg.SimParamsInfo.msg_BinaryData_Array.binarydatas)
  return _impl_.binarydatas_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace SimParamsInfo
}  // namespace msg

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_SimParamsInfo_2eproto
