// source: AgentCommSnrInfo.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.repeatedFields_, null);
};
goog.inherits(proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.displayName = 'proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.repeatedFields_ = [12,13];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    srcAgent: jspb.Message.getFieldWithDefault(msg, 1, ""),
    dstAgent: jspb.Message.getFieldWithDefault(msg, 2, ""),
    sensingmediaid: jspb.Message.getFieldWithDefault(msg, 3, ""),
    tmplmodsig: jspb.Message.getFieldWithDefault(msg, 4, ""),
    positive: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
    bandwidth: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
    sinr: jspb.Message.getFloatingPointFieldWithDefault(msg, 7, 0.0),
    snr: jspb.Message.getFloatingPointFieldWithDefault(msg, 8, 0.0),
    freqhzb: jspb.Message.getFloatingPointFieldWithDefault(msg, 9, 0.0),
    aIffcode: jspb.Message.getFieldWithDefault(msg, 10, ""),
    bIffcode: jspb.Message.getFieldWithDefault(msg, 11, ""),
    aClustercodesList: (f = jspb.Message.getRepeatedField(msg, 12)) == null ? undefined : f,
    bClustercodesList: (f = jspb.Message.getRepeatedField(msg, 13)) == null ? undefined : f,
    packindex: jspb.Message.getFieldWithDefault(msg, 14, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo}
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo;
  return proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo}
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSrcAgent(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDstAgent(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSensingmediaid(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setTmplmodsig(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPositive(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setBandwidth(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setSinr(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setSnr(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setFreqhzb(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setAIffcode(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setBIffcode(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.addAClustercodes(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.addBClustercodes(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setPackindex(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSrcAgent();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDstAgent();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSensingmediaid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getTmplmodsig();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getPositive();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getBandwidth();
  if (f !== 0.0) {
    writer.writeDouble(
      6,
      f
    );
  }
  f = message.getSinr();
  if (f !== 0.0) {
    writer.writeDouble(
      7,
      f
    );
  }
  f = message.getSnr();
  if (f !== 0.0) {
    writer.writeDouble(
      8,
      f
    );
  }
  f = message.getFreqhzb();
  if (f !== 0.0) {
    writer.writeDouble(
      9,
      f
    );
  }
  f = message.getAIffcode();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getBIffcode();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getAClustercodesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      12,
      f
    );
  }
  f = message.getBClustercodesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      13,
      f
    );
  }
  f = message.getPackindex();
  if (f !== 0) {
    writer.writeUint32(
      14,
      f
    );
  }
};


/**
 * optional string src_agent = 1;
 * @return {string}
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.prototype.getSrcAgent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo} returns this
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.prototype.setSrcAgent = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string dst_agent = 2;
 * @return {string}
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.prototype.getDstAgent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo} returns this
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.prototype.setDstAgent = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string sensingmediaid = 3;
 * @return {string}
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.prototype.getSensingmediaid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo} returns this
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.prototype.setSensingmediaid = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string tmplmodsig = 4;
 * @return {string}
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.prototype.getTmplmodsig = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo} returns this
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.prototype.setTmplmodsig = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional bool positive = 5;
 * @return {boolean}
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.prototype.getPositive = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo} returns this
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.prototype.setPositive = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional double bandwidth = 6;
 * @return {number}
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.prototype.getBandwidth = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo} returns this
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.prototype.setBandwidth = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional double sinr = 7;
 * @return {number}
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.prototype.getSinr = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo} returns this
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.prototype.setSinr = function(value) {
  return jspb.Message.setProto3FloatField(this, 7, value);
};


/**
 * optional double snr = 8;
 * @return {number}
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.prototype.getSnr = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 8, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo} returns this
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.prototype.setSnr = function(value) {
  return jspb.Message.setProto3FloatField(this, 8, value);
};


/**
 * optional double freqHzB = 9;
 * @return {number}
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.prototype.getFreqhzb = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 9, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo} returns this
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.prototype.setFreqhzb = function(value) {
  return jspb.Message.setProto3FloatField(this, 9, value);
};


/**
 * optional string a_iffcode = 10;
 * @return {string}
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.prototype.getAIffcode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo} returns this
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.prototype.setAIffcode = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string b_iffcode = 11;
 * @return {string}
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.prototype.getBIffcode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo} returns this
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.prototype.setBIffcode = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * repeated string a_clusterCodes = 12;
 * @return {!Array<string>}
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.prototype.getAClustercodesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 12));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo} returns this
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.prototype.setAClustercodesList = function(value) {
  return jspb.Message.setField(this, 12, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo} returns this
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.prototype.addAClustercodes = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 12, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo} returns this
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.prototype.clearAClustercodesList = function() {
  return this.setAClustercodesList([]);
};


/**
 * repeated string b_clusterCodes = 13;
 * @return {!Array<string>}
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.prototype.getBClustercodesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 13));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo} returns this
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.prototype.setBClustercodesList = function(value) {
  return jspb.Message.setField(this, 13, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo} returns this
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.prototype.addBClustercodes = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 13, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo} returns this
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.prototype.clearBClustercodesList = function() {
  return this.setBClustercodesList([]);
};


/**
 * optional uint32 packindex = 14;
 * @return {number}
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.prototype.getPackindex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/**
 * @param {number} value
 * @return {!proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo} returns this
 */
proto.msg.AgentCommSnrInfo.msg_AgentCommSnrInfo.prototype.setPackindex = function(value) {
  return jspb.Message.setProto3IntField(this, 14, value);
};


goog.object.extend(exports, proto.msg.AgentCommSnrInfo);
