// source: CommStackFrameResultElement.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.displayName = 'proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.prototype.toObject = function(opt_includeInstance) {
  return proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.toObject = function(includeInstance, msg) {
  var f, obj = {
    srcAgent: jspb.Message.getFieldWithDefault(msg, 1, ""),
    dstAgent: jspb.Message.getFieldWithDefault(msg, 2, ""),
    engineKeyedName: jspb.Message.getFieldWithDefault(msg, 3, ""),
    ber: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    fer: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    framehextext: jspb.Message.getFieldWithDefault(msg, 6, ""),
    packindex: jspb.Message.getFieldWithDefault(msg, 7, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement}
 */
proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement;
  return proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement}
 */
proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSrcAgent(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDstAgent(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setEngineKeyedName(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setBer(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setFer(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setFramehextext(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setPackindex(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSrcAgent();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDstAgent();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getEngineKeyedName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getBer();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
  f = message.getFer();
  if (f !== 0.0) {
    writer.writeFloat(
      5,
      f
    );
  }
  f = message.getFramehextext();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getPackindex();
  if (f !== 0) {
    writer.writeUint32(
      7,
      f
    );
  }
};


/**
 * optional string src_agent = 1;
 * @return {string}
 */
proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.prototype.getSrcAgent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement} returns this
 */
proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.prototype.setSrcAgent = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string dst_agent = 2;
 * @return {string}
 */
proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.prototype.getDstAgent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement} returns this
 */
proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.prototype.setDstAgent = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string engine_keyed_name = 3;
 * @return {string}
 */
proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.prototype.getEngineKeyedName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement} returns this
 */
proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.prototype.setEngineKeyedName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional float ber = 4;
 * @return {number}
 */
proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.prototype.getBer = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement} returns this
 */
proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.prototype.setBer = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional float fer = 5;
 * @return {number}
 */
proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.prototype.getFer = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement} returns this
 */
proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.prototype.setFer = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional string framehextext = 6;
 * @return {string}
 */
proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.prototype.getFramehextext = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement} returns this
 */
proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.prototype.setFramehextext = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional uint32 packindex = 7;
 * @return {number}
 */
proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.prototype.getPackindex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement} returns this
 */
proto.msg.CommStackFrameResultElement.msg_CommStackFrameResultElement.prototype.setPackindex = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


goog.object.extend(exports, proto.msg.CommStackFrameResultElement);
