#ifndef GAEACTOR_AGENT_CORES_GLOBAL_H
#define GAEACTOR_AGENT_CORES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GAEACTOR_AGENT_CORES_LIBRARY)
#  define GAEACTOR_AGENT_CORES_EXPORT Q_DECL_EXPORT
#else
#  define GAEACTOR_AGENT_CORES_EXPORT Q_DECL_IMPORT
#endif

#endif // GAEACTOR_AGENT_CORES_GLOBAL_H
